### ISSUE TITLE
Sharing on Facebook

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1013]
Is it expected behavior, that when sharing on Facebook, both the parameter in subject and message are ignored, and only the URL are shown if present?

**Comment by EddyVerbruggen** [comment]
Yes. Please search for similar issues before opening one. Thanks.

**Comment by ThorvaldAagaard** [comment]
I did search issues for this plugin, but did not find the requested information, hence my question 

But I will recommend to add this in the documentation, so other won't have to read all the issues (or at least link to the issues I might have missed in my reading.
