### ISSUE TITLE
[iOS] CDVPlugin class SocialSharing (pluginName: socialsharing) does not exist

### ISSUE THREAD

**Issue by hariramnandagopal** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1021]
Hey,

I am getting this error when I try to run the app. Please let me know if this expected in iOS 12+

```
[28811: 7534] CDVPlugin class SocialSharing (pluginName: socialsharing) does not exist.
[28811: 7532] [CDVTimer][socialsharing] 0.08297
```

```
Simulator- iPhone X - OS Version - 12.1
Xcode Version - 10.1
```

package.json

```
"cordova-plugin-x-socialsharing": "^5.4.4"
```

config.xml

```
<plugin name="cordova-plugin-x-socialsharing" spec="~5.4.4" />
```

Executing `window.plugins.socialsharing` in browser console (debugging thru browser), shows me `SocialSharing` function and its methods in the console. 

The same plugin works as expected for Android.

let me know if any of my configs are wrong or if you need more details to investigate.

**Comment by yassoni** [comment]
Is it solved ?

**Comment by hariramnandagopal** [comment]
Hey, yeah its more of build issue which resolved later a day or two.

**Comment by fariazz** [comment]
@hariramnandagopal how did you solve it?

**Comment by cuongdevjs** [comment]
still, have this error when running on ios? Haven't any updates to resolve it? @hariramnandagopal
