### ISSUE TITLE
Issue with Whatsapp on Android 

### ISSUE THREAD

**Issue by JerryBels** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1022]
When trying to share to whatsapp on Android, I simply get "Sharing failed, please try again". Some time ago it was working perfectly.

      this.socialSharing.share(
        res['SHARE_TEXT'],
        res['SHARE_TITLE'],
        this.image,
        this.url
      )

**Comment by JerryBels** [comment]
Looks like it's because the media was in an unsupported format - you have no error telling it whatsoever but removing the image part made it work.

**Comment by coffeverton** [comment]
That's a lifesaver tip! thank you so much!

**Comment by JerryBels** [comment]
You're welcome :)
