### ISSUE TITLE
how to use social sharing in browser(pwa app) ?

### ISSUE THREAD

**Issue by shomid** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1029]
how to use social sharing in browser(pwa app) ?
this work correctly in native app but not work in browser.
but when use in browser throw warning:

     Native: tried calling SocialSharing.share, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

**Comment by EddyVerbruggen** [comment]
Does this help? https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#5-web-share-api
