### ISSUE TITLE
Setting NSPhotoLibraryUsageDescription to "This app requires photo library access to function properly" will get your app rejected by Apple

### ISSUE THREAD

**Issue by asgeo1** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1030]
I just had my app rejected by Apple, for the following reason.

> Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
> 
> We noticed that your app requests the user’s consent to access their photos but does not clarify the use of the photos in the applicable purpose string.

I looked through my app, and it seems this plugin is the culprit. It's adding the following into plist.info

```
    <config-file target="*-Info.plist" parent="NSPhotoLibraryAddUsageDescription">
      <string>This app requires photo library access to function properly.</string>
    </config-file>

    <config-file target ="*-Info.plist" parent="NSPhotoLibraryUsageDescription">
      <string>This app requires photo library access to function properly.</string>
    </config-file>
```

So that text needs to be updated to a genuine reason.

But it also begs the question... why even include that at all in the plugin?  Why not let people include that configuration in their own config.xml?   Then people can provide their own descriptions.

I tried doing that myself, but unfortunately Cordova uses your setting rather than my own.

**Comment by EddyVerbruggen** [comment]
Hi! I'd happily merge a PR that externalises those usage description properties so folks can override the default message. Much like this: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/2bed8a66f984d6fb4164751f15bc45fbfdc8943b/plugin.xml#L53-L57 (only I'd rather see the default being what it is now). You up for it?

**Comment by asgeo1** [comment]
Sure, just sent a PR

**Comment by EddyVerbruggen** [comment]
Awesome, man! Let me merge and release that right away! 💪
