### ISSUE TITLE
iOS: Any plan to remove UIWebView and use WKWebView instead?

### ISSUE THREAD

**Issue by joelz** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1052]
Hi,

Recently people has started receiving this warning when submitting apps that have references to UIWebView.

>ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.

Here's a Twitter thread from one Apple dev on the topic: https://twitter.com/NiklasMaerz/status/1167031874738434048

Although our app (which used this plugin) has not received the warning yet, but I find this plugin also uses `UIWebView`:

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/4740df80faabf38cccc7d66803769690205fc0d6/src/ios/SocialSharing.m#L37

So is there any plan to remove UIWebView reference and use WKWebView instead?

Thanks.

**Comment by EddyVerbruggen** [comment]
I've removed it in 5.6.0 so the `iPadPopupCoordinates` feature no longer works until someone makes it `WKWebView` compatible.

**Comment by tryhardest** [comment]
Nice. We must be on an old version as we still saw references. Will upgrade thank you. For this interested https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html
