### ISSUE TITLE
wechat sdk

### ISSUE THREAD

**Issue by kakkuk** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#106]
it is possible to add wechat sdk in this plugin
thank you

**Comment by jianbo** [comment]
Does this work in IOS? Doesn't seems to be working for me

**Comment by EddyVerbruggen** [comment]
It doesn't until WeChat adds an iOS8 extension to its iOS app. I advise you to stalk WeChat for that feature. Others like LinkedIN, Wunderlist, Tumblr, etc have added an extension to their apps so it pops up in the native iOS share sheet which is used by the SocialSharing plugin.
