### ISSUE TITLE
problem with ios(NSNull componenetsSeparatedBy String)

### ISSUE THREAD

**Issue by dufrein** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1066]
Hello, few days ago I faced the error on IOS (on android all good)  when I try to call  
` window.plugins.socialsharing.share(null, gameName, gameInBase64, null) `
where gameInBase64 is object
 I got error in xcode:

```
NSNull componentsSeparatedByString:]: unrecognized selector sent to instance 0x1c674d7f0
2019-10-16 13:40:34.950914+0400 myAppName[606:118601] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull componentsSeparatedByString:]: unrecognized selector sent to instance 0x1c674d7f0'
*** First throw call stack:
(0x196676190 0x19584b9f8 0x1965929cc 0x19667b9d8 0x19667d66c 0x100e31b74 0x100f736f4 0x100f74c78 0x100f77ad4 0x100f85dc8 0x100f867ac 0x1962921b4 0x196294cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

do you know what is the reason of it?
thx

so, I read your docs about use shareWithOptions instead share, but I don't understand how I can pass to  shareWithOptions my object gameInBase64, can you explain more clearly. I am junior in web and  cordova mobile)

**Comment by EddyVerbruggen** [comment]
I think that’s caused by the change in #1057 - can you ping the author of the PR there?

**Comment by dufrein** [comment]
thx for fast answer, this problem cuased about 5 days ago, 10 days ago all was good.
I don't know he author of the PR, how I can do it?

**Comment by EddyVerbruggen** [comment]
You’re probably not pinning to a specific version so you automatically pulled in the latest version. If you pin to the previous version it should be all good. I’ll ping the author in the other issue.

**Comment by dufrein** [comment]
thx. what version of plugin  I must use? 5.6.0 ?

**Comment by EddyVerbruggen** [comment]
Yep

**Comment by dufrein** [comment]
yes it's works)!

**Comment by EddyVerbruggen** [comment]
Updating to 5.6.2 should now also fix this. Thanks to @TaDaa 👍
