### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by clemdesign** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1070]
So, first thank you for your great plugin!
For the next versions, could you provide a CHANGELOG please?

**Comment by EddyVerbruggen** [comment]
Nope, that would take too much of my time. If you can automate it and send a PR then I'd be happy to merge it though.

But there's an alternative: I always assign a milestone to an issue so you can simply look at the list of closed items for each version, like: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/milestone/20?closed=1
