### ISSUE TITLE
Problem sharing images - panel opens, then whatsapp open fails

### ISSUE THREAD

**Issue by ttthub** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1071]
➜ ionic info

Ionic:

   Ionic CLI                     : 5.4.2
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 28 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.16.3
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.1 Build version 11A1027

cordova-plugin-x-socialsharing 5.6.1 "SocialSharing"

When trying to share image with text, the share panel opens. Then on selecting whatsapp, this error occurs:

_Share panel open failed:  Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference_

**Comment by nvwebm** [comment]
Hi, I'm dealing with the same issue, someone has ideas?

**Comment by guikeller** [comment]
Hi @ttthub ,

Have a look at issue #1026 it seems like the same exception.
It also has a workaround, hope this helps.

Cheers!

**Comment by ttthub** [comment]
Apologies I should have updated here, we indeed resolved it using the workaround on #1026 

Thank you
