### ISSUE TITLE
Format String Attack

### ISSUE THREAD

**Issue by trangnt-bkhn** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1072]
We have scanned the code and finded the issue at line 768. Can you check more in photos.

![image](https://user-images.githubusercontent.com/56822255/67358231-55801b00-f592-11e9-8bfb-f271a134a9d0.png)

**Comment by EddyVerbruggen** [comment]
If you'd like to see this changed please open a PR instead of dropping this on me.

**Comment by trangnt-bkhn** [comment]
How can I do for this issue fixed by you?
