### ISSUE TITLE
Uncaught TypeError: Cannot read property 'socialsharing' of undefined

### ISSUE THREAD

**Issue by wasemanam** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#109]
i included SocialSharing.js and added reference to the page where im sharing. when i press the share button log show following error:
Uncaught TypeError: Cannot read property 'socialsharing' of undefined at file:///android_asset/www/js/articleDetails.js:60

im calling it from articleDetails.js page

function sharePost(){
    $(window).plugins.socialsharing.share('Test Share', null, null, 'http://link');
}

**Comment by pedroabreu** [comment]
Getting the same issue as you guys.

Using Ionic with ngcordova. Can use, for example, the inappbrowser without any issue, but when I try to use the $cordovaSocialSharing I get:

TypeError: Cannot read property 'socialsharing' of undefined

Has anybody found a solution for this ? Using Ionic beta 14, ngCordova alpha 10

**Comment by Purus** [comment]
Same issue to me too.. How could this be solved?

I am using ngCordova and Ionic.

**Comment by EddyVerbruggen** [comment]
@Purus, @pedroabreu you're trying this on a real device, right?
Also, you're sure `deviceready` has fired before using the plugin?

**Comment by Purus** [comment]
@EddyVerbruggen Yes, I am trying on my real device - Moto G, KitKat 4.4.4

I am wrapping the code inside my Ionic device ready event.

**Comment by EddyVerbruggen** [comment]
Sounds good to me. Did you add the plugin and ran `cordova prepare`? Is the plugin listed in `cordova_plugins.js`?

**Comment by Purus** [comment]
Yes. I ran phonegap prepare. The plugin is in cordiva-plugins.js file at
the end.

**Comment by EddyVerbruggen** [comment]
Odd - can you share your Android project with me?

**Comment by Purus** [comment]
Sure. You mean the project present inside the platforms/Android directory?

To which email I should send? I will send morning. Thanks for your help.

**Comment by EddyVerbruggen** [comment]
That would do it, email me at eddyverbruggen at gmail

**Comment by pedroabreu** [comment]
@EddyVerbruggen yeah, the issue was it wasn't wrapped in a ionicPlatform.ready and that I wasn't testing on a real device.
Thanks for the help anyway.

**Comment by Purus** [comment]
@EddyVerbruggen: It works now. I am not sure what I changed. Thanks for your help.

**Comment by ElenaZueva** [comment]
I guess you need to include plugin after your deviceready event has been fired

**Comment by wal-nadeem** [comment]
does this work only on real device?

**Comment by alsfurlan** [comment]
@ElenaZueva How I do that?

**Comment by arifraven** [comment]
Hi guys..I am using using jquery mobile and phonegap.got the same error.was able to make it work by replacing the first line in SocialSharing.js
change
`var cordova = require('cordova');`
to 
`var cordova = window.cordova;`

**Comment by sagarora77** [comment]
In ionic, check **cordova plugin list**
If plugin exists, build the project using ionic build <platform>
Code working fine, doesn't works well in browser window.

**Comment by Drey77** [comment]
Hello, 
@arifraven, i tried your solution but now it is stuck on 

> Cannot read property 'addConstructor' of undefined           SocialSharing.js:120

And I also have the "require is not defined"  issue  from "cordova.js:29"

**Comment by arifraven** [comment]
@Drey77 please check #268 hope it will solve the issue

**Comment by Drey77** [comment]
@arifraven thx but i was on that issue before reading this one, and I have tried what was advised there. Still stuck

**Comment by serdarde** [comment]
just a remind for the guys who forgot the cordova.js line like me: 

`<script type="text/javascript" src="cordova.js"></script>`
