### ISSUE TITLE
Apple detects UIWebView depreciation using latest version of social sharing

### ISSUE THREAD

**Issue by noxiousmobile** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1094]
I got rejected by apple.
I do see that the plugin still returns (UIWebview*)self.webview in /src.ios

This must be removed.

**Comment by niels-qup** [comment]
Yes, this is also preventing me from using this plugin. April 30 apple will block any new apps using this UIWebview

**Comment by EddyVerbruggen** [comment]
@noxiousmobile If you mean this:

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/9468f0afbffc38f4d4596b8f946e2de7108ee1cb/src/ios/SocialSharing.m#L41

Then you'll be pleased to learn you can update to a newer plugin version for some time now.
