### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

### ISSUE THREAD

**Issue by Kavyagupta24** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1102]
I'm using Cordova to build iOS apps. When I'm uploading a build to AppStoreConnect, I'm getting the well known deprecation message:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

The plugin is using UIWebView.
Please update the plugin removing all UIWebView usage and using WKWebView or please let me know if we can use some other alternative plugin.

**Comment by EddyVerbruggen** [comment]
I'm pretty sure the latest published version already no longer uses `UIWebView`.
