### ISSUE TITLE
Using UIWebView

### ISSUE THREAD

**Issue by ladaniavadh** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1106]
Hello,
I am using the latest 5.6.8 version of plugin since it showing the reference  of using UIWebView in grep command and that's why my app is getting rejected from IOS.
Any solution how can I solve this error?
![Screenshot 2020-06-27 at 10 30 39 AM](https://user-images.githubusercontent.com/30779077/85972103-9fa48080-b9ec-11ea-9597-8a92f89e8b87.png)

**Comment by EddyVerbruggen** [comment]
It's commented: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/4d7511d7b857f8d5ce00d4b3b1d6e6a0c3949bb0/src/ios/SocialSharing.m#L41

Isn't the problem with other plugins you've grepped?

**Comment by phusting** [comment]
I believe Apple just does a String search on UIWebView and rejects it.  I think that lines needs to be removed completely.
