### ISSUE TITLE
Does this plugin work in Ionic 5

### ISSUE THREAD

**Issue by kennedyngigi4** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1130]
I have tried to use this plugin in Ionic 5 but fails when I do "ionic cordova build android"

What could be the issue??

**Comment by KbaylonH** [comment]
Can you test this fork? https://github.com/KbaylonH/SocialSharing-PhoneGap-Plugin

**Comment by ndang17** [comment]
> Can you test this fork? https://github.com/KbaylonH/SocialSharing-PhoneGap-Plugin

is this working ?

**Comment by KbaylonH** [comment]
> > Can you test this fork? https://github.com/KbaylonH/SocialSharing-PhoneGap-Plugin
> 
> is this working ?

It worked for my case. I had trouble implementing this plugin with google map and admob plugins. I just changed the androidx dependency by v4 support version
