### ISSUE TITLE
An update of screenshots is needed

### ISSUE THREAD

**Issue by Neustradamus** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1151]
Screenshots are very old, it is possible to update the README?
- https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/README.md#2-screenshots

**Comment by EddyVerbruggen** [comment]
Yes, please open a PR with the updates you want and I’ll be happy to merge.

**Comment by Neustradamus** [comment]
Dear @EddyVerbruggen, please do not close a ticket which is not solved.
