### ISSUE TITLE
Issue sharing with iOS 15.1

### ISSUE THREAD

**Issue by trrichmondreglo** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1159]
Hi,

We've just encountered an issue running the Sharing Feature on iOS 15.1.  Is there a report or article that you can share on how to fix this issue?

The app is working absolutely fine on iOS 15.0, just before our tester did the upgrade.

**Comment by bgituser** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
