### ISSUE TITLE
screen frozen after share via facebook

### ISSUE THREAD

**Issue by alextapia007** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1194]
hi.
after share via facebook on ios the screen its frozen. 
![IMG_945E4E6AE135-1](https://user-images.githubusercontent.com/15269078/190231715-cca0e421-a03c-4718-9276-8c5d0ac0f8f2.jpeg)

**Comment by alextapia007** [comment]
after facebook update, work fine.

**Comment by johnpaulcm** [comment]
Any fix except the Facebook app update?
