### ISSUE TITLE
in-correct callback when cancel facebook sharing

### ISSUE THREAD

**Issue by Netpolice** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#140]
.shareVia('com.apple.social.facebook',.....

even the user cancel the sharing, still calling the successful callback. How can I know sharing successfully or cancelled?

**Comment by cankemik** [comment]
any progress about this issue ? is there any other way to get right callback from share popup ?

**Comment by EddyVerbruggen** [comment]
OK, I'm finally smart enough to fix this issue. Please update to 4.3.16 guys.
Canceling the share popup now invokes the error callback correctly on iOS.

**Comment by AcademyLime** [comment]
:+1: However, now we cannot detect if there was an error or was it cancelled. :)

**Comment by ShehramTahir** [comment]
On my side in iOS Promise is working fine but in android it is not working.
It is returning false on success and cancelling
