### ISSUE TITLE
Sharing an animated gif loses the animation

### ISSUE THREAD

**Issue by mrw** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#147]
Hello,

Thanks for your great work on this! I'm using this syntax to share images:

``` javascript
window.plugins.socialsharing.share(null, null, 'http://domain.com/image.gif');
```

`image.gif` is an animated gif. When it shares, such as via SMS, the animation is lost and only the first frame shares. Is there any way around that?

Thanks,
Matt

**Comment by yelban** [comment]
Does this help?

https://stackoverflow.com/questions/37007067/ios-share-gif-animated-image-not-working
