### ISSUE TITLE
Share via Facebook using Messages

### ISSUE THREAD

**Issue by chOse** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#159]
Is it possible to Share via Facebook not in the News Feed but directly via Messages to specific people ?

**Comment by beauby** [comment]
Has the situation changed regarding this?

**Comment by dodomui** [comment]
Tested using @Wumms method on Andoird and it's working fine.
canShareVia('com.facebook.orca', ...)

But cannot make IOS work yet. 
Any suggestion?

**Comment by shawns582** [comment]
Any progress on iOS?
