### ISSUE TITLE
Receive share file from another app

### ISSUE THREAD

**Issue by genuinefafa** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#160]
I'm looking for a two way sharing process. 
- First, share from our app to others (or even social sharing) - which this plugin does very well :)
- Second, receive from another app some share file 

Is there any plugin to **receive** the shared file by using this plugin?

**Comment by slorber** [comment]
Hi

@EddyVerbruggen @genuinefafa @marcsyp I'm currently working on this (we are building a "mobile clipper")
https://github.com/stample/cordova-sharingreceptor

However I must admit it is my first cordova plugin, and I'm not an iOS developer, and I have a really hard time... any help is welcome :) Even a iOS > 8 solution would be nice.


I've tried to add things to CFBundleDocumentTypes but it did not really do what I want. 
See also: http://stackoverflow.com/questions/33105698/sharing-safari-browser-url-to-my-ios-app

As far as I understand, I have to do a  "share extension" (iOS > 8) right?

**Comment by slorber** [comment]
Hi,

I've finally been able to create a clipper.

For Android it is much simpler as a it only requires a Cordova plugin. (I made my [own](https://github.com/stample/cordova-sharingreceptor) and you should probably do your own too as it requires to customize it to your needs). 

For iOS it is much complicated and I've documented it there:
http://stackoverflow.com/questions/26436544/share-image-using-share-extension-in-ios8
