### ISSUE TITLE
cannot read property socialsharing of undefined

### ISSUE THREAD

**Issue by Eigenket** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#166]
I am new to PhoneGap/Eclipse, so please bear with my ignorance (have been building apps with Air for Android/iOS exclusively for the past 3 years)

I have just installed PhoneGap and Eclipse and I am modifying the sample HelloWorld project - successfully created some simple-looking testing apps.

But when I tried to use this plug-in, I've run into this error:
"cannot read property socialsharing of undefined"

I have followed the installation instruction for PhoneGap 3.0 - i.e. just added

```
<gap:plugin name="nl.x-services.plugins.socialsharing" />
```

from 

```
<button onclick="window.plugins.socialsharing.share('Testing Share', null, null, 'http://www.google.com')">Sharing Link</button>
```

to the config.xml in the www folder (cordova.js is already included in the index.html)

This is so frustrating as I cannot get this simple test to work even with such excellent documentation you have.  Can you please shine some light onto it?

Eigen

**Comment by gomathyfollowon** [comment]
i too have same issue..i.e "phonegap-socialsharing-error-cannot-read-property-socialsharing-of-undefined" what is the solution help me to solve the issue

**Comment by EddyVerbruggen** [comment]
@gomathyfollowon there are a few more factors here: have you included a reference to `cordova.js`, do you wait for `deviceready` to fire before using the (any) plugin?

**Comment by gomathyfollowon** [comment]
thanks for your response. yes i referred cordova.js and socialshare.js in my index.html file.

**Comment by gomathyfollowon** [comment]
![image](https://cloud.githubusercontent.com/assets/13587077/9032619/0851a8f4-39de-11e5-811b-2a28f22fb771.png)

**Comment by gfginter** [comment]
I am having similar issue.  On Android I am receiving socialsharing undefined as well.  Have made sure that I have included everything.  Did CLI install then double checked everything.  iOS is working great.  

I am using the $cordovaSocialSharing.share() on a click.  How would I make sure that is wrapped in deviceready when I am setting the click on the ionic tag?

**Comment by gfginter** [comment]
It looks like I was able to get it running...I swear I ran this before, but doing it again and reloading the application on Android worked. 

Refresh the ios.json / android.json file (inside the /plugin folder):

$ cordova platform rm [ios/android]
$ cordova platform add [ios/android]

Update your project to the latest version of Cordova:

This command updates the cordova.js and other Cordova-dependent files to the latest version of Cordova.

$ cordova platform update [ios/android]
