### ISSUE TITLE
iOS: sharing on Facebook with link does not work

### ISSUE THREAD

**Issue by Prinzhorn** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#2]
Well, I can post on Facebook when using sth. like "My text with a link: http://domain.com", but Facebook doesn't fetch the link and does fancy stuff with it (display title and image). Works on Android though.

Is there anything you can change about the way Facebook handles links within text on iOS?

Thanks!

**Comment by developweb10** [comment]
@EddyVerbruggen 
There we can share text using share api please check below line of code & you will be able to share text on FB

FBSDKShareAPI * shareApi = [[FBSDKShareAPI alloc]init];
shareApi.message = @"Share Text";
