### ISSUE TITLE
Share function not working in iOS 7.1

### ISSUE THREAD

**Issue by marcsyp** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#205]
My code works in Android 4.4+ but not in iOS7.1.  ShareVia functions work in iOS but not the generic share function.  Something missing/awry here?

    function share(url) {
          window.plugins.socialsharing.share(null, null, url, '\n\nShared by S, T, L.\nhttp://www.snaptaglove.com', function() {
            var dimensions = {
              username: $scope.currentUser.attributes.username,          
              platform: $scope.currentUser.attributes.devicePlatform,
              device: $scope.currentUser.attributes.deviceModel,
              target: "general"
            }

            // console.log(dimensions);
            Parse.Analytics.track('share', dimensions);
          });
        }

Thanks,
Marc

**Comment by XigenBen** [comment]
+1

**Comment by EddyVerbruggen** [comment]
The arguments are not entirely correct (url is fourth). I should have designed the API better, I know. Please refer to the readme for details.

```
window.plugins.socialsharing.share('Shared by S, T, L.\nhttp://www.snaptaglove.com', null, null, url, function() {} ..
```
