### ISSUE TITLE
Is there a hack to be able to do LinkedIn sharing on iOS?

### ISSUE THREAD

**Issue by Gaviniso** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#208]
Is there a workaround or do we have to wait for Apple to include LinkedIn sharing as per issue #23?

**Comment by garyns** [comment]
+1. Great library. You can certainly share to linked in via a call to .share(), however I'd like to be able to do a shareViaLinkedIn() type call.

**Comment by EddyVerbruggen** [comment]
Apple has included LinkedIn in the sharing targets for iOS but they don't provide a direct sharing option. They do offer this for MacOS (the thing they use in the notification panel on the right), not for iOS unfortunately.

Sharing to LinkedIn on iOS would mean including a lot of LinkedIn-specific framework code and OAuth stuff with API keys etc making usage quite complicated. It would be better to look for a specific Cordova LinkedIn plugin.
