### ISSUE TITLE
Facebook image url issue

### ISSUE THREAD

**Issue by vishnuc156** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#222]
I share location url : "https://maps.googleapis.com/maps/api/staticmap?center=8.893212,76.614140&zoom=13&size=600x300&maptype=roadmap&markers=color:red%7Clabel:S%7C8.893212,76.614140" successfully via google+, Twitter, Gmail.
But it is not crating thumbnail of the same url in Facebook share

**Comment by fmendoza** [comment]
I confirm the issue in Android. The image preview works on WhatApp, Twitter, Google+, Mail, etc, but Facebook is not working. It seems that is a Facebook issue not related to this plugin : (

**Comment by vishnuc156** [comment]
Ok Thanks Fernando..

On Tue, Jan 5, 2016 at 8:37 AM, Fernando Mendoza <notifications@github.com>
wrote:

> I confirm the issue in Android. The image preview works on WhatApp,
> Twitter, Google+, Mail, etc, but Facebook is not working. It seems that is
> a Facebook issue not related to this plugin : (
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/222#issuecomment-168879440>
> .
>



-- 
Thanks and Regards
*Vishnu C*

**Comment by vishnuc156** [comment]
Ok Thanks Fernando..
