### ISSUE TITLE
share not working on iOS8(Solved)

### ISSUE THREAD

**Issue by arnesikstrom** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#230]
I am doing a simple "share" but it doesn't show up in iOS8.1. Running exactly the same code works fine in Android 4.4.4.
When i check the log in Xcode I can see that the plugin is loaded and registered. However when I do "share" the only thing that shows up in the log is this:
Oct 26 16:20:45 Arnes-iPad HelloFrosty[672] <Warning>: **\* WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> **\* -[__NSArrayM insertObject:atIndex:]: object cannot be nil

Any ideas?

**Comment by ils-anshub** [comment]
I am using this plugin for sharing via Facebook and twitter. My only concern is that if we discard the post after calling share function, then why plugin didn't return any value.
Any suggestions ?
