### ISSUE TITLE
Facebook and twitter window open twice in android

### ISSUE THREAD

**Issue by nidhidedania** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#237]
I have used shareViaTwitter and shareViaFacebook for sharing but when i click on button facebook and twitter window open twice in android.
My Code is below : 
window.plugins.socialsharing.shareViaTwitter('title', null /* img */, null, function(msg) {console.log('ok: ' + msg)}, function(msg) {console.log('error: ' + msg)});

Thanks

**Comment by patt0** [comment]
Experiencing a very similar issue with our project, was there a resolution or work around found?

**Comment by EddyVerbruggen** [comment]
@patt0 please share your code with me at eddyverbruggen at gmail and I'll take a look.

**Comment by kingstakh** [comment]
Have this issue to. When click on Share button window opens twice.
Button:
```

      <button class="button" style="border:none;" ng-click="sharePost(post.url)">
        <i class="icon ion-android-share-alt"></i>
      </button>	
```

Controller:
` $scope.sharePost = function( link ){
    window.plugins.socialsharing.share('Check this post here: ', null, null, link);
  }`
