### ISSUE TITLE
Callback after share always return false

### ISSUE THREAD

**Issue by Hurtyto** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#238]
Hello there,
I've tried to implement your plugin in:
Cordova: 3.5.0
Platform: Android 4.4.2 (KitKat)

All the functionalities are wowking ok, but the callback after share is always returning false:

Here is a snippet:

```javascript
service.shareApp = function () {
        return cordova.ready.then(function () {
            var deferred = $q.defer();
            try {
                window.plugins.socialsharing.share(
                'Check out our new Christmas App!',
                'Christmas Card',
                null,
                'http://www.test.io',
                function success(isShared) {
                    alert(isShared);
                    if (isShared) {
                        alert('Share successful!');
                        DataContext.ready.then(function (ctx) {
                            ctx.setSocialIntegrated().then(function () {
                                deferred.resolve(true);
                            });
                        });
                    }
                    else {
                        alert('Share canceled!');
                        deferred.resolve(false);
                    }
                },
                function error() {
                    deferred.reject();
                }
            );
            } catch (e) {
                deferred.reject(e);
            }

            return deferred.promise;
        })
    };
```

I tried to share via Facebook and via Mail and it always returns false.

**Comment by danda1man** [comment]
This is also seen if the action is cancelled.  It would be nice to know if the action happened or was cancelled.

**Comment by mczernin** [comment]
Having the same problem here... is there a workaround or a fix?

**Comment by EddyVerbruggen** [comment]
I wish it was possible to reliably tell whether or not sharing via the 3rd party app worked as expected, but it's not. Check this out: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#notes-about-the-successcallback-you-can-just-ignore-the-callbacks-if-you-like

**Comment by mczernin** [comment]
Yeah, but it happens under iOS at the link it says on iOS it works fine... And also it`s native Facebook sharing that always returns false

**Comment by EddyVerbruggen** [comment]
You didn't mention that :)
I'll leave this open then.

**Comment by mczernin** [comment]
No problem ;) looking forward to a fix

**Comment by EddyVerbruggen** [comment]
@mczernin I just tested `shareViaFacebook` on iOS 8 simulator and it correctly alerted `true` after sharing and `false` after I canceled sharing. Can you give this code a try please?

```
<button onclick="window.plugins.socialsharing.shareViaFacebook('hi', ['https://www.google.nl/images/srpr/logo4w.png', 'http://tweakimg.net/g/if/v3/framework/logo_transparent.png'], null, function(result) {alert('result: ' + result)}, function(errormsg) {alert(errormsg)})">msg, 2 imgs, via Fb /w cb</button>
```

Also, I get the exact same (correct) result with the `share` function:

```
<button onclick="window.plugins.socialsharing.share('Message', null, null, null, function(msg) {alert('ok: ' + msg)}, function(msg) {alert('nok: ' + msg)})">message via *</button>
```

**Comment by cjaikarthik** [comment]
I am also using this plugin and its working perfectly for iOS as you posted above. 

But for Android, i am facing some issues
          i cannot able to share text with image or even text only
          It's returning "false" even after successful share.

Please provide your suggestion.

**Comment by EddyVerbruggen** [comment]
@cjaikarthik to which app are you sharing your text?

**Comment by cjaikarthik** [comment]
Sharing to Facebook app

**Comment by EddyVerbruggen** [comment]
Please see the readme - sharing text to Fb on Android is a no-go. Note that there is a workaround in the readme.

**Comment by cjaikarthik** [comment]
Ok i will try that workaround.
But for the return response, can you give me any suggestion?
It's always showing false even after successful share.

**Comment by EddyVerbruggen** [comment]
Please see my comment of Jan 9th above.

**Comment by cjaikarthik** [comment]
So it's not possible to get proper response.

I am asking this because i am adding some data to db after successful share only. so i am keep getting false even after successful share and can't able add that data.

It would really helpful if you suggest any other option to do this.

**Comment by EddyVerbruggen** [comment]
I can stand on my head for a while but that won't fix Fb's crappy sharing integration on Android. If it did I would  gladly do it for you.

**Comment by cjaikarthik** [comment]
Thanks @EddyVerbruggen , I am looking forward to it.

**Comment by ilvalerione** [comment]
Hello, I'm having the same problem in Android app. After saccessful share callback function get "false".

Is there workaround to solve this issue?

**Comment by PAnvesh** [comment]
Hi, I'm also facing same problem in Android . Even if I cancel/POST the sharing it is invoking success callback and returning "false". 

Can someone give me suggestion to handle the callback?

**Comment by JeremyColton** [comment]
IOS 9+ works perfectly. I updated the SocialSharing.m line 98 to even return the name of the sharing app that was used as follows:

98. CDVPluginResult * pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsBool:completed];

changed to:

98. CDVPluginResult * pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:activityType];

But, on Android, I always get false and no matter what the user does.  The Java can be updated from Android 5.1 to return the app's intent that was used according to http://stackoverflow.com/questions/24561855/get-chosen-app-from-intent-createchooser

But the world still has 35% of users at Android 4.4.  So, meanwhile having a reliable true/false would be great.  Has anyone found a way to achieve this?

**Comment by marysgonzalez** [comment]
I am having the same issue, but also I can't share any image from my server, but if I use any random picture from the Internet, it is been shared successfully. When I access the image from the server in the browser it returns just fine.

**Comment by abhishekthakur1995** [comment]
suppose I share something on a particular app using the cordova native share sheet and I want to know which app was used for sharing. So is there any way to get the name of the app which is used to share the content on android devices.
