### ISSUE TITLE
Sharing image with spaces in filename.

### ISSUE THREAD

**Issue by jharbertdev** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#241]
I have successfully got the Android Intents to work.  However when the image has spaces in it the app will not load the image.  I am using the following:

< img onclick="window.plugins.socialsharing.share('#priproductions', null, 'http://priproductions.com/eventphotography/sites/default/files/styles/juicebox_medium/public/field/image/Georgia Florida 2014-001.jpg', null)" src="http://priproductions.com/eventphotography/sites/default/files/styles/juicebox_medium/public/field/image/Georgia Florida 2014-001.jpg" />

I have attempted to replace the spaces with %20 and + but neither is working.

Problem is I have over 5000 images uploaded in my drupal site that have spaces in the filename.

**Comment by thatsmekaustubh** [comment]
problem persists! also on 2G/3G networks
