### ISSUE TITLE
Facebook Sharing on Android - no URL or Image (or Message)

### ISSUE THREAD

**Issue by rajatrocks** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#253]
On Android 4.4 I've tried sharing to Facebook via .share, .shareViaFacebook, and . shareViaFacebookWithPasteMessageHint - with no image and a url. My url never gets added. Maybe this has something to do with the splitting out of Messenger functionality? 

On iOS this works fine.

**Comment by replysam2009** [comment]
@EddyVerbruggen Hi, I am using Social Sharing plugin in one of my Ionic2 projects. Earlier evrything was working fine but from past 3 days I am not being able to share anything using shareViaWhatsApp() function. Whenever I try to share anything it says: "Attempt to invoke virtual method 'android.content.res.XmlResourceParserandroid.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference."
Is there anything you can help me with?

**Comment by gianpaj** [comment]
Do we know why this happens only on Android? Is the Android Facebook or Messenger App doing something after a cordova/ionic sends the correct URL, but not on iOS?
Or can we update some native SDK/code inside this plugin, that could allow for this?

**Comment by marceviana** [comment]
I can´t share anything via facebook. The facebook app will crash before opening completely if I use **window.plugins.socialsharing.shareViaFacebook** 
```

                    window.plugins.socialsharing.shareViaFacebook(null, [fileURL], null, 
                        function successShare(s) {
                            console.log('share ok')
                        }, function errorShare(errormsg){
                            console.log('Error in: shareViaFacebook >> msg:')
                            console.log(errormsg)
                        })
```
The only function currently working that won't make fb to crash is **window.plugins.socialsharing.shareVia('facebook', null, [fileURL])** but then the sharing activity is shown but won't load the file. I've tried both with a local file (file:/...) and a web hosted one, and also video files. All the other apps work as expected (whatsapp, gmail, drive, etc) both with image and video. Any ideas what might be happening? 

I'm using version 5.2.1 of the plugin for android:minSdkVersion="14" and android:targetSdkVersion="26"

**Comment by mfdeveloper** [comment]
@replysam2009 See my comment  https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/774#issuecomment-369211159 into your issue about `loadXmlMetada()` error.

**Comment by kierangillen** [comment]
It seems that .edu also doesn't work?

**Comment by abdullahMYMA** [comment]
this.socialSharing.shareViaFacebook(text, url).then(data =>
