### ISSUE TITLE
iOS sms sharing hides when sharing an image 

### ISSUE THREAD

**Issue by stackdevdev14** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#254]
when trying to share via sms on iOS using png photo, the dialogue closes immediately and logs an error of "ok:false"

**Comment by stackdevdev14** [comment]
Any update regarding this issue? Would love to be bike to share an image via sms only

**Comment by stackdevdev14** [comment]
*able

**Comment by EddyVerbruggen** [comment]
Hi,

I've just tested this again on my iPhone 6 (iOS 8):

```html
<button onclick="window.plugins.socialsharing.shareViaSMS({'subject':null,'image':'https://www.google.nl/images/srpr/logo4w.png'}, '0650298958', function(msg) {alert('ok: ' + msg)}, function(msg) {alert('nok: ' + msg)})">share null,null,img via SMS /w nr</button>
```

It works flawlessly. Can you post your exact code please?

If it already is exactly the same, check your 'MMS' setting in the iPhone settings > Messages.

**Comment by stackdevdev14** [comment]
I just used the exact code you provided and and the sms sheet pops up only to immediately hide and provide the alert of "ok:false". I have mms on and I too am using an iPhone 6 on iOS 8

**Comment by stackdevdev14** [comment]
Hey Eddy, 
Figured it out. I simply needed to update my config.xml for phone gap build. Thank you so much for your help and it works as you said; flawlessly.
