### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by delbyStudio** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#255]
Add iOS 8 support for SocialSharing plugin because when i execute it i can share only with mail app but not with Whatsapp or Facebook

**Comment by fredevery** [comment]
I have google hangouts and whatsapp installed in iOS 8 but am not seeing them in the sharesheet?

**Comment by socialraving** [comment]
Looks the same at our app:

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/307

**Comment by EddyVerbruggen** [comment]
Hangouts and WhatsApp don't have an iOS 8 extension yet. You can use the `shareViaWhatsApp` and the few other `shareVia...` functions in the meanwhile.

**Comment by EddyVerbruggen** [comment]
WhatsApp finally has an iOS share extension. Woohoo!
