### ISSUE TITLE
Sharing an image AND text to whatsapp under iOS

### ISSUE THREAD

**Issue by ptrumpis** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#256]
Sharing both, image and text to whatsapp is working under Android but it is not working under iOS.
Under iOS only the image is getting shared while under Android both is getting shared.

I came accross this: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/188
So is this a plugin issue or is it the way whatsapp behaves under iOS?

If it is not a plugin issue, then you might should add this information to "iOS Quirks".
So other users don't get confussed

**Comment by petergoes** [comment]
Hi there, is there any news regarding this issue?
I agree with @ptrumpis that if this is not a plugin issue, it should be mentioned under iOS Quirks

Regards

**Comment by EddyVerbruggen** [comment]
Good point guys - update the doc @ `shareViaWhatsApp`. It's a limitation of WA on iOS unfortunately.
