### ISSUE TITLE
Sharing to twitter : message text empty

### ISSUE THREAD

**Issue by sreejith-m-sreedharan1987** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#265]
Hi,
 when i try to share message through twitter, i can see the popup but the message i passed to it is missing. I can see the image attached and the link provided in the twitter share popup. This issue occurs in iOS 6 devices, it is working perfectly in iOS 7. All other share options - facebook,mail,sms are working fine. Problem is with twitter only. The exact version of the device in which the problem was found - 6.1.3 and 6.1.2.

Please help me to resolve the issue at the earliest.

**Comment by sktniranjan** [comment]
Hi Sreejith,
        I am also facing the same problem. I need to limit the message length to 140 only for Twitter. Do you have any workaround for this issue?

Thanks,

**Comment by EddyVerbruggen** [comment]
Hi, it's not possible to use `share` with multiple message contents as the plugin can't know which app the user picks to share with.

For this you should use the `shareViaTwitter` etc methods.
