### ISSUE TITLE
Error sharing Via Facebook

### ISSUE THREAD

**Issue by Chouniou** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#267]
Hi everyone, I'm trying to solve an issue that I have notice in my cordova project. When I try to share something via facebook I get an alert error message and the app never goes to facebook. I have test sharing via twitter and it works fine.
My cordova version is 4.0.0 and I'm using Motorola Moto G for tests.
This is the error that I recieve:
![screenshot](https://cloud.githubusercontent.com/assets/10278540/5536057/2995b738-8a8b-11e4-9d0e-ce845e53deb5.jpg)
thanks in advance.

**Comment by cmardegan** [comment]
Hi I see your message "This alert is simply a callback of the shareViaFacebook method you're alerting. You could console.log it or ignore it, but that list shows which packages you actually have installed on your device." how can I change the text alert?

Thanks

**Comment by EddyVerbruggen** [comment]
@cmardegan I'm assuming you're passing in an error function to the plugin (the last parameter of any of this plugins functions). Simply change the content of your error function to something like:
```js
function(msg) {
  alert("Sharing failed, oops!");
  // or log it to the console:
  console.log("Error message from SocialSharing plugin: " + msg);
}
```

Hope I understood your question correctly.
