### ISSUE TITLE
In ios share doesn't work

### ISSUE THREAD

**Issue by borhademohini** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#271]
I am using following code to implement share app functionality.

window.plugins.socialsharing.share('Check out App name', null, null, 'Google - https://play.google.com/store/apps/details?id=app-id Apple - https://itunes.apple.com/us/app/app-name/idapp-id');

It is working in android. But not in IOS.

Please help me to solve this.

**Comment by BMSTUDIO** [comment]
Same

**Comment by EddyVerbruggen** [comment]
@borhademohini so you're doing this on iOS? `window.plugins.socialsharing.share('Check out App name', null, null, 'https://itunes.apple.com/us/app/app-name/idapp-id');`
What exactly happens when you try that?

@BMSTUDIO a bit more details would be appreciated.

**Comment by BMSTUDIO** [comment]
IOS on the buttons do not work. Nothing happens .
The application is emulated in Cordova CLI and on the device is the same.

I followed the procedure "Automatically ".
(https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/tree/f5ac146f5bfb2bb940b026350c47a8b28ea11eb0)

**Comment by EddyVerbruggen** [comment]
@BMSTUDIO Can you share you project with me?

**Comment by BMSTUDIO** [comment]
What should I send you ? Thk


2015-01-22 23:26 GMT+01:00 Eddy Verbruggen <notifications@github.com>:

> @BMSTUDIO <https://github.com/BMSTUDIO> Can you share you project with me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/271#issuecomment-71111977>
> .
>



-- 
*Benoît Mislin*
*BM-STUDIO | Développeur & Intégrateur Web / **Web-designer*
*----------------------------------------------------------------------------------------------*
http://bm-studio.fr
Mobile : 06 59 55 79 64
Fixe : 04 84 26 34 03

**Comment by EddyVerbruggen** [comment]
As much as possible. An XCode project perhaps. Anything I need to reproduce your problem.

**Comment by BMSTUDIO** [comment]
A bitbucket is ok for you ?

Can you give me your email that I will share the project?


2015-01-22 23:31 GMT+01:00 Eddy Verbruggen <notifications@github.com>:

> As much as possible. An XCode project perhaps. Anything I need to
> reproduce your problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/271#issuecomment-71112684>
> .
>



-- 
*Benoît Mislin*
*BM-STUDIO | Développeur & Intégrateur Web / **Web-designer*
*----------------------------------------------------------------------------------------------*
http://bm-studio.fr
Mobile : 06 59 55 79 64
Fixe : 04 84 26 34 03

**Comment by EddyVerbruggen** [comment]
Sure thing, bb is fine. Mail me at eddyverbruggen at gmail, thanks!

**Comment by jasonlacarl** [comment]
running into the same issue on an ipod touch with 8.1.2.  i have imessage and twitter configured on the device and nothing happens when i hit the "share" button in my app. it works beautifully in WP8.1 and Android using this: window.plugins.socialsharing.share(mesg, null, null, null);

any help is appreciated.

**Comment by MyBoon** [comment]
Same problem for me. Was working fine till last week.

**Comment by EddyVerbruggen** [comment]
What changed last week?

**Comment by MyBoon** [comment]
Except upgrading to cordova 4.2.0 ... nothing

**Comment by EddyVerbruggen** [comment]
Can you share your project with me perhaps?

**Comment by bradleyflood** [comment]
+1

**Comment by EddyVerbruggen** [comment]
@bradleyflood +1 what exactly?
Please share your project with me if you have a specific problem.

**Comment by bradleyflood** [comment]
@EddyVerbruggen Turns out I didn't have the `cordova.js` file included. This isn't clear from the Cordova docs. Thank you
