### ISSUE TITLE
canShareViaEmail on iPad

### ISSUE THREAD

**Issue by FabioKB** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#273]
Hi there, I love your plugin, it's amazing...

window.plugins.socialsharing.canShareViaEmail(... returns False on my iPad2 iOS 7.1.2 device. It's flawless on Android.

Why is this? Is there something I'm missing?

Thanks!

**Comment by EddyVerbruggen** [comment]
Thanks, and sorry it took me a while. A long while even.

The `canShareViaEmail` function will return true if the native iOS emailclient has been properly configured to send email. At least that's what the iOS documentation (of the function I'm using) tells me.

If you have any concern please post the javascript code here as well.
