### ISSUE TITLE
[Intel XDK] window.plugins === undefined

### ISSUE THREAD

**Issue by wll** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#274]
I use the plugins by this step
1、cordova plugin add xxxx
2、cordova prepare

but call window.plugins.socialsharing.share, I got the error: TypeError: Cannot read property 'socialsharing' of undefined

**Comment by EddyVerbruggen** [comment]
Did you include cordova.js in your index.html?

**Comment by qnimate** [comment]
yes I included it but it still doesn't work......

**Comment by EddyVerbruggen** [comment]
Can you share more of your code with me perhaps?

**Comment by qnimate** [comment]
Well I am using this plugin in Intel XDK. Imported the plugin from web with proper id and git url. I am testing it in iOS adhoc build not its not working. windows.plugins is still undefined.

**Comment by EddyVerbruggen** [comment]
I have never used Intel XDK, so no idea what's wrong, perhaps watchers using XDK can help? Otherwise, I'm sure there must be similar Cordova plugin installation questions on the XDK fora.

**Comment by qnimate** [comment]
thanks

**Comment by wll** [comment]
》》》》Did you include cordova.js in your index.html?

yes， you are right,I missing the cordova.js in my index.html
it works now。thinks

**Comment by Dfault-Games** [comment]
I have included cordova.js but still i am getting the same error. moreover i typed window.plugins in console and it says undefined. Can anyone [please tell me how to resolve this?

**Comment by wog890** [comment]
Likewise, I have included cordova.js, but getting this error. Has anyone figured out a fix?

**Comment by TechGuyVN** [comment]
I Have the same error like you, turn out everything ok when run in simulator or device. Plugin not work in web browser.

**Comment by MHaendel** [comment]
Same, its referenced in the cordova_plugins.js th. `"cordova-plugin-x-socialsharing": "5.0.12-dev"`
