### ISSUE TITLE
what is the latest new about plugin 4.3.12

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#276]
hi @EddyVerbruggen 
I saw in cordova.io have a new version 4.3.12
http://plugins.cordova.io/#/package/nl.x-services.plugins.socialsharing

but in this page only update to 4.3.8
http://plugins.telerik.com/plugin/socialsharing

so...is there any difference or update information ?

**Comment by EddyVerbruggen** [comment]
Please don't create issues for questions like this. It's nothing major, just a few bugfixes.

**Comment by bau720123** [comment]
OK
sorry for @EddyVerbruggen 
I'll pay more attention
