### ISSUE TITLE
shareViaSMS() empty message content

### ISSUE THREAD

**Issue by dmonllao** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#277]
I'm using a Nexus 5 (Android 5.0.1) I share via SMS specifying the phone numbers and the message text, only the phone numbers passes to hangout once started.

In README.md I read "SMS (note that on Android, SMS via Hangouts may not behave correctly)" any work around?

**Comment by dmonllao** [comment]
All solved using last hangouts version (2.5.83281670) Feel free to close the issue if you conclude that it was just a hangouts problem.

**Comment by EddyVerbruggen** [comment]
Thanks!
