### ISSUE TITLE
Facebook Sharing : text not shown in sharing page, hint is displayed as null

### ISSUE THREAD

**Issue by sreejith-m-sreedharan1987** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#279]
Text is missing in the facebook sharing page. I have used your work around function , shareViaFacebookWithPasteMessageHint , and now i can paste the text manually, but i get a 'null' toast instead of that paste info. Please fix it at the earliest.

**Comment by EddyVerbruggen** [comment]
Hi, what's the exact code you're using, and on which devices have you tested this (please include the Android versions). Thx.

**Comment by sreejith-m-sreedharan1987** [comment]
I am tetsing it in android 5.0, 

window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint('message', null, 'http:\\sampleurl.com', function() {},function(){});

Thanks for that quick response :)

**Comment by EddyVerbruggen** [comment]
Well, then it's null because you didn't pass any paste hint. Look at this code I found in the readme:

```
<button onclick="window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint('Message via Facebook', null /* img */, null /* url */, 'Paste it dude!', function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">msg via Facebook (with errcallback)</button>
```

**Comment by sreejith-m-sreedharan1987** [comment]
Sorry, I thought it was pre-configured in the plugin.

Thanks Eddy
