### ISSUE TITLE
Copy to clipboard?

### ISSUE THREAD

**Issue by aboudeh87** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#282]
How i can copy directly to clipboard ?

**Comment by EddyVerbruggen** [comment]
What do you want to copy?

**Comment by aboudeh87** [comment]
I want to copy a text but direct to clipboard

**Comment by EddyVerbruggen** [comment]
This is not a clipboard-specif plugin. There are others which are..

**Comment by aboudeh87** [comment]
thanks a lot

**Comment by Donald3d** [comment]
I t would be nice to be able to copy directly to clipboard,I really need that feature in my app

**Comment by Dineshrajaa** [comment]
https://github.com/VersoSolutions/CordovaClipboard
try this plugin @Donald3d
