### ISSUE TITLE
Twitter cannot post message without displaying the popup dialog

### ISSUE THREAD

**Issue by chalzteddi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#284]
Can you provide with options to post to twitter without opening the popup dialog? We do not want the users to modify the message before posting it to Twitter.

**Comment by EddyVerbruggen** [comment]
If that's your requirement then this is not the plugin to use. This one taps in to the native share features which do not support Tweeting without the user pressing the button himself.
