### ISSUE TITLE
IOS No Mail Accounts

### ISSUE THREAD

**Issue by nidhidedania** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#288]
On startup alert comes 'No Mail Accounts' in ios how can we disable this?

**Comment by EddyVerbruggen** [comment]
Which plugin version are you on?

**Comment by nidhidedania** [comment]
4.3.7

**Comment by EddyVerbruggen** [comment]
[Check this](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/releases/tag/4.3.8) (was fixed in 4.3.8)

**Comment by nidhidedania** [comment]
i have upgrade to 4.3.13 still issue is there
