### ISSUE TITLE
Localization on iOS

### ISSUE THREAD

**Issue by ASGAlex** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#289]
On ios devices with non-english system language sharing popup still use english captions ("Cancel" button). Whereas on android devices everything is ok. In both cases locale of phonegap browser matches to selected language (ru_RU on Android, ru-ru on ios). Screenshots:

Android 4.2.1:
![screenshot_2015-01-27-16-44-05](https://cloud.githubusercontent.com/assets/1258285/5919468/25791070-a645-11e4-99b2-ee9d1b478258.png)

IOS 7:
![img_0137](https://cloud.githubusercontent.com/assets/1258285/5919491/52e81cd6-a645-11e4-90e6-454b6d3186fd.PNG)

**Comment by EddyVerbruggen** [comment]
To my knowledge this is not something this plugin can fix. Please Google a bit and let me know here if it is, but my initials tests on iOS 8 didn't show any change.

**Comment by poornerd** [comment]
so @EddyVerbruggen what is the solution to getting the iOS language dialogs?  My Phone is set to German, but I still get the dialogs in English.

**Comment by Luehrsen** [comment]
I also have this issue. Phone is in german language mode, but the sharing dialog remains in english. Can you reproduce this?

**Comment by Luehrsen** [comment]
Yeah, I figured it out. We are localizing the Cordova Webview, but not the actual app.

@poornerd Try adding German to the app languages in the info.plist of the app. Without that the iphone doesn't know that the app is actually capable of displaying German strings. :)

**Comment by poornerd** [comment]
Thanks @Luehrsen will try that

**Comment by chmac** [comment]
@poornerd Did that work for you? We're looking at the same issue.

**Comment by gfringeli** [comment]
@Luehrsen 's solution is working.
Add German to your apps info.plist.
