### ISSUE TITLE
Callback when sharesheet is shown.

### ISSUE THREAD

**Issue by leouze** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#293]
Hi EddyVerbruggen,
The plugin is great! I love it.

But I have some question, is there any callback when sharesheet is shown?
Currently I am sharing an image fetched from a remote location/server, and I've noticed that there is a delay between invoking the share command and the moment the sharesheet is shown.

I wanted to add loading mask between these events to inform the user that something is happening in the background.

Thanks and Good day.

**Comment by EddyVerbruggen** [comment]
Hi,

Nope, the plugin doesn't let you know when the app of your choice shows up.

Note that the delay is because the image needs to be downloaded to your device before it can be shared. So you may want to download it first and share it from your local filesystem.

Best,
Eddy
