### ISSUE TITLE
Delay after click on any of the social icon(Android)

### ISSUE THREAD

**Issue by 05bca054** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#294]
Hello Eddy,

First of all let me thank you for awesome piece of work.

I'm working on Cordova, JQM application using fastclick.js but when i click on link for sharing,twitter and whatsapp content it takes measurable amount of time to open or launch application!

Is there any patch for that?

Please find code below and feel free to ask for more information if needed.

$(".nearby-facebook-share").attr("onclick","window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint('Use Coupon code : xyz And get  15% discount atnice n new Locate merchant using this link: https://www.google.com/maps/@23,72,18z', www.google.com/logo.jpg', null, 'Please paste message from clipboard!', function() {}, function(errormsg){alert(errormsg)})");

Thanks for your time and consideration in advance.

-Niks

**Comment by EddyVerbruggen** [comment]
Hi, good question. Replacing that image by null should be a lot quicker. Let me know if that helps.

Cheers,
Eddy

**Comment by 05bca054** [comment]
Yes still take take measurable amount of time!

**Comment by EddyVerbruggen** [comment]
There is no way for the app to know when facebook is started on your device. Perhaps you can just [show a spinner](http://plugins.telerik.com/plugin/spinner) for a few fixed seconds?

**Comment by 05bca054** [comment]
Ok ,thanks Eddy...
