### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by loranbriggs** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#3]
Hey great plugin, works well on Android. But I cant seem to get it to work on iOS. Am I missing something?

```
var message = 'the message';
var subject = 'the subject';
var image = 'https:image.url';
var link = 'http://www.somesite.com';

window.plugins.socialsharing.share( message, subject, image, link);
```

I am using iOS7, could that be it?

**Comment by wiadev** [comment]
@EddyVerbruggen I'm checking on iOS 10 and got [CDVCommandQueue executePending] error.

any suggestions?
