### ISSUE TITLE
shareViaTwitter : link automatically shortened not work

### ISSUE THREAD

**Issue by zckrs** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#302]
```
$scope.shareTwitter = function () {
      $cordovaSocialSharing.shareViaTwitter(content.title, null, content.url).then(function (result) {
        // Success
      }, function (err) {
        // An error occurred. Show a message to the user
      });
    };
```

On Android, tweet contain full url not shortened.

**Comment by EddyVerbruggen** [comment]
The plugin has no built-in shortener or anything.. that's up to the Twitter app. But did your total message fit the 140 chars?

**Comment by zckrs** [comment]
[In README plugin](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#4a-usage-on-ios-and-android)
> Twitter: message, image (other filetypes are not supported), link (which is automatically shortened).

I'm confuse with that. Lenght of message is lower that 140 character

**Comment by EddyVerbruggen** [comment]
Ah, that makes sense. I've updated the readme - it now indicates this is optionally done by the Twitter client, not something the plugin does.
