### ISSUE TITLE
ShareViaTwitter is done with call to hardcoded app name

### ISSUE THREAD

**Issue by mattheworres** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#306]
So I found this out the hard way, as I am an Android user I was testing the use of this plugin on Android, and shareViaTwitter was not working - the error handler was returning with "false" as the error data, and I had no clue. I was making the calls correctly, doing so in a deviceready event handler, and using ngCordova to call $cordovaSocialSharing - and yet the error handler would continually be called.

The issue is that in SocialShare.java the only way to pop up the tweet box is to call a hard-coded app name "twitter" (the same way 'com.katana.facebook' is called) - which caused an issue for me particularly.

This is probably an edge case (not only because it's Android, but a subset of Android users), but do you have any plans to support an optional parameter to "shareViaTwitter" to allow a third party app name to be passed in to the execute function?

I've considered hacking at this myself, but I'd have a little bit of spinup time since I've never worked in Java/Android directly before.

**Comment by EddyVerbruggen** [comment]
Have you tried the `shareVia` function?

**Comment by mattheworres** [comment]
Oh, nice! Didn't realize that was a thing. Perfect!
