### ISSUE TITLE
link is not opional

### ISSUE THREAD

**Issue by softBarbarian** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#309]
It seems if you pass an empty string as a `link` parameter to `shareVia` on Android 5.0.0 the plugin throws `URL_NOT_SUPPORTED` error.

Can someone confirm this issue?

**Comment by EddyVerbruggen** [comment]
I can't confirm it. Tested it just now on Android 5. Also, the code explicitly checks for empty and null strings.

Make sure you're using the 5th param for URL when using the `shareVia` function.
