### ISSUE TITLE
no sharing options on a Nexus 7 with Android 4.4.4

### ISSUE THREAD

**Issue by Pomax** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#310]
I'm calling the socialsharing plugin as follows on a Nexus 7 with Android 4.4.4,
```
if (window.plugins && window.plugins.socialsharing) {
    console.log("calling socialsharing plugin")
    window.plugins.socialsharing.share(msg, null, null, url, shareSuccess);
}
```

and looking at the console log through adb, this code is reached. However, the `window.plugins.socialsharing.share` call does not seem to pull up any share apps that might be useful, despite having the gmail and twitter apps installed as potential email and twitter clients, respectively.

The Nexus 7 does not have phone capabilities, would that cause the socialsharing plugin to ignore any of the other potential (non-sms, non-phone) options?

**Comment by EddyVerbruggen** [comment]
I have a 2012 model Nexus 7 with Kitkat which works fine. I also have one with Lollipop which also works fine.

Can you test it like this please?

```
<button onclick="window.plugins.socialsharing.share('Message only')">message only</button>
```

**Comment by Pomax** [comment]
yeah that seems to work correctly. I'll hunt on for why things break deeper in our code. thanks!
