### ISSUE TITLE
Attachment base64 image 

### ISSUE THREAD

**Issue by derozgurg** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#311]
Hi, if more than one image as base64 in an array want to be shared through email there only one attachment file is showed in received mail.
And all attachment files created in the same name for each other

**Comment by EddyVerbruggen** [comment]
Hi, are you refering to `shareViaEmail` on Android?

**Comment by derozgurg** [comment]
Yes, i meant exactly that here is i fixed it on my code 

SocialSharing.java :318
String fileName = "file"+nthFile+"." + imgExtension;

**Comment by EddyVerbruggen** [comment]
Hi, nicely found, please try the 4.3.15 version which works per your suggestion.
