### ISSUE TITLE
Angular {{ }} not working

### ISSUE THREAD

**Issue by andregeges** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#312]
```
<button
style="background:none;border:none" 
onclick="window.plugins.socialsharing.shareViaTwitter('Hi checkout this item', null /* img */, 'http://www.example.com/item/{{ vm.product.idt }}')">
<img src="img/twitter-share.png" style="width:150px"/>
</button>
```

this twitter share button does'n recognize {{ }} my variable.. 
i hope with this code i can got link like www.example.com/item/1

**Comment by andregeges** [comment]
i tried to change onclick to data-ng-click and my variable is coming up, but my button not working.. my share button only working if i used onclick

**Comment by EddyVerbruggen** [comment]
This is a JS issue, not a plugin issue.
