### ISSUE TITLE
shareVia is limited in iOS

### ISSUE THREAD

**Issue by dimanchee** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#313]
Hi EddyVerbruggen,
I have noticed in this section says:

- iOS: You are limited to 'com.apple.social.[facebook | twitter | sinaweibo | tencentweibo]'. If an app does not exist, the errorcallback is invoked and iOS shows a popup message asking the user to configure the app.

Does it mean that shareVia is only working with facebook, twitter, sinaweibo & tencentweibo? Because I am trying to use shareVia for "LINE app", but it seems nothing happen even errorcallback.

Here my code:
window.plugins.socialsharing.shareVia('com.apple.social.line', 'Message via LINE', null, null, null, function(){alert('share ok')}, function(msg) {alert('error: ' + msg)})

**Comment by EddyVerbruggen** [comment]
That's right, shareVia is limited to those options.
