### ISSUE TITLE
Share Video on Whatsapp ERROR

### ISSUE THREAD

**Issue by CostanzoPablo** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#315]
When I share a video on whatsapp, whatsapp says the file is not of type IMAGE. If I select share by e-mail or other destination, share it correctly.

The same file, if I share it with any program as "ES File Explorer" from android gallery or using the native operating system, WhatsApp is shared smoothly.

code:
 window.plugins.socialsharing.share('Here is your Video', 'Your Video', 'file://mnt/sdcard/1/2.mp4');

**Comment by CostanzoPablo** [comment]
Editing SocialSharing.java .... 
  private Uri getFileUriAndSetType(Intent sendIntent, String dir, String image, String subject, int nthFile) throws IOException {
    // we're assuming an image, but this can be any filetype you like
    String localImage = image;
    sendIntent.setType("video/*");
    return Uri.parse(localImage);
  }

But not changes...

**Comment by CostanzoPablo** [comment]
Only i edit /platforms/android/src/mobi/roshka/cordova/shareplugin/SharePlugin.java

Line 61:
sendIntent.setType("video/*");

Line 66:
String[] mime = {"video/*"};

Now works for Share the videos on WhatsApp ! :)

**Comment by krakostzakos** [comment]
Hi Pablo,

thanks for your effort and sharing your fix. Is there a way to get your compiled version with that fix? Because #165 is still open.

Thanks.

**Comment by EddyVerbruggen** [comment]
@krakostzakos I'd love to merge a backward compatible cross-platform fix for this issue. If anyone can point me to a fork or PR then I'd be happy to do it.
