### ISSUE TITLE
Not working in 3.8.0

### ISSUE THREAD

**Issue by MateenKadwaikar** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#317]
'toSuccessCallbackString:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate method sendPluginResult:callbackId instead. This will be removed in 4.0.0

**Comment by EddyVerbruggen** [comment]
That deprecation warning should not affect the plugin as it will be removed in 4.0.0 while you're at 3.8.0. So please elaborate a bit on how you're trying to use the plugin and I may be able to help you.

**Comment by MateenKadwaikar** [comment]
Thank you .

I tired building new application and installing your app.

The plugin is working .

-Best Regards
Mateen Kadwaikar
