### ISSUE TITLE
Cannot build the IOS app

### ISSUE THREAD

**Issue by BalticDistribution** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#319]
Hi,
after installing th eplugin I cannot build my project and get:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_SLServiceTypeFacebook", referenced from:
      -[SocialSharing shareViaFacebook:] in SocialSharing.o
      -[SocialSharing shareViaFacebookWithPasteMessageHint:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeSinaWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeTencentWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeTwitter", referenced from:
      -[SocialSharing shareViaTwitter:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
ld: symbol(s) not found for architecture i386

Regards,
Tomasz

**Comment by EddyVerbruggen** [comment]
Hi, unfortunately sometimes for iOS the frameworks fall off. You'll need to add the `Social.framework` and `MessageUI.framework` to your project. In XCode click your project, Build Phases, Link Binary With Libraries, search for and add Social.framework and MessageUI.framework.

**Comment by BalticDistribution** [comment]
Hi,thanks for the rapid reply. Works perfectly!
Great project!
Regards,
Tomasz

**Comment by BalticDistribution** [comment]
Eddy,
once again thank you for the solution. One more thing that would be great and I could even help you with it: on Android the base64 pics don’t work :/
regards,
Karol

**Comment by EddyVerbruggen** [comment]
Hi Karol,

Can you show me your code to try sharing base64 pics? And of course if you can fix it I'd be very happy!
