### ISSUE TITLE
Multiple share

### ISSUE THREAD

**Issue by DaveInfinity** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#320]
I am using method Sharing via Facebook to multiple photos at a time, by using array. 
If array contains more than 10 images say 25, it share only 10 images out of that 25 images.
Not allow to share more than 10 images.

Pl reply as soon as possible.
AnyOne.

**Comment by EddyVerbruggen** [comment]
That must be a limitation of the Fb app. I've read Tumblr has a similar limit so that may be it. It's not something the plugin enforces.

**Comment by DaveInfinity** [comment]
Thank you very much, for suggestion.
