### ISSUE TITLE
Crashes Android 5.0.2 application on Cordova 4.3.0 with Ionic

### ISSUE THREAD

**Issue by Kurtz1993** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#323]
Only by adding the plugin it makes my app crash on Android.
I'm using Cordova 4.3.0 with the Ionic Framework and when I run

    cordova run android --device

the app just show an alert that it has crashed.

**Comment by EddyVerbruggen** [comment]
Can you share your code with me perhaps?

**Comment by Kurtz1993** [comment]
I only did a fresh install of ionic and then added the plugin and platform, after that I ran the app on the device and crashed. Didn't add code at all, yet.
____________________
Luis Rogelio Hernández López
GitHub: @Kurtz1993
Sent using CloudMagic
On Mon, Mar 23, 2015 at 10:28 am, Eddy Verbruggen <notifications@github.com> wrote:Can you share your code with me perhaps?

**Comment by jpgarcia** [comment]
Any update on this? A user with 5.0.2 just reported us crashes after upgrading to 5.0.2

**Comment by RienMoeyaert** [comment]
Any word on this yet? Still an ongoing issue?

**Comment by EddyVerbruggen** [comment]
Perhaps it's the same issue as #365 which I fixed a few days ago?
