### ISSUE TITLE
View not in window hierarchy (inappbrowser)

### ISSUE THREAD

**Issue by Riesling11** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#324]
Unfortunately running window.plugins.socialsharing.share(...); produces the following error in my app when the inappbrowser is visible:

> Warning: Attempt to present UIActivityViewController: 0x13f6a0f30 on MainViewController: 0x13f60c850 whose view is not in the window hierarchy!

I am using cordova 4.3.0, ios 3.8.0 and socialSharing 4.3.15, any help is appreciated

**Comment by EddyVerbruggen** [comment]
Hi, you're opening the share() function from within the InAppBrowser?

That's a bit hard to support as those plugins don't know each other at the moment and I'd rather keep it that way.

I don't know your app, but can't you hide the InAppBrowser before calling share() ?

**Comment by Riesling11** [comment]
Hi, thanks the for the tip, hiding the InAppBrowser is not possible as far as I know but closing it works. After the sharing I then reopen it with the last page - I am loosing the history, but I can live with that :) Thank you

**Comment by hasandogu** [comment]
I am having this issue now. However, it is not quite possible to close the InAppBrowser in my case.

**Comment by EddyVerbruggen** [comment]
Hi @hasandogu and @Riesling11, I actually found a way to show the share sheet on top of InAppBrowser. It's part of 4.3.20.

**Comment by hasandogu** [comment]
That's awesome @EddyVerbruggen. Looking forward to it. The same happens with the Toast plugin as well. Do you think we can apply the same in there too?

**Comment by dineshs27** [comment]
@EddyVerbruggen can you please share your script , actually i have to open camera over inappbrowser , but getting the window hierarchy issue
