### ISSUE TITLE
Share via instagram

### ISSUE THREAD

**Issue by agrapps** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#326]
Hi, how can i share an image via instagram

Thanks

**Comment by DarrylD** [comment]
Also interested in this as the Instagram plugin isn't working.

**Comment by jvence** [comment]
+1

**Comment by vmcampos** [comment]
I demoed this to my students on 4/30 and it worked just fine. We were using Cordova on Android (real and virtual devices). What's your setup, @agrapps?

**Comment by extempl** [comment]
@vmcampos I believe, that @agrapps saying about ios Instagram sharing, since it is not really easy to do.

**Comment by ahait** [comment]
Also interested in a shareViaInstagram, especially for iOS...  is it in the pipeline?

**Comment by guykatz** [comment]
+1
Eddy we would love you to comment of possible.
Thanks!

**Comment by EddyVerbruggen** [comment]
Hey guys, thanks for all the votes :+1: 

I've done a little research and think `shareViaInstagram` is possible. Will try to add it in a few days.

**Comment by guykatz** [comment]
great!
instagram is to much of a big player to pass in this plugin :)

**Comment by EddyVerbruggen** [comment]
Please test the master repo which now contains a `shareViaInstagram` method. And please [take note of the quirks mentioned in the readme](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#instagram).

**Comment by guykatz** [comment]
Small question,
Is the pgb plugin I build with from the pgb repo updated with this change?

**Comment by EddyVerbruggen** [comment]
No. I can't update it. Su use npm plz.

**Comment by guykatz** [comment]
K thanks...
