### ISSUE TITLE
undefined is not an object (evaluating n.plugins.socialsharing)

### ISSUE THREAD

**Issue by massimocristofori** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#331]
Hi there,
I'm trying to reproduce your video example ( https://blog.nraboy.com/2014/10/implement-social-media-sharing-ionicframework/ ) following the same steps, but it's not working.
The only difference, is that I'm running it on a ionicView instead of an Android simulator.
 
the error, as the subject says, is:
TypeError: undefined is not an object (evaluating 'n.plugins.socialsharing')

could you please help me?
thanks

**Comment by EddyVerbruggen** [comment]
Hi, it's not my video, but ok. Do you have 'n.plugins.socialsharing' or 'nl.plugins.socialsharing'?

Also, do third party plugins work in Ionic View anyway?

**Comment by massimocristofori** [comment]
this is what i find in my plugins directory:
nl.x-services.plugins.socialsharing
for the third party plugins .... right now I'm using just org.apache.cordova plugins, plus your :)

**Comment by EddyVerbruggen** [comment]
As you can see [here](https://github.com/driftyco/ionic-view-issues/issues/15) the Ionic View app does not support most third party apps. Please open an issue at their repo.
