### ISSUE TITLE
iOS 8 Facebook share

### ISSUE THREAD

**Issue by bitflower** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#332]
Hi,
i get libc++abi.dylib: terminating with uncaught exception of type NSException (lldb) with this code:

        var message = 'test;
        var link = 'http://www.test.com';
        var image; // = '';

        // FACEBOOK
        $scope.sendFacebookMessage = function() {

            if (!window.plugins) {
                return;
            }

            $cordovaSocialSharing
                .shareViaFacebook(message, image, link)
                .then(function(result) {

                    // Go to social sharing successful view
                    // $state.go('app.end');

                }, function(err) {
                    // An error occurred. Show a message to the user
                });

        };

Latest Ionic 1.3.19, Cordova 4.3.0 on OSX 10.9.5/iPhone 6 with iOS 8.2.

Any idea? I took the JS code from ngCordova.

Thanks Eddy!

EDIT: Whatsapp sharing works! With the same code....

**Comment by gasperz** [comment]
I have similar error. I have tested with iOS 7 (on simulator) and it works. With iOS (8.x) I get this error. Tested with simulator and iPod(8.3). But "window.plugins.socialsharing.share" is working ok. Using Sencha touch 2.4.1 and cordova. Is this iOS 8.x problem. Or am I missing something?

**Comment by abremner** [comment]
I'm also getting libc++abi.dylib: terminating with uncaught exception of type NSException error on iOS 8.3 when using shareViaTwitter(), the standard share() method seems to be working ok.

**Comment by EddyVerbruggen** [comment]
Just tried it /w 8.3 and Facebook. Everything fine, so I need some help reproducing this.

Best option: an XCode project by one of you guys which shows the error.

Other option: the exact code leading up to the crash, including actually shared images/urls..

**Comment by abremner** [comment]
Not sure if this helps but for me it is crashing on any shareVia... functions. This is happening on all 8.x versions and works fine on iOS 7. The log also lists
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <MainViewController: 0x7f8241f29390>.'
***

Sorry, I don't have an Xcode project I can publicly supply.

**Comment by abremner** [comment]
Ok, I created a new Cordova project and was able to replicate the issue. You can get the project here
https://github.com/abremner/Cordova-social-sharing-test

**Comment by EddyVerbruggen** [comment]
A bug sneaked into version 4.3.16. Your comments and code samples pointed me in the right direction, so thanks a lot! Also, please update to 4.3.17 :)

**Comment by uipoet** [comment]
@EddyVerbruggen Thank you for promptly fixing this!

**Comment by abremner** [comment]
@EddyVerbruggen Working fine now. Thanks!

**Comment by bitflower** [comment]
You're the man Eddy! Thanks.

**Comment by ShindePrasad** [comment]
$cordovaSocialSharing.share(message, "From StreetBuzz", image, link).then(function(result) {

"What ever I write here doesnt execute"
console.log(result);
});


I want to execute some action on then success response.
Pl look into it, or if I am wrong correct me.

**Comment by fabiofebo** [comment]
Hi, congratulations for this plugin, it is truly beautiful.
However, I am having a problem, the emulator of xcode with ios 8.4, the plugin works, but when I upload the application on ionic view, on the iPhone 5S or iPhone 6 with ios 8.3, the plugin does not work and does not show the window for share the page.
