### ISSUE TITLE
Cannot read property 'socialsharing' of undefined

### ISSUE THREAD

**Issue by suraj-mahajan** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#334]
04-12 09:34:39.610: E/Web Console(3138): Uncaught TypeError: Cannot read property 'socialsharing' of undefined at file:///android_asset/www/share.html:29

**Comment by EddyVerbruggen** [comment]
Sounds like `deviceready` didn't fire before you called socialsharing. Can you share your `share.html` file perhaps?

**Comment by suraj-mahajan** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>

<script src="js/jquery.js"></script>
	<script src="_assets/js/index.js"></script>
	
    
    <link rel="stylesheet" href="themes/SurajJM.min.css" />
	
	<link rel="stylesheet" href="themes/jquery.mobile.structure-1.4.5.css" />
	
	<script src="themes/jquery.mobile-1.4.5.min.js"></script>
 
 
	<script type="text/javascript" src="cordova-2.2.0.js"></script>
	<script type="text/javascript" src="cordova_plugins.js"></script>

    
	<script type="text/javascript" src="SocialSharing.js"></script>


    
<script type="text/javascript">

$(document).ready(function () {
onDeviceReady();
	//document.addEventListener("deviceready", onClickBtnShare, false);
	 $("#shareBtn").click(socialShare);
	 
	 function socialShare(){
	  window.plugins.socialsharing.share('Test Share', null, null, 'http://link');
	}
});



	function ShareThispp()
	{
		//share("Hay budy, I am using SN LIVE NEWS Android app, get live news on your Android device.","\nSN Live News:- http://www.snlivenewscom/SNLive.apk" )	
		$(window)[0].plugins.socialsharing.share('Test Share', null, null, 'http://link');
		
	}
</script>
    

	
    
  <link href="js/style.css" rel="stylesheet" type="text/css" media="screen">
    

</head>

<body>


<a href="#" id="shareBtn">Share </a>

<button onclick="window.plugins.socialsharing.share('Message only')">message only</button>
</body>
</html>

**Comment by suraj-mahajan** [comment]
please give me your email id i'll send you my project.
Thanks for help

**Comment by suraj-mahajan** [comment]
here is my share.html file
https://www.dropbox.com/s/oqwui6baqcjwqgs/share.html?dl=0

**Comment by suraj-mahajan** [comment]
@EddyVerbruggen E
And here is my full Eclipse project.

https://www.dropbox.com/s/gc6u8ki6mhsnuxu/Sharing.rar?dl=0

please help

**Comment by EddyVerbruggen** [comment]
Hmm, I have a few bits of feedback for you, please PM me at eddyverbruggen at gmail.com
