### ISSUE TITLE
unable to use share in ios

### ISSUE THREAD

**Issue by arulapj** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#335]
Hi,

i have updated the plugin to latest 4.3.17

<gap:plugin name="nl.x-services.plugins.socialsharing" version="4.3.17" source="plugins.cordova.io"  /> 

using phonegap build, but still i am not able to use common share, but the same app works in android.. other than share option, i am able to use shareViaFacebook, shareViaTwitter etc in ios

code 

window.plugins.socialsharing.share(msg,txd,imgtag, function() {console.log('share ok')}, function(errormsg){
				console.log(errormsg);
	});

above thing doesnt do anything

tested in ios 7 and ios latest 8 version

**Comment by osro** [comment]
I can confirm this. Same problem here. Common share works only on Android.

**Comment by EddyVerbruggen** [comment]
@arulapj The usage of `share` is incorrect as it takes 6 params, the last two are the callbacks.
@osro How do you use it?

**Comment by osro** [comment]
Just like in the examples. This works fine on Android, but with iOS it opens the sharing dialog but nothing is passed to the app that's it shared.

```javascript
window.plugins.socialsharing.share('Message only');
```

**Comment by EddyVerbruggen** [comment]
That's not the same issue btw.

If you try to share that to Facebook you won't see it, so where are you sharing to?

**Comment by osro** [comment]
I have tried SMS, Email, Facebook, Twitter... it just opens empty message

Like this... empty SMS message.
![Image SMS]
(https://lh3.googleusercontent.com/0jskKcX5MlVdr7KrPVfcEXkFQ_lQQ-Qhlz6T330G3E7uphXviUUWCzPvJgk3ZQudxZB0qnNU858UFoI=w1416-h838-rw)

**Comment by EddyVerbruggen** [comment]
Please show the exact line of code you're using to share, as well as the plugin version you're using.

And I mean `share('the actual text...`, not `share(myVariable` :)

**Comment by osro** [comment]
Well, at the moment it's exactly like the example line :smile: 

```javascript
window.plugins.socialsharing.share('Message only');
```

PhoneGap 5.1.1-0.29.0
Plugin 4.3.19-dev I downloaded the plugin today via PhoneGap's add plugin command.

On Android it works as excepted
https://drive.google.com/file/d/0Bx8hfxonufSQckNFMVhabVlHTXc/view?usp=sharing

**Comment by EddyVerbruggen** [comment]
Sorry, missed that comment.

I just tried it on iOS 8.4 Sim (iPhone 6 and 6+) and iOS 8.4 iPhone 6 device, with a vanilla CLI project. Everything seems to be working fine.

Can you please try [this project](https://drive.google.com/file/d/0B77kDELmhlXNd3MwYS1mWHRZdk0/view?usp=sharing)? Unzip it, go to platforms/ios and run the XCode project.

**Comment by osro** [comment]
I think i'm going shoot myself :wink: Found the problem...

For some reason (probably some copy paste glitch) 
I had this empty share few lines before the actual line

```javascript
window.plugins.socialsharing.share('');
```

And seems that the iOS stops on the first one and Android goes with the last one it gets.

Sorry about the hustle, now it's working! Thanks!

**Comment by EddyVerbruggen** [comment]
Wow, nicely found :+1:
