### ISSUE TITLE
Is it possible to remove the previous image when sharing links?

### ISSUE THREAD

**Issue by SMJ93** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#337]
Hi Eddy, 

Great plugin!

Is there a way to remove the preview image (on the right)? 
And disable the location section (at the bottom)?

Here is a screenshot of the app:
https://imgur.com/Pq9W7MQ

Cheers, Stu

**Comment by EddyVerbruggen** [comment]
Hey Stuart,

Sure it is, simply don't pass a URL or image to the plugin. For the rest - it's the built-in iOS Twitter sharing widget over which no one but Apple has any control.

Best,
Eddy

**Comment by SMJ93** [comment]
Thanks Eddy! 

Ahh I see! I need a URL though.. Guess the users will have to put up with the image preview!

I thought it might have been built into Facebook and Twitter, cheers though!

Regards, Stu

**Comment by EddyVerbruggen** [comment]
The nice thing is that if you pass a URL that image will actually be a small preview of the webpage. It's pretty slick and at least it is what users are used to.

Cheers,
Eddy

**Comment by SMJ93** [comment]
Yeah, it looks better with the box, but my client wanted it without.

Thanks anyway! Best of luck!

Cheers, Stu
