### ISSUE TITLE
Packaging to windows 8.1 / windows Phone 8.1 issue

### ISSUE THREAD

**Issue by zabojad** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#338]
When validating an app package that contains this plugin, it fails with the following error:

File encoding test

FAILED
UTF-8 file encoding
Error Found: The UTF-8 file encoding test detected the following errors:
File plugins\nl.x-services.plugins.socialsharing\www\SocialSharing.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).
Impact if not fixed: HTML, CSS, and JavaScript files must be encoded in UTF-8 form with a corresponding byte-order mark (BOM) in order to benefit from bytecode caching and to avoid other runtime error conditions.
How to fix: Open the affected file, and select "Save As..." option from the File menu in Visual Studio. Select the drop-down control next to the Save button and select "Save with Encoding..." option. From the Advanced save options dialog, choose the "Unicode (UTF-8 with signature)" option and click the OK button.

**Comment by EddyVerbruggen** [comment]
Recreated the file, don't think much will change for you though.

If you still have an issue with this please follow the instructions provided by the validator and send a PR.
