### ISSUE TITLE
Facebook Message not showing on iOS anymore

### ISSUE THREAD

**Issue by rogercrandall** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#344]
It was working a few days ago, and now it just sends the image without a message

**Comment by EddyVerbruggen** [comment]
Crap!

It seems like Facebook finally closed that loophole on iOS as well. On Android it has never even been possible.

It's against their policy to prefill the share sheet message, see the last bullet [here](https://developers.facebook.com/docs/apps/review/prefill). And it seems like a recent Fb app update enforced that policy.

I found one pretty unusable workaround: remove the Facebook app from the device and use the built-in iOS share widget. It looks the same but it still allows sharing messages (the thing found in iOS Settings > Facebook).

If you really need to share a (prefilled) message to Facebook on iOS (and Android for that matter) then using the [Facebook plugin](http://plugins.telerik.com/plugin/facebook) is required as it uses the Facebook SDK which is allowed to prefill the message. But it's a bit of a pain to set up.

**Comment by EddyVerbruggen** [comment]
OK, FU Facebook.

I have now implemented `shareViaFacebookWithPasteMessageHint` for iOS (Android already had this 'feature').

If the Fb app is installed and a message is passed, this new function will show a 'paste hint' like shown below. It will automatically appear and disappear and you can pass in any hint you want (the default hint is shown in the screenshot).

![img_3652](https://cloud.githubusercontent.com/assets/1426370/7336299/afdc7700-ebf7-11e4-975e-861b08e87571.PNG)
![img_3653](https://cloud.githubusercontent.com/assets/1426370/7336301/afdd0a12-ebf7-11e4-8da5-66a9851cb77a.PNG)
![img_3654](https://cloud.githubusercontent.com/assets/1426370/7336300/afdc8560-ebf7-11e4-94b9-ce495f0b1488.PNG)

**Comment by EddyVerbruggen** [comment]
Available in [4.3.18](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/releases/tag/4.3.18)

**Comment by rogercrandall** [comment]
is there a way to implement this with Phonegap Build?

**Comment by EddyVerbruggen** [comment]
Good question - Yes there is.

See [the readme](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#phonegap-build) for what you need to add to your `config.xml`, it will use the latest version from plugins.cordova.io (I just published it).

**Comment by rogercrandall** [comment]
thank you.. you are the man!

**Comment by rogercrandall** [comment]
The Facebook plugin you referred to that is a "bit of a pain to set up".. Can this be used with "Phonegap Build"? I just really love the way the twitter share works, and I want to have a similar result when sharing via Facebook.

**Comment by ituhin** [comment]
is that "paste message from clipboard" still works ? because i cant see that in my iphone 4s :P 
due to smaller screen! as keyboard comes out automatically ?

**Comment by lincolnthree** [comment]
It seems like you can currently put a bunch of text in the URL field for Facebook. Any chance you could set that native functionality in the plugin for FB so we don't have to work-around for facebook specifically?
