### ISSUE TITLE
FB shareViaFacebookWithPasteMessageHint not working in latest build for iOS

### ISSUE THREAD

**Issue by agfa555** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#345]
FB method shareViaFacebookWithPasteMessageHint is hung up on the latest plugin version (4.3.18). It never returns a value on the callbacks, and the App doesn't respond.
I'm running it on an iPhone 5S with iOS 8.3 (12F670) installed.

Last Xcode message:
"2015-04-28 11:26:10.153 App[1501:1039076] THREAD WARNING: ['SocialSharing'] took '30.614258' ms. Plugin should use a background thread."
Although this appears for other media and works so it's not related.

Great plugin by the way :D

**Comment by EddyVerbruggen** [comment]
Can you share your project with me perhaps?
Also, what is the exact thing you're sharing, and do you have the Fb app installed?

Thx

**Comment by agfa555** [comment]
Hi Eddy,
Unfortunately I can't share the project (not personal) but i can paste the code here. I am trying to share a link. I have the FB App installed and I'm logged in. When I cancel the popup, callback returns ok, but if I send it, it gets stuck. This worked with previous version I was using (4.3.15). It also works on Android on both versions.

$(".icons .icon.facebook").on("click", function() {
			window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint("Share message", null, null, "Share message",
				function(msg) {
					// Returns true always on iOS and false always on Android
					console.log("Share ok: " + msg);
				},
				function(error) {
					console.log("Error: " + error);
				}
			);
		});

Thanks for your time!

**Comment by EddyVerbruggen** [comment]
Can't reproduce unfortunately. You did see the paste hint popup ('share message' in your case?)

Can you try adding a URL or image to the post as well? Also, can you show a screenshot of what you mean by 'it gets stuck'?

Thanks!

**Comment by agfa555** [comment]
Hi Eddy,

When I add a URL it works as expected. :)

But leaving that parameter null causes the App to stop working after you press the send button of the FB dialog. Never returns a callback and I can't click anywhere else. It never reaches FB either. I tested it on an iPhone 6 with 8.3 and it happened too. FB dialog cancel button works as expected with no side-effects.

Related to the hint, I believe the paste hint popup appears but only so fast and then the FB dialog is over it. I can't really tell cause it's so fast. Maybe it would work better with a timeout. Just a thought.

If you want I can close the issue, or I'll leave it open just in case you want to check those couple of things. Hope this helps.

And thanks again!!!!!

**Comment by 0mega** [comment]
Hello, I am also having issues with `shareViaFacebookWithPasteMessageHint(...)` on iOS 8.3.
My share use cases require that I post:
1. only image (for which I use imageURL argument)
2. only text (using message argument)
3. image and text (imageURL and message arguments)

Note: I never see the hint popup.

Result for each use case:
1. Image is shared normally.
2. Apparently text is not copied to "clipboard" and I have nothing to paste, but it still allows me to send the post anyway. So when I hit "Post" it results in a status update (without content) on my FB page.
3. The result is the same as for (1). It only pre-fills image and does not copy any text to clipboard.

Any ideas why am I getting this behaviour, any workaround for this use cases?

Thanks

**Comment by DmytroT** [comment]
Hi Eddy,
I have the same issue. I use shareViaFacebookWithPasteMessageHint, ios 8.3.
Popup hint doesn't appear, clipboard doesn't contain shared message. :(

**Comment by dimoreira** [comment]
Any updates on this guys?

**Comment by EddyVerbruggen** [comment]
Will look at it tomorrow. In the meantime @dimoreira, how exactly do you invoke the plugin?

**Comment by dimoreira** [comment]
@EddyVerbruggen Using the same steps from [ngCordova](http://ngcordova.com/docs/plugins/socialSharing/).

Using it in an Ionic app.

**Comment by EddyVerbruggen** [comment]
@dimoreira There is no example of the pastemessagehint function on that page.

@0mega (and possibly @DmytroT) if the message is prefilled then it's using the built-in iOS sharesheet, not the one from the Facebook app. Do you have the Fb app installed (and is it a recent version, where they have overridden the built-in iOS sharesheet)? Only the sheet of the Fb app will show the paste hint, which is fortunate because only then it's required.

**Comment by 0mega** [comment]
@EddyVerbruggen Thanks for reply.

In order to test my use cases I had to uninstall and install FB app several times, so it is the most recent version I guess =). But I never see the paste hint. Didn't have time to explore it more =|

**Comment by EddyVerbruggen** [comment]
@0mega Thanks for helping! Can you show me what exactly you are posting? Not the variable names but the values: `shareViaFacebookWithPasteMessageHint('message', ..`

Even better: the XCode project from the platforms/ios folder, so I can debug this b*tch.

**Comment by 0mega** [comment]
I'm sorry but I think I can't give you those because we ended up using the `plugins.socialsharing.share(...)` method. So now there is no fast way of providing you anything related to that issue :disappointed:.
Nevertheless if we decide to use it or if I get some spare time I'll try to reproduce the issue again.

Thanks again for your feedback, and for this plugin ;)

**Comment by mthahzan** [comment]
@EddyVerbruggen I'm facing this same issue. Debugging with XCode I found out

```
BOOL fbAppInstalled = [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"fb://"]]; // requires whitelisting on iOS9
if (fbAppInstalled) {
  ....
```

Right here `fbAppInstalled` is **false** although the (up to date) app is installed in the device. When I manually added `<string>fb</string>` to `LSApplicationQueriesSchemes` in `info.plist` the message is displayed (like in a kind of an alert) over the share popup and is copied to the clipboard. Any idea how to get around this?

Here's the output of `ionic info`

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : not installed

**Comment by EddyVerbruggen** [comment]
While debugging iOS 11 issues I found that the paste message is not correctly placed on the clipboard. No idea which iOS version changed that, but we have to use pasteboardType `public.utf8-plain-text` instead of `public.text`. The former seems to add HTML to the clipboard which Facebook is not (or no longer) able to interpret.

**Comment by EddyVerbruggen** [comment]
This has now been fixed. The paste message is shown on iOS again. I will push an update to npm once I've tackled a few iOS11 (beta) issues.

Note that the hint is only shown on iOS < 11 when the Facebook app is installed AND the `fb://` scheme has been whitelisted in the plist. That last bit will probably no longer be applicable to iOS 11.
