### ISSUE TITLE
Cordova 5 iOS problem

### ISSUE THREAD

**Issue by sebrojas14** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#346]
After update cordova to version 5.0.0 and prepare iOS I get errors (Using cordova iOS 3.8.0). I try to remove platform an re-add it but when I open the project in xcode shows errors of code deprecated and didn't build
![screen shot 2015-04-28 at 5 14 55 pm](https://cloud.githubusercontent.com/assets/1771574/7381567/3e7d8e1c-edca-11e4-9cf0-d7c27c37bc50.png)

CompileC /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/SocialSharing.o ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-generated-files.hmap -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-own-target-headers.hmap -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-all-target-headers.hmap -iquote /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-project-headers.hmap -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/usr/local/lib/include -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/UninstalledProducts/include -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/DerivedSources/armv7 -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/DerivedSources -F/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -FShoppingAdvisor/Plugins/com.phonegap.plugins.facebookconnect -include /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/PrecompiledHeaders/ShoppingAdvisor-Prefix-bsctnaoubdutuqdvuebjopbuzggd/ShoppingAdvisor-Prefix.pch -MMD -MT dependencies -MF /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/SocialSharing.d --serialize-diagnostics /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/SocialSharing.dia -c /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m -o /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/SocialSharing.o

/Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:315:26: warning: 'dataFromBase64String:' is deprecated: Deprecated in Cordova 3.8 .0. Use cdv_dataFromBase64String [-Wdeprecated-declarations]
          data = [NSData dataFromBase64String:base64content];
                         ^
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:1:
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.h:1:
In file included from /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/CDV.h:36:
/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/NSData+Base64.h:40:1: note: 'dataFromBase64String:' has been explicitly marked deprecated here
+ (NSData*)dataFromBase64String:(NSString*)aString CDV_DEPRECATED(3.8 .0, "Use cdv_dataFromBase64String");
^
/Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:577:34: warning: 'dataFromBase64String:' is deprecated: Deprecated in Cordova 3.8 .0. Use cdv_dataFromBase64String [-Wdeprecated-declarations]
      NSData *fileData = [NSData dataFromBase64String:base64content];
                                 ^
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:1:
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.h:1:
In file included from /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/CDV.h:36:
/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/NSData+Base64.h:40:1: note: 'dataFromBase64String:' has been explicitly marked deprecated here
+ (NSData*)dataFromBase64String:(NSString*)aString CDV_DEPRECATED(3.8 .0, "Use cdv_dataFromBase64String");
^
2 warnings generated.

CompileC /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/SocialSharing.o ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-generated-files.hmap -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-own-target-headers.hmap -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-all-target-headers.hmap -iquote /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/ShoppingAdvisor-project-headers.hmap -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/usr/local/lib/include -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/UninstalledProducts/include -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/DerivedSources/arm64 -I/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/DerivedSources -F/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -FShoppingAdvisor/Plugins/com.phonegap.plugins.facebookconnect -include /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/PrecompiledHeaders/ShoppingAdvisor-Prefix-cfpechbsnxkvrcbqwjrbjoauanyw/ShoppingAdvisor-Prefix.pch -MMD -MT dependencies -MF /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/SocialSharing.d --serialize-diagnostics /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/SocialSharing.dia -c /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m -o /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/SocialSharing.o

/Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:315:26: warning: 'dataFromBase64String:' is deprecated: Deprecated in Cordova 3.8 .0. Use cdv_dataFromBase64String [-Wdeprecated-declarations]
          data = [NSData dataFromBase64String:base64content];
                         ^
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:1:
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.h:1:
In file included from /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/CDV.h:36:
/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/NSData+Base64.h:40:1: note: 'dataFromBase64String:' has been explicitly marked deprecated here
+ (NSData*)dataFromBase64String:(NSString*)aString CDV_DEPRECATED(3.8 .0, "Use cdv_dataFromBase64String");
^
/Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:577:34: warning: 'dataFromBase64String:' is deprecated: Deprecated in Cordova 3.8 .0. Use cdv_dataFromBase64String [-Wdeprecated-declarations]
      NSData *fileData = [NSData dataFromBase64String:base64content];
                                 ^
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:1:
In file included from /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios/ShoppingAdvisor/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.h:1:
In file included from /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/CDV.h:36:
/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/include/Cordova/NSData+Base64.h:40:1: note: 'dataFromBase64String:' has been explicitly marked deprecated here
+ (NSData*)dataFromBase64String:(NSString*)aString CDV_DEPRECATED(3.8 .0, "Use cdv_dataFromBase64String");
^
2 warnings generated.

Ld /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/ShoppingAdvisor normal arm64
    cd /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -L/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -F/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -FShoppingAdvisor/Plugins/com.phonegap.plugins.facebookconnect -filelist /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/ShoppingAdvisor.LinkFileList -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=6.0 -framework AssetsLibrary /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework FacebookSDK -lsqlite3 -weak_framework Accounts -weak_framework Security -weak_framework MessageUI -Xlinker -dependency_info -Xlinker /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/ShoppingAdvisor_dependency_info.dat -o /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/arm64/ShoppingAdvisor

Undefined symbols for architecture arm64:
  "_SLServiceTypeTencentWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeSinaWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_SLServiceTypeFacebook", referenced from:
      -[SocialSharing shareViaFacebook:] in SocialSharing.o
      -[SocialSharing shareViaFacebookWithPasteMessageHint:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
     (maybe you meant: _fbdfl_SLServiceTypeFacebook)
  "_SLServiceTypeTwitter", referenced from:
      -[SocialSharing shareViaTwitter:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/ShoppingAdvisor normal armv7
    cd /Users/fernandocaviedes/Documents/SA/MobileApp/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -L/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -F/Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos -FShoppingAdvisor/Plugins/com.phonegap.plugins.facebookconnect -filelist /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/ShoppingAdvisor.LinkFileList -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=6.0 -framework AssetsLibrary /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Products/Debug-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework FacebookSDK -lsqlite3 -weak_framework Accounts -weak_framework Security -weak_framework MessageUI -Xlinker -dependency_info -Xlinker /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/ShoppingAdvisor_dependency_info.dat -o /Users/fernandocaviedes/Library/Developer/Xcode/DerivedData/ShoppingAdvisor-avsdwpzuhhmdzieauogksgnleheg/Build/Intermediates/ShoppingAdvisor.build/Debug-iphoneos/ShoppingAdvisor.build/Objects-normal/armv7/ShoppingAdvisor

Undefined symbols for architecture armv7:
  "_SLServiceTypeTwitter", referenced from:
      -[SocialSharing shareViaTwitter:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeTencentWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeSinaWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeFacebook", referenced from:
      -[SocialSharing shareViaFacebook:] in SocialSharing.o
      -[SocialSharing shareViaFacebookWithPasteMessageHint:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
     (maybe you meant: _fbdfl_SLServiceTypeFacebook)
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mattbowen** [comment]
I ran into the same problem with similar linker errors. I was able to manually get it to build by going to "Build Phases" of my cordova project, then under "Link Binary with Libraries" adding "MessageUI.framework" and "Social.framework". I see the config to add them in the plugin's XML, so I'm not sure why it's not working, but the manual fix got everything building again.

**Comment by sebrojas14** [comment]
I'm gonna try it tomorrow.

**Comment by sebrojas14** [comment]
Than you @mattbowen !

**Comment by petarov** [comment]
I had the same issue. I removed the platform and added it again. The plugins got reinstalled and the problem seems to have disappeared.

**Comment by davidemanske** [comment]
Like @mattbowen said, just find the Linked Frameworks and Libraries section in General or under Link Binary with Libraries in Build Phases and add the following two libraries, "MessageUI.framework" and "Social.framework".

**Comment by victorhguillen** [comment]
I did all and nothing works for me, any other idea?

**Comment by victorhguillen** [comment]
I fix it changing this:     dataFromBase64String    to     cdv_dataFromBase64String

**Comment by EddyVerbruggen** [comment]
@victorhguillen You fixed the deprecation warnings, not the build errors, right?
As cordova-ios 4 isn't out yet those base64-related warnings shouldn't prevent your project from successfully building.

**Comment by victorhguillen** [comment]
@EddyVerbruggen thanks for your answer, I don't have building errors, just the warnings. Thanks.

**Comment by EddyVerbruggen** [comment]
Awesome, that's good to know.

Nevertheless I've just pushed an update to the master branch which gets rid of this warning as well.

Note that simply switching to `cdv_dataFromBase64String` would break compatibility with cordova-ios < 3.8.0, so I did it a little different.
