### ISSUE TITLE
iOS 8.x SocialSharing.share facebook - Message not appears

### ISSUE THREAD

**Issue by EduardoNE** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#349]
That is my function:

            $scope.share = function() {
				var img = item.imagem != "data:image/;base64," ? item.imagem : NULL;
				var message = "waw aw aw awawaw awawaw awawaw";
				
				console.log(message);
				$cordovaSocialSharing.share(message, item.nome, img, "http://chef.com.br");
			}

everytime when i've been run the app the console.log was returned with the correct value but the box to share in facebook was displayed empty.

The most weird is, another option works fine.

**Comment by udfalkso** [comment]
I'm also having this issue.  I have a feeling it's due to a recent iOS update.  It definitely used to work.  Other services continue to show the message, as @EduardoNE says.

**Comment by EddyVerbruggen** [comment]
You can thank the latest Facebook app update for this. See #347.
