### ISSUE TITLE
Is it possible to pre-populate location?

### ISSUE THREAD

**Issue by drastick** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#351]
Just wondering if it is possible to fill in the users location either via lat, lng or asking the user to allow access to location data?

![image](https://cloud.githubusercontent.com/assets/2067242/7454093/63fa3b9a-f23e-11e4-8c9a-09bc925a580e.png)

**Comment by sevameyer** [comment]
Hi! Have you ever found a solution to this problem?

**Comment by iliraga** [comment]
Any update on that?

**Comment by EddyVerbruggen** [comment]
Nope.
