### ISSUE TITLE
shareViaFacebookWithPasteMessageHint success and cancel callbacks are the same

### ISSUE THREAD

**Issue by rogercrandall** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#352]
They both return true. The twitter one works great. Any ideas?

**Comment by EddyVerbruggen** [comment]
Quick Q: iOS or Android?

**Comment by rogercrandall** [comment]
iOS

**Comment by EddyVerbruggen** [comment]
`shareViaTwitter`, `shareViaFacebook` and `shareViaFacebookWithPasteMessageHint` share the same code on iOS, but it may depend if you're sharing via the built-in iOS share widget or the app directly. And that depends on whether or not you have the Facebook app installed. Do you have it on your phone?

**Comment by rogercrandall** [comment]
Facebook is installed. The twitter one works totally fine.. But for some reason the Facebook one just returns true even if you hit cancel.

**Comment by EddyVerbruggen** [comment]
Please see my latest comment in #343
