### ISSUE TITLE
Deprecated XLint message compiling with Crosswalk

### ISSUE THREAD

**Issue by leocreo** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#353]
When I compile my application for android with Crosswalk added I'm getting this message:

:compileArmv7DebugJavaNote: ..... platforms\android\src\nl\xservices\plugins\SocialSharing
.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

The plugin works anyway, but this is something that I need to worry about?
Thanks!

**Comment by EddyVerbruggen** [comment]
Thanks for letting me know. You can ignore those warnings for now. I will be playing with Xwalk myself and fix anything that looks suspicious :+1:
