### ISSUE TITLE
canShareVia('facebook',...) is resolved but shareViaFacebook(...) fails

### ISSUE THREAD

**Issue by AphexHenry** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#354]
This issue only happens on **one** of my devices: Android 4.4.2. 
The Facebook app was previously installed on it but has been removed. 
The Facebook messenger app is installed. Removing it works as expected, the canShareVia is rejected.

canShareVia('facebook',...) is resolved, no error.
Calling shareViaFacebook gives me the following error: 
*["com.android.mms", "com.samsung.android.app.memo", "com.sec.chaton", "flipboard.app", "com.google.android.apps.plus", "com.google.android.talk", "com.google.android.apps.docs", "com.sec.android.app.FileShareClient", "com.android.bluetooth", "com.dropbox.android", "com.android.email", "com.google.android.gm", "com.google.android.apps.docs", "com.socialnmobile.dictapps.notepad.color.note", "com.facebook.orca", "com.twitter.android", "com.skype.raider"]*

**Comment by EddyVerbruggen** [comment]
Hi,

If you want to test for the facebook app, please user `com.facebook.katana`.

Best,
Eddy

**Comment by EricDeCoff** [comment]
<b>Solved</b>

This error is cause when the app is not installed on the device

Check your canShareVia and call shareViaFacebook in sucess of can share
<pre>
            window.plugins.socialsharing.canShareVia('com.facebook.katana',
                                                      'Test canShareVia',null,null,null,
                    function(){ 
                        console.log('canShareVia("com.facebook.katana"):success');
                        require(['utils/mobileShare'],function(ms){
                            ms.fb();
                        });
                    }, 
                    function(){ 
                        console.log('canShareVia("com.facebook.katana"):failure');
                        require(['utils/mobileShare'],function(ms){
                navigator.notification.alert('Facebook App Require to use\n\rPlease install the Facebook App\n\rLogin and Setup might take awhile',null,'Facebook App Missing');
                            ms.iconSpinRemove();
                        });
                    }
            );
