### ISSUE TITLE
More Clearly Communicate File Plugin Dependancy for Android

### ISSUE THREAD

**Issue by RaniSputnik** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#355]
When attempting to build a project using the social sharing plugin for the Android platform, the build will fail if you are not also using the [Cordova File plugin](https://github.com/apache/cordova-plugin-file). This should be more clearly communicated + potentially added to the install step.

**Comment by EddyVerbruggen** [comment]
Can you post the error / stacktrace please?
