### ISSUE TITLE
shareViaFacebook content empty issue.

### ISSUE THREAD

**Issue by jinjin86** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#356]
<button onclick="window.plugins.socialsharing.shareViaFacebook('Message via Facebook', null /* img */, null /* url */, function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">msg via Facebook (with errcallback)</button>

when i use above code, I can't see any text in post dialog (ios 8.1.2).
but after remove facebook application on my device, then i can see 'Message via Facebook' in post dialog.

**Comment by victtavares** [comment]
I'm having the same problem on (ios 8.3). Also, when I use the general share function with err callback it's not showing the facebook option to share.

The code:

$cordovaSocialSharing
    .share("Teste", "Teste Body", null, null) // Share via native share sheet
    .then(function(result) {
      // Success!
    }, function(err) {
      // An error occured. Show a message to the user
    });

**Comment by EddyVerbruggen** [comment]
Message not appearing: #344 #347 #349

Facebook not in the list: perhaps you need to fill the URL or image params, as Facebook can't prefill anything with your current usage, so it's probably not considered a valid share target.

**Comment by nfajardo** [comment]
Look at this:
https://developers.facebook.com/docs/apps/review/prefill
