### ISSUE TITLE
Cannot read property 'socialsharing' 

### ISSUE THREAD

**Issue by feng612266** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#358]
I add the plugin manually,copy java/js,modify res/config.xml and cordova_plugin.js;but when i run it ,click the share button has the below question ,who can light me?
05-21 14:02:21.489: E/Web Console(29561): Uncaught TypeError: Cannot read property 'socialsharing' of undefined at file:///android_asset/www/personal/index.html:14

**Comment by EddyVerbruggen** [comment]
Why do you install it manually?

**Comment by feng612266** [comment]
because our team are on the old project development directly,the project is native ,the needs plugins are install manually all,
now I have solved the question,maybe i am not correct reference at that moment,thankyou! this plugin is very good

**Comment by EddyVerbruggen** [comment]
:+1:

**Comment by feng612266** [comment]
the outermost layer package name is "nl.x-services.plugins.socialsharing",but when to a detail platform for example android the src package name is "nl.xservices.plugins.socialsharing", i think if you remove the previous "-"  whether or not a bit better ? thankyou!
