### ISSUE TITLE
Mail not dismiss after opening on IOS

### ISSUE THREAD

**Issue by igorsudijovski** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#359]
Hi,

When I want to send mail then its opening the mail app, but when I click cancel or send it is not closing.
I was digging in the code from SocialSharing.m and I found what is the problem.

line 367 -> [self.viewController dismissViewControllerAnimated:YES completion:^{[self cycleTheGlobalMailComposer];}];

change with [self.globalMailComposer dismissViewControllerAnimated:YES completion:^{[self cycleTheGlobalMailComposer];}];

Is it a valid fix?

**Comment by EddyVerbruggen** [comment]
Absolutely! And I've just added it to the code, it's in the master branch and will be part of the next release :+1:  :+1:
