### ISSUE TITLE
Uncaught TypeError: Cannot read property 'socialsharing' of undefined

### ISSUE THREAD

**Issue by kornsanz** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#361]
"Uncaught TypeError: Cannot read property 'socialsharing' of undefined", source: file:///android_asset/www/js/index.js

**Comment by seven-ply** [comment]
@kornsanz I have the same issue. As soon as you are adding the .then()... after your share method you are getting that error. Leaving the .then() out will remove that issue which might be not an option.

**Comment by seven-ply** [comment]
@kornsanz can you share your code? I had also a similar issue. In the ng-cordova documentation there is still the success- and error-callback outside the share-method. But in the current version it is like this: 
socialSharing.share(message, subject, fileOrFileArray, url, successCallback, errorCallback). So putting the callbacks inside the function call solved my issue.

**Comment by kornsanz** [comment]
window.plugins.socialsharing.share('Message ', 'subject')" as provided in the documentation. It was working on previous version of cordova.

**Comment by EddyVerbruggen** [comment]
Make sure "deviceready" has fired before using the plugin.
