### ISSUE TITLE
Select twitter account

### ISSUE THREAD

**Issue by capitancafe** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#362]
Hi EddyVerbruggen, thanks for this great plugin!
Can i select which tweeter account operate? 
I´m android app and two tweeters accounts in device. 
Thanks!

**Comment by EddyVerbruggen** [comment]
The default account will be used, it's not up to the plugin to provide a UI for that. If anything, the Operating System (Android) should provide it.
