### ISSUE TITLE
App specific share content

### ISSUE THREAD

**Issue by russick89** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#363]
Awesome plugin, great work!

Is there a way to have share specific content?  For instance I want to share a link via facebook and twitter and text via sms and email.  Is there any built in way to do something like this?

<script>
function share_stuff(){
var message = { default:"", sms:"sms text here", email: "e-mail text here" } ;
var link = { default: "http://www.example.com", sms: null, email: null };
var subject = { default: "", email: "email subject" };
window.plugins.socialsharing.share(message, subject, null, link);
}
</script>

<button onclick="share_stuff()">share stuff</button>

If not is there a way to invoke the share and have it callback so I can use their selection to generate the content?

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi,

The share sheet and its consecutive dialogs are controlled by the operating system. You can't intercept click events or something similar to tweak the content for a specific share target.

The only option is to use the `shareVia` methods.
