### ISSUE TITLE
publish the plugin in NPM

### ISSUE THREAD

**Issue by Bnaya** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#364]
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by EddyVerbruggen** [comment]
Sure will. Soon.

**Comment by Bnaya** [comment]
Thanks :+1:

**Comment by jamminjames** [comment]
Has this been moved yet, and if so, do we simply change the config.xml line to:
`<gap:plugin name="nl.x-services.plugins.socialsharing" source="npm" />` ?
