### ISSUE TITLE
Cancel is seen as success when it shouldn't

### ISSUE THREAD

**Issue by lamyju** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#366]
Hi there,

First all, I love your work!

Any ideas when this will be fixed? I trigger some code after success and obivously this shouldn't be triggered unless you have actually shared something.

Cheers,
Julien

**Comment by EddyVerbruggen** [comment]
Yes, obviously it shouldn't but as stated in the readme: don't rely on the success handler. It's not something this plugin has control of. If a third party app decides to return a succes result when nothing was actually shared, then my hands are tied.

**Comment by EduardoNE** [comment]
yet? Some suggestions? i really need somethig like this because on my platform i'll give points($) for share. :(

**Comment by strikegamer** [comment]
Same problem here... my app users win some "coins" when they share something. But some people cancel the operation and win, because the callback is always true. i don't have idea how to solve it :(

**Comment by mstueve** [comment]
I need to detect a cancel from `shareViaSMS` and I think it is actually possible to detect in iOS (not sure about Android). In looking through the source, this is the method that dismisses the interface:

``` objectivec
- (void)messageComposeViewController:(MFMessageComposeViewController *)controller didFinishWithResult:
    (MessageComposeResult)result
```

However, if you instead use the following:

``` objectivec
- (void)messageComposeViewController:(MFMessageComposeViewController *)controller didFinishWithResult:
    (MFMailComposeResult)result
```

You can inspect the MFMailComposeResult enum:

``` objectivec
switch (result)
    {
        case MFMailComposeResultCancelled:
            NSLog(@"SMS cancelled");
            ok = 0;
            break;
        case MFMailComposeResultSaved:
            NSLog(@"SMS saved");
            break;
        case MFMailComposeResultSent:
            NSLog(@"SMS sent");
            break;
        case MFMailComposeResultFailed:
            NSLog(@"SMS sent failure");
            ok = 0;
            break;
        default:
            break;
    }
```

And return false if the user cancelled the SMS dialog

**Comment by etherewind** [comment]
Same problem for me
