### ISSUE TITLE
Share with twitter without dialog.

### ISSUE THREAD

**Issue by jorgevidal** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#367]
Hi, I´m wondering if we can share twitter without the dialog. 
I need to check if the user is logged in twitter, and then send the message and picture to twitter without the dialog of posting in twitter. I want to create the share just like the one on Instagram or nike running. 

Any suggestion in how to do this?
Thanx in advance.

**Comment by EddyVerbruggen** [comment]
Hi, you can't with this plugin. Perhaps search for a dedicated Twttr plugin, I'm not aware of its existence.

**Comment by jorgevidal** [comment]
Thanx for your help! Nice plugin by the way!
