### ISSUE TITLE
Image from dynamic URL

### ISSUE THREAD

**Issue by alokjkumar** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#368]
I'm trying to share an image from a dynamic URL, which looks something like:

`http://www.example.com/test.php?apikey=abc123&type=user&id=abc123`

None of the social networks listed seem to like it if I set the image as that URL, I get messages like:

>"Sorry, Messenger was unable to process the file"

or in most cases, just a blank, black square.

Does anyone know of anything that might get me on my way to fixing this? I've a funny feeling it's more of a cordova issue rather than an issue with this plugin itself. I'd guess that the image is taking a little longer to load due to the dynamic nature of it (it's a QR code) and the plugin isn't giving it time to play catch up - but that's just a guess.

EDIT:
Thought it might be useful to know what the exact code is:
`$cordovaSocialSharing.share("Scan my QR code now!", null, "http://www.example.com/test.php?apikey=abc123&id=" + $scope.productId + "&type=product", null);`

**Comment by EddyVerbruggen** [comment]
Are you able to share an actual url static url here?

**Comment by alokjkumar** [comment]
Yep, sharing a static image with a standard .png extension seems to work fine, just the dynamic URLs seem to break

**Comment by EddyVerbruggen** [comment]
I mean, can you paste a URL here that resolves to a QR code?

**Comment by alokjkumar** [comment]
http://www.tugtog.co.uk/api/shareScan.php?apikey=J*c3[%3CopJ|Lhg*1&uxid=722Y68xkAZ&type=user

**Comment by EddyVerbruggen** [comment]
I'm quite sure that URL is the problem, not the fact that it's dynamically generated. Can you make sure the apiKey uses characters that don't need URI encoding?

**Comment by alokjkumar** [comment]
Still no luck, I'm afraid. I changed the apikey to abc123 and got the same error(s) :/

**Comment by EddyVerbruggen** [comment]
Actually, that works great on my end. Tested with email and Fb, see screenshot..

![screen shot 2015-06-07 at 22 57 50](https://cloud.githubusercontent.com/assets/1426370/8026061/ad9029fa-0d68-11e5-975e-0c73377e0c46.png)

**Comment by alokjkumar** [comment]
How odd! It's still refusing to work for me, I'll do some digging and see what's going on. Thanks for you help anyway - great plugin regardless!

**Comment by pokleh** [comment]
mine also can't use dynamic image url.
@alokjkumar ... have you solve this issue?

**Comment by alokjkumar** [comment]
@pokleh Nope, ended up just having to share a dynamic URL which ended up having the same effect but just a more cumbersome way. Let me know if you manage to figure it out though - best of luck!

**Comment by fmendoza** [comment]
not working in android with https://lh3.googleusercontent.com/-fuw7rz6gpgc/VNGmqiwxXZI/AAAAAAAAAAU/7BzslJBMXsw/w600-h800-k/

**Comment by EddyVerbruggen** [comment]
@fmendoza Turns our that's because of the trailing slash in your url - without it it works ok. Note that that URL also doesn't set a `Content-Disposition` header so the plugin has no way to determine the filetype.

I will update the plugin to accept files from URL's with a `/` as the last character.
