### ISSUE TITLE
How to share image on the screen at the time?

### ISSUE THREAD

**Issue by jamminjames** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#370]
I see examples of how to share certain images with the app (naming the exact url of the image in the code), but what about sharing the image the user happens to be on at the time they press the share button? How is that accomplished?

For instance, you give the example:
`<button onclick="window.plugins.socialsharing.share('Message and image', null, 'https://www.google.nl/images/srpr/logo4w.png', null)">message and image</button>`
... which will share the image pogo4w.png. But how can we allow them to just share the image they see at the time?

**Comment by EddyVerbruggen** [comment]
Sorry, that's a javascript question, not at all related to this plugin. You can use something like jquery and do:
```js
$(img).click(function(... etc
```

**Comment by jamminjames** [comment]
Forgive me, newbie here. I'd have to hook into your plugin somehow, right? With a variable or something?
