### ISSUE TITLE
Available in npm repository, as Phonegap Build update requires?

### ISSUE THREAD

**Issue by jamminjames** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#381]
Is this app available in the npm repository yet? I searched, but could not find it. If so, what would be the correct line to add to the config.xml? Thank you.

**Comment by EddyVerbruggen** [comment]
I will upload it to npm soon, but until then the latest release (4.3.19) is available on plugins.cordova.io which you can reference in PGB.
