### ISSUE TITLE
Seems like it does not adds provided message to the facebook dialog

### ISSUE THREAD

**Issue by extempl** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#383]
Only url. Maybe we should for FB put all data (message and the url) into url section?
It is possible to differentiate data for different targets. See http://stackoverflow.com/a/16888058/506954

P.S. all works fine with SMS/email//pinterest sharing.

**Comment by EddyVerbruggen** [comment]
That's because Facebook wants the user to type their own personal message. See the readme for details.
