### ISSUE TITLE
verifying post

### ISSUE THREAD

**Issue by daphnawegner** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#391]
Is there a ways to check if the user actually shared the item or canceled when using:

share(message,subject, image, link)

I want to verify if the item was actually shared (or see if the user decided to cancel the native share sheet)

Also is there a way to add the message at the bottom of a facebook shares that said which app it was shared from I have seen those posts with "via xxxxx" at the bottom of posts on facebook. Is this something to set up when posting a message

**Comment by EddyVerbruggen** [comment]
Nope to both. Regarding the latter: if you really need that, you need deeper Fb integration, so look for a plugin using the Facebook SDK. This one uses the built-in share sheet (which many native apps use as well).
