### ISSUE TITLE
Any plan for npm?

### ISSUE THREAD

**Issue by appsystemstaff** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#393]
http://phonegap.com/blog/2015/05/26/npm-plugins-available/

Will you put your plugin on NPM?THANKS.

**Comment by escolhatecnologia** [comment]
+1

**Comment by Bnaya** [comment]
+1

**Comment by bau720123** [comment]
+1

**Comment by awebdeveloper** [comment]
+1

**Comment by EddyVerbruggen** [comment]
cordova-plugin-socialsharing is taken (for a while now), that's what's holding me back. So perhaps I'll settle for cordova-plugin-x-socialsharing instead. Suggestions are welcome.

**Comment by katejp** [comment]
cordova-plugin-socialshare ?

+1

**Comment by roberthovhannisyan** [comment]
:+1: 
Would be great to see it with any name on npm along with cordova-plugin-actionsheet (you should hurry up while it is not yet taken)

**Comment by EddyVerbruggen** [comment]
@roberthovhannisyan good call on actionsheet - published just now.

And SocialSharing is following later today, I settled in cordova-plugin-x-socialsharing, just like I had to do with toast. I don't want to use cordova-plugin-socialshare because that may conflict with a colleague's plugin.

**Comment by EddyVerbruggen** [comment]
OK, done: cordova-plugin-x-socialsharing is up, use it on phonegap build with `source="npm"`.

**Comment by bau720123** [comment]
thanks @EddyVerbruggen !!!

**Comment by escolhatecnologia** [comment]
thanks  @EddyVerbruggen
