### ISSUE TITLE
Share not working on iOS in combination with inAppBrowser

### ISSUE THREAD

**Issue by androdel** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#396]
Hello,

If I want to share an url with your plugin on iOS, but I get the following output:
-----
Attempt to present <SLFacebookComposeViewController: 0x1ee56380> on <MainViewController: 0x1dd97120> which is waiting for a delayed presention of <SLFacebookComposeViewController: 0x1ed8a1d0> to complete

Warning: Attempt to present <SLFacebookComposeViewController: 0x1ed8a1d0> on <MainViewController: 0x1dd97120> whose view is not in the window hierarchy!

Attempt to dismiss from view controller <MainViewController: 0x1dd97120> while a presentation or dismiss is in progress!
-----
Situation:
In the inAppBrowser I click on a button to share an url to Facebook. Instead of opening the share screen, it closes my inAppBrowser and doesn't show anything. It only does this on iOS(6). On Android there is no problem at all.

Any idea how to fix this?
Kind regards.

**Comment by EddyVerbruggen** [comment]
You can't show two native viewcontrollers simultaneously; while InAppBrowser is being closed, the share sheet is being shown. If you close the browser from its API and call socialsharing after a little `setTimeout`, you should be ok.

**Comment by EddyVerbruggen** [comment]
Scrap that, found a fix! It's part of 4.3.20.

**Comment by androdel** [comment]
Nice! Thanks a lot!

**Comment by EddyVerbruggen** [comment]
You're welcome.

For future reference: you can't show two viewcontrollers simultaneously, but it turned out that wasn't causing the problem.

The problem was that the plugin attempted to show the share sheet on top of a viewcontroller (inappbrowser) which was no longer the top most (the webview).

So we now search for the top most viewcontroller when we want to show the share sheet and have that one present it.

**Comment by androdel** [comment]
Is it possible that the 4.3.20 is not available yet on the cordova plugin registry? I can't get the latest version for my app.

**Comment by EddyVerbruggen** [comment]
Cordova plugin registry is readonly these days, but you can grab it from npm: cordova-plugin-x-socialsharing (v5.0.1).

**Comment by androdel** [comment]
Okay, found it and installed it. Unfortunately, there are still some problems. Sometimes the app crashes all together when the share dialog opens. If it doesn't, the dialog screen comes up, but the button to post it is disabled and if you want to cancel, only the keyboard disappears and not the dialog itself. Is this also something related to the plugin or is this purely the Facebook app?

**Comment by EddyVerbruggen** [comment]
Can you share the code you're using to trigger facebook?

And this only happens when triggering sharing when inside the inappbrowser? It would be really helpful if you tell more about your usecase. Perhaps even sharing a project reproducing this problem.

**Comment by androdel** [comment]
Here the code that I use for triggering the Facebook share dialog:

ref.addEventListener('loadstart', function(e){
...
if(/facebook.com\/sharer/.test(e.url)){
                    window.plugins.socialsharing.canShareVia(fbPackage,null,null,null,e.url,
                        function(){
                            ref.executeScript({
                                code: "try{window.stop()}catch(e){document.execCommand('Stop')}"
                            });
                            window.plugins.socialsharing.shareVia(fbPackage,null,null,null,shareUrl);
                        }
                    ); 
                }
...
});

The scenario: When you are on an article, you can share that specific article to Facebook, Twitter, ... When the user clicks on the FB icon, I check in the inappbrowser if the url that is loaded is the FB share url. If that is the case, I stop loading that url and execute your plugin to show the share dialog.

You see the button to post (right top) is disabled
![img_0200](https://cloud.githubusercontent.com/assets/13794129/9990809/a79dc4f4-6064-11e5-82b1-a7b758cb72bb.jpg)

Here i clicked the cancel button and only the keyboard closes
![img_0201](https://cloud.githubusercontent.com/assets/13794129/9990822/c8649b86-6064-11e5-9bbc-3f61d0ff7839.jpg)

**Comment by ne0c0de** [comment]
I have exactly same situation with @androdel 

i'm using InAppBrowser in my application and if there's a sharing url in inappbrowser and the user was trying to click on it, i'm stopping the loading of facebook url and proceed with window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint function

However when the sharing is done or cancelled the iab window was closed with sharing window.

Can we apply a quick fix for this?

**Comment by ne0c0de** [comment]
Here's the important log lines from xcode:

`2016-12-02 10:41:06.076 xxx[70528:532292] Warning: Attempt to present <SLComposeViewController: 0x7fece32118c0> on <SLComposeViewController: 0x7fece36a2b50> while a presentation is in progress!
2016-12-02 10:41:10.320 xxx[70528:532292] -[NSNull lowercaseString]: unrecognized selector sent to instance 0x1062abd80
2016-12-02 10:41:10.321 xxx[70528:532292] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull lowercaseString]: unrecognized selector sent to instance 0x1062abd80`
