### ISSUE TITLE
Uncaught TypeError: Cannot read property 'share' of undefined

### ISSUE THREAD

**Issue by angelorm** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#398]
So I'm using Cordova on Netbeans to compile my projects to Android and I want to use this plugin to share content into social media but I'm getting this error:

Uncaught TypeError: Cannot read property 'shareViaFacebook' of undefined (14:30:33:603 | error, javascript)
    at onclick (www/index.html:1:114)

I'm calling the plugin like this: onclick="window.plugins.socialsharing.share('Test Title', 'Test Text', null, 'http://www.google.com')"

I think I've installed the plugin correctly and it's being recognized otherwise it would show an error on the socialsharing part, right? Can anyone help?

**Comment by EddyVerbruggen** [comment]
If you still need help feel free to DM me at eddyverbruggen at gmail dot com
