### ISSUE TITLE
[Issue] Calling canShareVia "facebook" returns 'Cannot share on Facebook' error on iOS 8.4.1

### ISSUE THREAD

**Issue by saintc0d3r** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#399]
**Sinopsis**
When running an Cordova mobile app on iPhone which runs iOS 8.4.1 and the app's feature calls SocialSharing's canShareVia method with "facebook" set as 1st parameter, "Cannot share on Facebook" error is returned although the facebook app's settings in the iPhone have been set to allow all applications to use the associated facebook's account.

**Environment settings**
- **Development environment**
  - Cordova CLI: 5.2.0
  - Ionic Version: 1.1.0
  - Ionic CLI Version: 1.6.4
  - Ionic App Lib Version: 0.3.8
  - ios-deploy version: 1.4.0 
  - ios-sim version: 3.1.1 
  - OS: Mac OS X Yosemite 10.10.5
  - Node Version: v0.12.0
  - Xcode version: Xcode 6.4 Build version 6E35b 
  - ngCordova version: 0.1.20-alpha

- **Test Device environment**
  - Model: iPhone 5c
  - OS: iOS 8.4.1
  - Latest version of Facebook app is installed
 
**Replication steps**
- Write a simple cordova or ionic application which performs share to facebook functionality by calling SocialSharing's canShareVia & shareViaFacebook methods, similar to this code: 
  - .js code: http://tinyurl.com/nt2ouv6
  - html : http://tinyurl.com/nhk3cnf
- Build the code by using cordova & XCode compiler  
- Run the compiled build into the iPhone through XCode
- Invoke share to facebook function on the app.
- Confirm that 'Cannot share on Facebook' alert is shown.
- When the code made a call to canShareVia method is commented or removed so that it calls shareViaFacebook straightforward, no error is reported and the facebook sharing dialog view is shown. 
- This issue does not happens in Android devices.

**Temporary workaround's idea**
Added a check to probe current device's model before calling canShareVia method so that when the device belong to iOS, canShareVia method should not be called.

**Comment by EddyVerbruggen** [comment]
Have you also tried `com.apple.social.facebook`?

From the readme:
```js
<button onclick="window.plugins.socialsharing.canShareVia('com.apple.social.facebook', 'msg', null, null, null, function(e){alert(e)}, function(e){alert(e)})">is facebook available on iOS?</button>
```

**Comment by saintc0d3r** [comment]
Hello Eddy,

When i replaced the 'facebook' parameter to 'com.apple.social.facebook' in the 1st parameter of canShareVia method, the error does not happen. I will update the "Temporary workaround" section now.

Thanks for the reply.

**Comment by EddyVerbruggen** [comment]
The point is that that first param is different for iOS and Android. See the readme for details.

**Comment by saintc0d3r** [comment]
Thanks Eddy, 

I am testing it on android device now and hoping to see no same error occurs in it.

**Comment by saintc0d3r** [comment]
Hello Eddy,

When I replaced the canShareVia's 1st parameter to 'com.apple.social.facebook' and run the app on Android device, 'Cannot share on Facebook' error happened. Therefore, I will leave the temporary workaround as it is.

**Comment by EddyVerbruggen** [comment]
The point is: on Android it's 'facebook', on iOS it's 'com.apple.social.facebook'. It's no work-around, it's how it works...

**Comment by saintc0d3r** [comment]
I see. 
Alright, thank you for your reply, Eddy.
