### ISSUE TITLE
[Question] about this plugin from npm

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#401]
hi @EddyVerbruggen 
I saw a almost 100% the same plugin as yours from npm
https://www.npmjs.com/package/cordova-plugin-socialsharing
but that a man called "appsystem" transfer it to npm

after I compare his (from "npm" 4.3.81) and yours (from "plugins.cordova.io" 4.3.19)
I found seem only one thing different

all code are the same
all function are the work，besides when I use "saveToPhotoAlbum" method
if I use his，not work，use yours，work !!!

so I guess...
according to this teaching page
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
the "saveToPhotoAlbum" method start at version 4.3.16
maybe "appsystem" fork this is lower than 4.3.16
am I right ?

**Comment by EddyVerbruggen** [comment]
Perhaps you can ask him? I'd like to upload it to npm myself but this is kinda blocking.. perhaps I'll use a different name.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I askd him before
but no reply...

yes!!! use a different name is a good idea
if one day have a npm version
please let me know
thanks...
