### ISSUE TITLE
One share but different message for different mediums

### ISSUE THREAD

**Issue by gchokeen** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#404]
Hi,
It's very useful plugin, I am sure this question may raised before and solved but I unable to find it anywhere. Sorry to steal your time!

I have one share button, but I want to share different message on different medium. For example, I want to share long text on "Email, whats app, etc" but on sms should take small length text. twitter should send with twitter handler 

Please help me on this!

**Comment by DaDanny** [comment]
Is a callback fired once the user selects their service? If so, check which service they have selected and format the message for that particular one.

**Comment by gchokeen** [comment]
Hey @DaDanny ,

Thanks for reply. Which callback you talking about. I am using below code callback is triggered only after I shared on some medium. How can I find the service before I share. Can you show me an example

```
window.plugins.socialsharing.share("Message...",null,null,null,function(msg) {console.log('ok: ' + msg)}, function(msg) {alert('error: ' + msg)});
```
Thanks

**Comment by EddyVerbruggen** [comment]
Don't bother for now as it's not possible. If you want to share different content to different providers use the `shareVia*` functions.

**Comment by gchokeen** [comment]
Really Sad :(
