### ISSUE TITLE
iOS Keyboard doesn't appear onSMS activation with multiple numbers

### ISSUE THREAD

**Issue by ullasmohan** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#405]
When the plugin is used a second time on iOS 6 device, the keyboard does not appear and focus is not placed on the "To" field.
How we can resolve this?
Am using Ionic Framework and angular Js (http://ngcordova.com/docs/plugins/socialSharing/)

**Comment by omaxlive** [comment]
I experienced this issue with iOS8 and iOS8.X. I would like a fix for it too.

**Comment by EddyVerbruggen** [comment]
I'm trying this two times in a row without trouble. On iOS9 in the meanwhile though:

Can you guys drop this in, change the numbers, and see what happens?

```js
<button onclick="window.plugins.socialsharing.shareViaSMS('My cool message', '0612345678, 0687654321', function(msg) {console.log('ok: ' + msg)}, function(msg) {alert('error: ' + msg)})">share via SMS</button>
```

**Comment by mstueve** [comment]
I also experienced this, randomly, and with single numbers as well as multiple. By changing the animated property to NO it seems to get fixed:

``` objectivec
[self.viewController presentViewController:picker animated:NO completion:nil]
```

**Comment by EddyVerbruggen** [comment]
@mstueve Nice find! Would you be willing to send a PR to change that?
