### ISSUE TITLE
Slow sharing in Android on button click event

### ISSUE THREAD

**Issue by kirant400** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#406]
Onsen UI + angular JS code
On click event Tried below code it takes minimum 8 sec to launch the share screen in Android. I have not tried it on iOS. Tried removing the settimeout also.
It is same behavior with Jquery  
```javascript
$scope.shareLaunch = function() {   
        addUserData([{'Event':'LauncherShare','Time':moment.utc().unix(),'Post':controllerScope.selectedPost.id}]);    
        setTimeout(function() {
           window.plugins.socialsharing.share(null, null, $scope.selectedPost.image, null);
        }, 0);
      }
```

**Comment by EddyVerbruggen** [comment]
Hi, what's the URL of the image you're sharing?

**Comment by kirant400** [comment]
URL is public facing URL which is already Downloaded and in image cache https://github.com/chrisben/imgcache.js/

**Comment by EddyVerbruggen** [comment]
Smart move. Pass the locally cached imgpath to the plugin and it should work.

**Comment by kirant400** [comment]
Works smooth +1 
```javascript
    console.time("shareLaunch");
        addUserData([{'Event':'LauncherShare','Time':moment.utc().unix(),'Post':controllerScope.selectedPost.id}]);    
        ImgCache.isCached($scope.selectedPost.image, function(path, success){
        if(success){
          setTimeout(function() {
            console.log(path);
            ImgCache.getCachedFileURL(path,function(path,lpath){
                console.timeEnd("shareLaunch");
                window.plugins.socialsharing.share(null, path, lpath, null);
              });
          }, 0);
        } else {
          setTimeout(function() {
           window.plugins.socialsharing.share(null, null, $scope.selectedPost.image, null);
        }, 0);
        }
        });
```

**Comment by guykatz** [comment]
"Smart move. Pass the locally cached imgpath to the plugin and it should work."
can you please ellaborate on how to get a local cached image in from browser?

**Comment by kirant400** [comment]
Use a plugin https://github.com/chrisben/imgcache.js/  Which will give you local reference of the cached image instead of web URL. 
You can then use the cached path from this to share the image.

**Comment by guykatz** [comment]
Oh got it. So in your experience this is more performent as it saves the extra http call?

**Comment by kirant400** [comment]
Yes and it do not depend on network speed once it is downloaded, Consistent performance of the same image

**Comment by guykatz** [comment]
Cool thanks, will definitely try it out

**Comment by EddyVerbruggen** [comment]
Thanks for helping out @kirant400
