### ISSUE TITLE
Can't get this to work on iOS with the GMail app.

### ISSUE THREAD

**Issue by richtera** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#407]
I can't quite figure out if I need to do something different for GMail specifically, but it works for SMS and the normal email app. But when I select GMail it just creates an empty message. Not sure what to check or how to debug. Any ideas?
Thanks
Andy

**Comment by richtera** [comment]
This was due to the &sup2; inside of the message. GMail only allows normal text whereas the other apps seems to support partial xml entities. Changing things to m^2 instead of m&sup2;...

**Comment by EddyVerbruggen** [comment]
Woah, interesting find! Not sure I need to change anything in the plugin really, since others work as expected.
