### ISSUE TITLE
ipad requests login to native app even though I am logged in

### ISSUE THREAD

**Issue by guykatz** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#409]
hi;
I use my ipad with latest ios 8.4.1 and social sharing plugin hybrid app build with phonegap build.
when trying to share via facebook get a pop up that states that I need to login to the app first (see picture)
if I open facebook native app I am logged in so I dont know why this is happening.
any thoughts?
thanks
![img_0020](https://cloud.githubusercontent.com/assets/2852437/9782454/e7d6bc5a-57a5-11e5-8e98-ebb2cdc3def6.PNG)
.

**Comment by EddyVerbruggen** [comment]
I think it's because you're not signed in to the Facebook 'built in' app - see iOS settings > Facebook.

**Comment by guykatz** [comment]
thanks, I will check it

**Comment by joelseneque** [comment]
Hi, I'm logged into Facebook natively but am getting this error on my iPhone 6s Plus on ios 9.1??

**Comment by EddyVerbruggen** [comment]
Where did you log in to Fb?
