### ISSUE TITLE
Plugin ID causes the Windows store to think there are Dutch resources

### ISSUE THREAD

**Issue by rmaclean** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#411]
The ID is `nl.x-services.plugins.socialsharing` which creates a folder starting with the `nl.` - the Windows store sees this folder and assumes that it is for Dutch language resources. Impact is low, means an extra detail during store submission but would be easier if the plugin ID did not have that prefix.

**Comment by EddyVerbruggen** [comment]
woah, that's inconvenient - I'll be renaming this plugin to `cordova-plugin-<something>-socialsharing` (for npm) shortly.

**Comment by EddyVerbruggen** [comment]
Hi @rmaclean it's been renamed, so I hope this solved your issue. Use cordova-plugin-x-socialsharing.
