### ISSUE TITLE
[Issue] Sharing to Google + through calling shareVia method, is not working in iOS

### ISSUE THREAD

**Issue by saintc0d3r** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#412]
Hello all,

I found that calling shareVia method with these 1st parameter values, does not show google plus sharing dialog on iOS: 'google+', 'com.google.ios.apps.plus', 'google'. What is the correct string parameter that I need to pass into shareVia method's 1st parameter for showing the google plus sharing dialog in iOS ?

Cheers.

**Comment by EddyVerbruggen** [comment]
You can't using this plugin, but you should be able to use [the AppAvailability plugin](http://plugins.telerik.com/cordova/plugin/appavailability).
