### ISSUE TITLE
Text Won't Appear on Facebook

### ISSUE THREAD

**Issue by daksamedia** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#413]
Hello Eddy,
I tried use this plugin, it works magfinicent on iOS then I tried to Android (I'm using Lollipop version).
But, the problem is text won't appear on facebook post dialog.

I there any problem?
Please, give me your advice.

Thank you in advanced.

Daksa Media

**Comment by EddyVerbruggen** [comment]
Please see the readme and a dozen of similar issues. Sharing text to Fb is not possible.
