### ISSUE TITLE
iOS9. The App crashes on start.

### ISSUE THREAD

**Issue by oleksiy-nesterov** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#417]
iOS9. The App crashes on start, in case if plugin is included. Works fine without plugin. iOS9 only issue. iOS7-8 is fine.

**Comment by EddyVerbruggen** [comment]
I'll take a look..

**Comment by EddyVerbruggen** [comment]
Hmm no problem here.. what are you doing on start?

Please try:

```
cordova create test
cd test
cordova platform add ios
cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
cordova build ios
```

Then deploy to your iOS9 device (mine is an iPhone 6).

**Comment by oleksiy-nesterov** [comment]
Hi. You are right. Thanks.
