### ISSUE TITLE
android removal of org.apache.http.* with API Level 23

### ISSUE THREAD

**Issue by boredom2** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#426]
Hi and thanks for your really great plugin.
Compiling you Plugin with latest android Studio and API Level 23 (at elast as targetSdkVersion), will fail unless I add

    compile 'org.apache.httpcomponents:httpclient:4.5'
    compile 'org.apache.httpcomponents:httpcore:4.4.3'

in order to re-enable the now removed apache httpcomponents.
do you plan to switch to the new modules?

Thanks a lot!

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this issue. It was deprecated in 22 and removed in 23. That's unusually quick. I've swapped the implementation to something else in v5.0.3 of this plugin (available on npm).

**Comment by bramus** [comment]
Thanks for the (very quick!) fix.
