### ISSUE TITLE
Can't use ampersand "&" with shareViaWhatsApp on iOS

### ISSUE THREAD

**Issue by bobolat** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#427]
hello there..anyone have problem like me? for example my text is " bobo & friends"..when i call functtion share via whatsapp which is this code i use 
```
<button onclick="window.plugins.socialsharing.shareViaWhatsApp('bobo & friends, null /* img */, null /* url */, function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">msg via WhatsApp (with errcallback)</button>
```
when im about to send the text it only read "bobo" only..text after ampersand "&" the plugin not read anymore..on android seems no problem..i just found out this bugs only on ios platform..can someone help me?

**Comment by EddyVerbruggen** [comment]
Hi, do you see this only with `shareViaWhatsApp`? I think there is a similar open issue in this repo about this problem, so I'll take a look as soon as possible.

**Comment by bobolat** [comment]
thanks for the reply..just now i see on that only because i just use that function only..i dont know about the other callback...

**Comment by bobolat** [comment]
i just found out if i did not use your plugin means i use javascript code to share text to whats app..it still can read the ampersand.. i just use this code 
```
<a href="whatsapp://send?text=bobo & friends">
```
still the code cant read the text after ampersand..so right now i dont know the problem is from where..lol

**Comment by EddyVerbruggen** [comment]
Hi, just fixed, available in 5.0.3 (not yet released) and the master repo.

Thanks for reporting it!

**Comment by bobolat** [comment]
how to test?

**Comment by bobolat** [comment]
thanks by the way ..really appreciate

**Comment by EddyVerbruggen** [comment]
Version 5.0.3 is now available on npm.

**Comment by bobolat** [comment]
thanks buddy..u save my live..haha
