### ISSUE TITLE
Problem Share Instagram

### ISSUE THREAD

**Issue by jrortiz8585** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#428]
No found method window.plugins.socialsharing.shareViaInstagram, please a example for integrated width phonegap.

**Comment by EddyVerbruggen** [comment]
Make sure you're using the master repo for now, otherwise it's not available. So how do you add the plugin currently?

[And here's the example](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#instagram)

**Comment by jrortiz8585** [comment]
load the plugin en my config.xml
<gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />	

the method for share instagram no found. Facebook, twitter and whatsapp working very good.

I have problems only with instagram

**Comment by guykatz** [comment]
same here:
updated config xml file to:
<preference name='phonegap-version' value='cli-5.2.0'/>
<gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />

downloaded the apk from build service and went to:
assets\www\plugins\cordova-plugin-x-socialsharing\www\SocialSharing.js (injected by the build service) and it does not include instagram....

any ideas on what I'm doing wrong?

**Comment by guykatz** [comment]
note, not sure this has anything to with it.
but PGB cli5.2.0 and npm repository builds are not working properly for the past few hours...

**Comment by EddyVerbruggen** [comment]
Version 5.0.3 (with this new method) was not yet available on npm, but it is now.
