### ISSUE TITLE
Android: Failed to ensure directory: /storage/sdcard/Android/data/com.example.hellotest/files

### ISSUE THREAD

**Issue by eholmes** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#43]
Hi,

I installed the plugin manually and added a button:

&lt;button onclick="window.plugins.socialsharing.share('My message')"&gt;share!&lt;/button&gt;

When I click on the button in the Android emulator, I get this message in the console log:

Failed to ensure directory: /storage/sdcard/Android/data/com.example.hellotest/files

Does anyone know what I am doing wrong?  Thank you!

**Comment by thomasMary** [comment]
Hi @EddyVerbruggen I've the same error ("Failed to ensure directory: /storage/sdcard/Android/data/...."), and so i'm not able to share on twitter or facebook.
I'm working on a real device (Android 4.4), i've the correct permission (WRITE_EXTERNAL_STORAGE)
Here is the code my js code:
-for twitter:
 $cordovaSocialSharings.shareViaTwitter('I love myapp.', imageUrl, null);
-for facebook:
$cordovaSocialSharings.shareViaFacebook('I love viceversa.', imageUrl, null)
I tried for both to upload with and url or base64 image data.
Any idea would be very appreciate. Thanks

**Comment by EddyVerbruggen** [comment]
@thomasMary Can you try sharing a local image? One you host in your www folder somewhere?

**Comment by thomasMary** [comment]
Hi Eddy,

I found what was wrong. Facebook and Twitter were not installed on my phone. I expected a no-native fallback in that case, but i guess this is why you add canShareVia.. methods.
Thanks for that plugin, good job.

**Comment by nh2** [comment]
> I deleted my existing virtual devices, created new ones, and no longer see this error. Thank you for looking at my files!

Worked so well for me.

**Comment by TheShy** [comment]
Hi@Eddy,
  I've had a similar situation.More than(Android 4.2)  of the models and more than (Android 4.4)  of the following photos will lead to collapse.
Reason:
Failed to ensure directory: /storage/sdcard1/Android/data/com.jeemoo.conveniencestore/cache
thanks
