### ISSUE TITLE
instagram: success callback called instead of error callback when native app is not installed

### ISSUE THREAD

**Issue by guykatz** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#430]
hi, my env:
-android 5.1.1
-PGB 3.7.0 (not 5.2.0 cli yet)
-nexus 5
-no native instagram installed
-use latest npm plugin version
when calling shareViaInstagram (......,. success callback, error callback) the success callback is called instead of the error callback. in all other applications, if the app is not installed the error callback is called.
is this an android quirk? a bug? 
thanks!

**Comment by EddyVerbruggen** [comment]
Have you tried calling `canShareVia('instagram'..)` first?

**Comment by guykatz** [comment]
no, I can test it for you but I dont really want to use it as by reading your docs it seems that the input to the canShareVia can be different sometimes depending on the platform and I am trying to be generic. I dont know I i am making sense to you...
let me test this and I will update.

**Comment by EddyVerbruggen** [comment]
It's because of a change in iOS9 where you would get an error if you didn't whitelist the domain. Too much hassle to get right for everyone - I simply advice to use `canShareVia` for Instagram an WhatsApp.

**Comment by guykatz** [comment]
got it. thanks very much for your responses!
