### ISSUE TITLE
chompSMS: Share content is pasted twice

### ISSUE THREAD

**Issue by SebT** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#432]
Hi, I noticed a bug when sharing via the application [chompSMS](https://play.google.com/store/apps/details?id=com.p1.chompsms&hl=fr).

```javascript
window.plugins.socialsharing.share("Message", "Subject", null, "http://google.com");
```
The share content is pasted twiced, the above will share:
> Message http://google.comMessage http://google.com

Instead of just

> Message http://google.com

When I look at the source code I see that the message may be pasted twice when sharing through an SMS app: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/SocialSharing.java#L234-L235

Any idea on how to fix this? Are these 2 lines really necessary?

Tested on: 2 Android 5.X phones

**Comment by EddyVerbruggen** [comment]
Yeah that's exactly the line that causes this. In the past when users shared to SMS they reported an empty message, so that's why the second line was added. I don't know if that's still a problem though..

Are you able to test sms sharing (the default app and hangouts I guess) without that line?

**Comment by SebT** [comment]
Yes. I'll fork, test that and come back to you.

**Comment by SebT** [comment]
Well I forked and removed the line causing issues and it fixes the problem.

I tested on two Android 5.1 devices: basic sms app & hangout work fine.
I'll add a check to disable this line for Android 5+ and do a pull request later.

I'm pretty confident that the line can also be removed for android 4+. Unfortunately I can't test on an Android 4 as I don't have any.
