### ISSUE TITLE
Hard coded content doesn't appear in Share via Facebook 

### ISSUE THREAD

**Issue by ShrinivasKattimani** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#437]
Hi, 
I have my index.html as:

<button class="button" ng-click="shareViaFacebook('Testing Facebook Share...', null, null)">Share on Facebook</button>

and app.js as:

$scope.shareViaFacebook = function(message, image, link) {
        $cordovaSocialSharing.canShareVia("facebook", message, image, link).then(function(result) {
            $cordovaSocialSharing.shareViaFacebook(message, image);
        }, function(error) {
            alert("You need to have Facebook Application installed in your device to perform this action");
        });
    }

when I run this on device, upon tapping 'Share On Facebook', I get to to see the default Facebook status update screen. However, the hard coded content passed as message does not appear. Is this a known issue or am I missing something?

**Comment by EddyVerbruggen** [comment]
Please see the readme.
