### ISSUE TITLE
App submission on Windows Store fails

### ISSUE THREAD

**Issue by osro** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#449]
Just for the note. Windows Store app submission fails on these error.

> UTF-8 file encoding
> Error Found: The UTF-8 file encoding test detected the following errors:

> File plugins\cordova-plugin-x-socialsharing\tests\tests.js is not properly UTF-8 encoded. Re-save the > file as UTF-8 (including Byte Order Mark).

> File plugins\cordova-plugin-x-socialsharing\www\SocialSharing.js is not properly UTF-8 encoded. Re-> save the file as UTF-8 (including Byte Order Mark).

**Comment by EddyVerbruggen** [comment]
Hi, I've removed the file and created a new one - hope that helps!

**Comment by osro** [comment]
Sorry for the late response, but the issue is still there.

I noticed that those files are still missing the Byte Order Mark. By adding the UTF8-**BOM** encoding I got PASS from the Windows Store.

**Comment by EddyVerbruggen** [comment]
Could you add a PR for this perhaps?

**Comment by osro** [comment]
Hmm... now the file encoding passes, but Windows Store validation throws another issue.

> Error Found: The supported APIs test detected the following errors:
This API is not supported for this application type - Api=System.Reflection.ICustomAttributeProvider. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.

That ddl-file seems to belong to the WP8 platform. So I began to wonder why that file is there as I'm building a Windows Universal app which I guess shouldn't even need that file?

Now I took a slightly deeper look of the "windows" platform folder that Cordova generates and I noticed that there is a folder called "plugins" which contains the whole Socialsharing plugin's repository. Is this something that is meant to be there?

**Comment by jmail** [comment]
I will check this later today - this file shouldn't ne attached to windows app. Only wondows phone app

**Comment by osro** [comment]
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/plugin.xml#L82

Hmm... I think the line 82. is the reason why it copies whole src folder to the package(?)

**Comment by AlexandrZl** [comment]
Windows Store validation throws issue for me too.
I have problem with supported APIs.
How it fix?
