### ISSUE TITLE
New lines

### ISSUE THREAD

**Issue by rogercrandall** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#451]
It doesn't seem to work when there are new lines \n or \r in the message.

**Comment by EddyVerbruggen** [comment]
Strip 'em!

**Comment by rogercrandall** [comment]
so there is no way to pass a new line to say FB or twitter

**Comment by EddyVerbruggen** [comment]
I don't know, what have your tried already and which platform is this? Have you Googled for it?
