### ISSUE TITLE
Whatsapp is not open in iOS 9.0 and above version

### ISSUE THREAD

**Issue by narendrajadhav** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#452]
I have used this plugin but with latest version of iOS 9.0 and above whats-app is not open please let me know and suggest me any solution for this.

Thanks

**Comment by vitormalencar** [comment]
i have almost the same problem, but in my case is not display any image when i`m use share with whatsapp

**Comment by oliverlaz** [comment]
Same issue here, the solution was to add 'whatsapp' to the white-listed urls as described [here] (http://stackoverflow.com/questions/30987986/ios-9-not-opening-instagram-app-with-url-scheme).

**Comment by EddyVerbruggen** [comment]
It's in the readme but slightly hidden I admit. If anyone wants to take a stab at making it more obvious then I'd be more than happy to merge a PR.
