### ISSUE TITLE
Sign In to iCloud 

### ISSUE THREAD

**Issue by krisrandall** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#453]
When this plugin is added to a Cordova project and run on iOS8, the iPhone/iPad will throw up a prompt on app startup asking for the Apple ID password.
"
Sign In to iCloud
Enter the Apple ID password for
(your account)
[password]
Cancel | OK
"

Removing the plugin stops this occurring, adding the plugin back in makes it happen.
"cordova plugin add cordova-plugin-x-socialsharing"

**Comment by jmail** [comment]
And what is the problem?
