### ISSUE TITLE
Linebreak / Feed new line

### ISSUE THREAD

**Issue by Esselans** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#457]
Hi!

I'm using this plugin to share with Facebook with Hint so the user can paste a prefill text. In these prefill I need to insert line breaks (think in a **ul** list with its **li** items). I've tried **`\n\r`,`\n`, `<br>`** and so on but nothing seems to work.

Is there a way to do this?

Thanks!

**Comment by EddyVerbruggen** [comment]
I don't know - does Facebook allow that when entering it manually?

**Comment by Esselans** [comment]
No idea. Not a FB user myself. I just made an account to share content from the app I'm working on.

**Comment by EddyVerbruggen** [comment]
Plz Google what you can do with the Fb sharesheet and let me know if there's a bug here.

**Comment by Esselans** [comment]
Ok. I tried again **`\n\r`,`\n`**. Both works seems to be working now on a different project. So this is on my end. Just letting you know that this chars works as line feeders. Great plugin btw.
