### ISSUE TITLE
ByteArrayBuffer  cannot be resolved when compiling SDK 6.0 and API 23

### ISSUE THREAD

**Issue by devshisiyani** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#459]
I have phonegap app which in google play (compiled against SDK 5.0 and AP22).  Some of the functions fails to work on android Marshmallow. 
In eclipse I have changed the compilation to  DK 6.0 and API 23. Now I get the compilation error. ByteArrayBuffer  cannot be resolved. Also using "import org.apache.http.util.ByteArrayBuffer" i get compilation error cannot be resolved. Looks like org.apache.http.util.ByteArrayBuffer has been depreciated. Will you be  fixing this issue and is there a current work around ?

**Comment by demiurga** [comment]
Same issue, but it seams fixed when I updated to newest version.

**Comment by EddyVerbruggen** [comment]
Yeah that's been removed a while ago :+1:
