### ISSUE TITLE
iOs 9.1 not functions decalared

### ISSUE THREAD

**Issue by leovilla89** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#461]
Hi, I'm building in Phonegap Build importing the plugin with this:
&lt;gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />

And the Safari Browser debug returns 'windows.plugins.socialsharing.share is not a function'.

I don't know what I'm doing wrong. But It was working in iOs 8 with the next include code:
&lt;gap:plugin name="nl.x-services.plugins.socialsharing"/></addr>

Thanks

**Comment by jmail** [comment]
There should be 

window.plugins.socialsharing.share

and you got 

windows.plugins.socialsharing.share
