### ISSUE TITLE
TypeError: $cordovaSocialSharing.shareViaInstagram is not a function

### ISSUE THREAD

**Issue by jazzwhistle** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#462]
Hi, I'm using ionic + cordova and the plugin is working perfectly except for shareViaInstagram which gives me the error in the title.

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/573e409/README.md makes no mention of this function... but this does:

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

I have version cordova-plugin-x-socialsharing 5.0.7 "SocialSharing" installed.

Thanks

**Comment by jmail** [comment]
which platform are you having issue with?

**Comment by EddyVerbruggen** [comment]
@jazzwhistle is this actually supported according to ngCordova?

**Comment by jazzwhistle** [comment]
Hi Eddy, I assumed it was because I found it here initially: http://ngcordova.com/docs/plugins/socialSharing/

The shareViaInstagram function is not mentioned there though...

Thanks

**Comment by jazzwhistle** [comment]
That's no big deal really... more importantly I keep getting random SIGBART crashes on iOS in

 [[self getTopMostViewController] presentViewController:activityVC animated:YES completion:nil];
