### ISSUE TITLE
Plugin is not loaded in the phonegap emulator

### ISSUE THREAD

**Issue by AlmogCohen** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#466]
Hi,

I'm trying to use the plugin without success.
I followed all the steps to install the plugin with cordova plugin install from the project's README but yet, whenever I try to use the plugin, `window.plugins.socialsharing` is null.
The "brother" `plugin, window.plugins.insomnia` just works great.

I followed all problems checks here with no problems:
http://stackoverflow.com/questions/26654231/cordova-plugins-not-working

Does anybody guess what is the problem? Any ideas how to solve it?

**Comment by jmail** [comment]
Which platforms you having issues with?

**Comment by AlmogCohen** [comment]
I dont fully understands the phonegap inner working mechanizms but maybe what I found is related to the problems.
In the first line of the SocialSharing.js I have 
`cordova.define("cordova-plugin-x-socialsharing.SocialSharing"...`

and in the config.xml automatic config defined by the git project I have
```
      <feature name="SocialSharing">
        <param name="android-package" value="nl.xservices.plugins.SocialSharing" />
      </feature>
```

Maybe the difference here is the root of all evil?

**Comment by jmail** [comment]
am I correctly assume form your code that we are talking about Android?

**Comment by AlmogCohen** [comment]
Yup, android

**Comment by jmail** [comment]
If you added plugin localy via cli - can you please remove platform and add it again? 

In case of plugman try to reinstall plugin. 

Please check your app via Google Chrome inspect and try to find if there is any file missing on loda.

**Comment by AlmogCohen** [comment]
Removed the platform and installed again, same problem.
I find the problem when I'm using the emulator and view the app on my Nexus 5

No 404 in the chrome or something, but there are no plugins available at all when I'm using the web version. Is it a problem?

**Comment by AlmogCohen** [comment]
Oops, it seems that I have to run the browse through cordova :)
Now actually I see the insomnia and socialsharing inside the window.plugins

**Comment by jmail** [comment]
Good for you :)

**Comment by AlmogCohen** [comment]
Hmmm, I think that this is still an issuee, it won't work for other people too when trying the plugin. I dont know the problem but the issuee shouldn't be closed.

**Comment by AlmogCohen** [comment]
The bug is still there....
