### ISSUE TITLE
Error: undefined is not an object (evaluating 'c.plugins.socialsharing')

### ISSUE THREAD

**Issue by PLopezD** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#469]
Hi,
Getting the same issue as previously mentioned. (it says c.plugins because the code is minified) I have the plugin working in a toy app but when I try using it in production it breaks. I have cordova.js and socialsharing.js  in my index.html. Any other tips?

**Comment by EddyVerbruggen** [comment]
Yeah, try first without minifying. Note that cordova.js searches for a cordova_plugins.js file, perhaps that's minified/inlined as well?

**Comment by smartyw** [comment]
I'm getting this error on iOS but not on Android:

```
TypeError: undefined is not an object (evaluating 'window.plugins.socialsharing') 
```

cordova plugin indicates the plugin is installed:

```
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
```
Any ideas? Works great on Android so I'd hate to have to hide the option from iOS users.

Thanks

**Comment by EddyVerbruggen** [comment]
Hard to tell. Try removing the platform folder first. But could be many things.

**Comment by smartyw** [comment]
To be clear, your advice is to remove the social sharing plugin, remove the cordova ios platform completely and reinstall it and then reinstall the plugin?

If it's hard to tell, what information can I provide which would make a proper diagnosis possible?

**Comment by EddyVerbruggen** [comment]
Have you tried doing those things?

**Comment by smartyw** [comment]
I have now.... just wanted to make sure I understood the sequence of steps you were recommending.

And..... yep, that's fixed it :-)

Thanks very much!

**Comment by EddyVerbruggen** [comment]
Awesome, glad I was able to help while driving shotgun in the Bulgarian mountains :)

**Comment by smartyw** [comment]
Brilliant. I too have given technical support from a laptop perched precariously on my knee, as the passenger in a car speeding through mountains... Scotland in that case!

Nice work by the way. Thanks for this. Very useful indeed.

**Comment by EddyVerbruggen** [comment]
Haha us developers are so weird. Cheers!

**Comment by smartyw** [comment]
I think we're all a tiny bit obsessive! Adios!
