### ISSUE TITLE
window.plugins undefined

### ISSUE THREAD

**Issue by leandrolimasi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#472]
Hi ,

I'm using the cordova CLI 5.1.1 with jQuery Mobile.

WHEN I try to USE the plugin , I have the undefined error in COMMAND "window.plugins" and no action fired.

Why ?

**Comment by EddyVerbruggen** [comment]
Why? A few possibilities:
- You're deploying to a companion app
- You didn't include a reference to `cordova.js`
- You invoked the plugin before `deviceready` fired
- You're testing in a browser instead of an emulator or device
- You have a JS error on your page preventing plugins to load

**Comment by leandrolimasi** [comment]
tanks for reply @EddyVerbruggen 

But, 

which would be a companion app?? would be Entreprise builds?

cordova.js is automatic include when use cordova build right? I'm use a cordova build.

I made no treatment for the device ready because I'm calling the function in the click of a button which I believe is reder after the device is ready.

I'm testing in device, not emulator. IOS e ANDROID are undefined in window.plugins command.

I'm not a any error in javascript.

more any help?

**Comment by EddyVerbruggen** [comment]
Let me ask more explicitly this time: can you please share your code with me? An email to eddyverbruggen at gmail dot com would be ok.
