### ISSUE TITLE
How do I whitelist Facebook

### ISSUE THREAD

**Issue by philecom** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#473]
I am currently using the plugin and it works great. I have never had any issue installing it and using it. 
But there is this issue i am facing. whenever I share photo to Facebook with the plugin everything works well, but when I visit Facebook in my browser it temporally prevent me from carrying certain actions like commenting on or share others post with the warning that I am using harmful browser extension. I have to restart my browser then everything will be ok. 
It only happens when i share photo to Facebook through the plugin.
I am thinking there is a way I can solve this, maybe by white-listing Facebook.

So where do i place this code.

<key>LSApplicationQueriesSchemes</key>
<array>
  <string>fb</string>
</array>

Thank You.

**Comment by EddyVerbruggen** [comment]
Very odd issue, I can't imagine the whitelist has something to do with it, but it needs to go into your .plist. If you're building with build.phonegap.com then you can add it in config.xml (search for the exact usage on google plz)
