### ISSUE TITLE
Unable to invoke social media.

### ISSUE THREAD

**Issue by Defaultacc9** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#474]
Hi Guys, 
I am trying to share content from cordova[phonegap] app to various social media platforms like facebook/whatsapp/hike/emails/and so on.... 
I tried with following plugin but was unsuccessful to implement it. 
https://github.com/Telerik-Verified-P... 

https://github.com/EddyVerbruggen/Soc... 
I have added above plugin to my application and followed all the steps as instructed over there but its not working for my Android.

Steps I have done:
1) Created cordova application through CLI.
2) Added Android Platform
3) Added this socialSharing Plugin through CLI
4) pasted share sheet html in index.html
5) Build deployed but the buttons not working
6) tried with "Sharing directly to.." sheet but not working.

@EddyVerbruggen  Please help!

**Comment by EddyVerbruggen** [comment]
It's guessing without your code, so here's my first guess: do you have the whitelist plugin installed and is there a CSP metatag preventing inline scripts in your index.html?

**Comment by Defaultacc9** [comment]
Thanks! @EddyVerbruggen  for your prompt response.
Whitelist plugin is installed and CSP meta tag is also present in index.html.

**Comment by Defaultacc9** [comment]
Its working!!!!!
What a great plugin!!!!!
Thanks @EddyVerbruggen!!!!!

**Comment by EddyVerbruggen** [comment]
Awesome!
