### ISSUE TITLE
ios gmail: socialsharing.share('message', 'subject') shows message as subject

### ISSUE THREAD

**Issue by djangojack** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#477]
ios gmail: socialsharing.share('message', 'subject') shows message as subject 

is this the expected behavior?

**Comment by AntonAI** [comment]
Any update on this? Still happening with latest build...

**Comment by EddyVerbruggen** [comment]
see #375

**Comment by BassamHabash** [comment]
Any update on this? @EddyVerbruggen  ?
