### ISSUE TITLE
Windows package validation fails on "Supported API test"

### ISSUE THREAD

**Issue by zabojad** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#478]
When running the package validation, it fails on the "Supported API test":

Supported API test
FAILED

Supported APIs

•Error Found: The supported APIs test detected the following errors:◦This API is not supported for this application type - Api=System.Reflection.ICustomAttributeProvider. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverter. Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Xml.XmlDateTimeSerializationMode. Module=SYSTEM.XML, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Reflection.MemberTypes. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.DBNull. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Reflection.Binder. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Reflection.ParameterModifier. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.DescriptionAttribute. Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverterAttribute. Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.IO.BinaryWriter.Close. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.IO.BinaryReader.Close. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Char.ToString(System.IFormatProvider). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Xml.XmlConvert.ToString(System.DateTime,System.Xml.XmlDateTimeSerializationMode). Module=SYSTEM.XML, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Guid.ToString(System.String,System.IFormatProvider). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.IO.TextReader.Close. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.IO.TextWriter.Close. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.DBNull.Value. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverter.CanConvertTo(System.Type). Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverter.ConvertToString(System.Object). Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Convert.GetTypeCode(System.Object). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type). Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverter.CanConvertFrom(System.Type). Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverter.ConvertFrom(System.Object). Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Type.EmptyTypes. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Reflection.ICustomAttributeProvider.GetCustomAttributes(System.Type,System.Boolean). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Type.GetProperty(System.String,System.Reflection.BindingFlags,System.Reflection.Binder,System.Type,System.Type[],System.Reflection.ParameterModifier[]). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Type.GetMember(System.String,System.Reflection.MemberTypes,System.Reflection.BindingFlags). Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.Reflection.MemberInfo.get_MemberType. Module=MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.DescriptionAttribute.get_Description. Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.
◦This API is not supported for this application type - Api=System.ComponentModel.TypeConverterAttribute.get_ConverterTypeName. Module=SYSTEM, PUBLICKEYTOKEN=7CEC85D7BEA7798E. File=Newtonsoft.Json.dll.

•Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Phone Store apps violates the Windows Phone Store certification requirements. 

•How to fix:  Review the error messages to identify the API that is not part of the Windows SDK for Windows Phone Store app. Please note, C++ apps that are built in a debug configuration will fail this test even if they only use APIs from the Windows SDK for Windows Phone Store apps. 

Any idea how to workaround this ?

**Comment by zabojad** [comment]
Here is a screenshot of the problem:

![error_validation](https://cloud.githubusercontent.com/assets/1238030/11641025/43fcb2d4-9d36-11e5-9093-0d972abcf72a.png)

**Comment by zabojad** [comment]
@EddyVerbruggen is there a possibility of paid support to get this fixed faster ?

**Comment by EddyVerbruggen** [comment]
@zabojad It's more a problem of not having a VS environment currently. Can you update from the master repo and try it again though? I made some small changes..

**Comment by zabojad** [comment]
Hey Eddy ! I confirm that commit 4263d1a fixed the problem. You can close this issue, thank you!

**Comment by EddyVerbruggen** [comment]
Pfew, great! Thx for the test.
