### ISSUE TITLE
Special characters in Portuguese are displayed as invalid characters.

### ISSUE THREAD

**Issue by FernandoMorais** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#484]
Hi!

I'm trying to share a message that has special characters in both message and subject.

My Code:

``` javascript
window.plugins.socialsharing.share(
            "Estou utilizando o Dicionário e você deveria conhecer ele também!",
            "Dicionário",
            null,
            "http://www..."
        );
```

But, in Android, the message was showed with invalid characters.

Is there something I'm missing?

Regards!

**Comment by Probabit** [comment]
Please be sure your javascript file is encoded as UTF-8.
