### ISSUE TITLE
Crash on iPad 4th generation

### ISSUE THREAD

**Issue by kimuraeiji214** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#485]
I installed the plugin and tested on iPad 4th generation(Retina display).
It's using iOS9.1 and the plugin crashes.

**Comment by EddyVerbruggen** [comment]
That's a bit too little to go on mate. Care to share any more information? How are you using the plugin, what's in the crashlog, ..

**Comment by kimuraeiji214** [comment]
I installed the plugin and used it as follows.

var message = {
        to:      '',
        subject: currentPageTitle,
        text: currentPageTitle,
        url: currentPageUrl
    };

    window.socialmessage.send(message);

And this is the error I got.

2015-12-13 10:55:23.187 QUEERTY[407:145891] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<_UIAlertControllerActionSheetRegularPresentationController: 0x15e357e0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
*** First throw call stack:
(0x26d6985b 0x387aedff 0x2b763b11 0x2b1e75af 0x2b1e54cf 0x2b14515d 0x2b150af3 0x2ae90bc1 0x26d2c091 0x26d2a387 0x26d2a7c5 0x26c7d0d9 0x26c7cecd 0x2fe64af9 0x2af062dd 0x5ef8b 0x38efc873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by EddyVerbruggen** [comment]
`socialmessage` is not this plugin, please head over [here](https://github.com/leecrossley/cordova-plugin-social-message)
