### ISSUE TITLE
"share" method doesn't work to share a link on facebook

### ISSUE THREAD

**Issue by cess2014** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#486]
Hi Eddy,
I'm using your plugin, but I need to share a link in any social network selected by user, but in facebook case it doesn't work.
I'm tried with this code.

window.plugins.socialsharing.share(null, null, null,'http://www.google.com/');

But in the facebook case cannot display the url.

I use these:
Android 4.4.4
cordova-plugin-x-socialsharing 5.0.7
Cordova version: 5.0.0

Can you help me please?

**Comment by EddyVerbruggen** [comment]
So that link gets shared to twitter, sms, etc? What happens op facebook exactly? Perhaps you want to share the actual code with me?

**Comment by cess2014** [comment]
The link is shared with whatsapp, hangout, sms, etc. but in facebook doesn't working, no copy the url, then cannot share the url with facebook.
I'm using angularjs, then my code are similar,
$scope.methods = {
  sharingFacebook: function() {
          window.plugins.socialsharing.share(null, null, null, http://ww.mostaza.menu/');
  }
};

**Comment by sergio-aranda-tierconnect-com** [comment]
@EddyVerbruggen Hi can you help me on this error? You have any idea why this error?

**Comment by cess2014** [comment]
@EddyVerbruggen Hi can you help me on this error? You have any idea why this error?

**Comment by EddyVerbruggen** [comment]
Perhaps the Facebook app has trouble loading a .menu page, or it times out while loading the site (because it seems a little slow to respond to me) and just ignores it. Who can tell, it's Facebook so it's a black box really.

Changing the url to `http://goo.gl/3MRbak` (a shortened version I created) the link is loaded btw.
