### ISSUE TITLE
Content Security Policy keeps me from sharing anything.  connect-src the solution?

### ISSUE THREAD

**Issue by jakub94** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#489]
When I try to share something out of my cordova project on android or ios I get the following console output:
Refused to execute inline event handler because it violates the following Content Security Policy directive: "default-src * data: gap: https://ssl.gstatic.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

I was able to work around this deleting the meta tag from the index page:
<meta http-equiv="Content-Security-Policy" content="default-src * data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src * 'unsafe-inline'; media-src *">

Though is not a good solutions since I want the Content Security Policy to be present in my application.
Searching the Web I found something which might help me, the 
" connect-src=" " " attribute which I can use in this meta tag. 

Though I do not find any information on what values to use in there in order to make my cause work (sharing text to any application installed on the device).

Has anybody done this before and could give me a hint on how to achieve this? It would be greatly appreciated.

**Comment by EddyVerbruggen** [comment]
I'm guessing you have some inline script in `index.html`? Move it to your js file and you'll be fine.

Please ask this kind of questions on SO because it's not really related to this plugin.

**Comment by jakub94** [comment]
Thank you for your quick answer. I do not have any inline script in my index.html file. All scripts are stored in separate files. I thought it was related to the plugin since I wanted to know what "exceptions" I need to to the Content Security Policy when using THIS plugin.

**Comment by EddyVerbruggen** [comment]
OK, if you figure it out plz post it here as well.
