### ISSUE TITLE
Problem sharing facebook originated image (which is located on fbcdn)

### ISSUE THREAD

**Issue by tomermes** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#491]
Hi Eddy, I'm using your plugin and it is great, while sharing images from most locations works perfectly,
using with this type of url (which is not a broken link on a browser) acts as if it was a broken url:

https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xfl1/v/t1.0-9/s720x720/12369239_1005740372801097_6977151939319838373_n.jpg?oh=024ccee4b7e30de4ee76914dc33d0061&oe=56E619EC&__gda__=1461592839_fb67db7be2a68582135c9d5d7ba0025a

Any ideas why?
Thanks!

**Comment by EddyVerbruggen** [comment]
The funny thing is: this is how the Github email notification showed up in my mailbox:

<img width="556" alt="screen shot 2015-12-19 at 17 31 55" src="https://cloud.githubusercontent.com/assets/1426370/11914054/feb0523c-a675-11e5-816b-f93c9f40cfae.png">

It looks like those `__x__` underscores are markdownified to __bold__ syntax. Has nothing to do with this plugin as far as I can tell (as the github notification mail is parsed similar by gmail).

**Comment by EddyVerbruggen** [comment]
Tip: use an URL shortener service to get around this issue.

**Comment by tomermes** [comment]
Thanks, but What about that link:

https://scontent-fra3-1.xx.fbcdn.net/hphotos-xfl1/v/t1.0-9/s720x720/12369240_1005740382801096_8455252032445198356_n.jpg?oh=4f4b3ac089530379b9d7eab7fa632c4c&oe=56E15D6C

Also not working, and without the "__gda__" potential issue.
