### ISSUE TITLE
IOS Newline character problem

### ISSUE THREAD

**Issue by okanari2** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#492]
When sharing text on IOS, whatsapp is preferring <br> as a new line seperator. But email client accepts \n. So this makes a conflict in the text which prevents sharing a text with new line character successfully.

**Comment by Malkiat-Singh** [comment]
Yes Same issue at my end :(

**Comment by EddyVerbruggen** [comment]
Use the `shareVia*` functions with sep content. Otherwise you'll need to do a feature request with WhatsApp to support `\n`..

**Comment by Malkiat-Singh** [comment]
I am using the Share via share sheet so cannot use the shareVia* ... Is There any way in c-obj/java code that detect the selected option 
if is whatsApp then replace '\n' with '<br/>'
