### ISSUE TITLE
5.0.8 version will cause winphone build fail from PGB cli-5.2.0

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#496]
hi @EddyVerbruggen 
5.0.8 version will cause winphone build fail from PGB cli-5.2.0
all log right here
![2015-12-31_113342](https://cloud.githubusercontent.com/assets/5110085/12060803/5eeb3de8-afb2-11e5-99db-17ebc462fa6e.jpg)
http://justpaste.it/q2cu

but 5.0.7 is ok for all platform

**Comment by henrikhermansen** [comment]
I have the same issue with 5.0.8. I can happily provide [my log](http://pastebin.com/TV4uy3jB), but I don't think it adds anything to what @bau720123 provided.
5.0.7 works fine.

**Comment by EddyVerbruggen** [comment]
Thanks guys - 5.0.9 finally fixes this issue. Available on npm, so if you did not pin the plugin version in `config.xml` triggering a rebuild should automatically pick up the latest version and fix the problem.

**Comment by bau720123** [comment]
problem solved
thanks @EddyVerbruggen
