### ISSUE TITLE
Adding a "via field" at the end of the tweet

### ISSUE THREAD

**Issue by hakikihacioglu** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#498]
Hi,

I want to add a via @accountname at the end of the tweet -after the url-

is ist possible? 

Thank you

**Comment by EddyVerbruggen** [comment]
Nope, you should add it to the message manually, there is no separate field.

**Comment by hakikihacioglu** [comment]
Fastest answer ever:-)

Thank you
