### ISSUE TITLE
Share message on Android

### ISSUE THREAD

**Issue by alejandrocao** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#50]
Hi Eddy,

Why is not possible to share a message or text in Android? When you do share is essential to share text, especially on Facebook. What are the alternatives to solve this? What plans are there to add this functionality? 

Thanks in advance, 
Alejandro

**Comment by mutkumar** [comment]
Hi Eddy,
    Is there any way to share the message directly to Facebook Messenger?

**Comment by Muthukumar28041990** [comment]
Hi Eddy,
Is there any way to share the message directly to Facebook Messenger?

**Comment by samuelralak** [comment]
@Muthukumar28041990 and @mutkumar the following piece of code worked for me:
```
window.plugins.socialsharing.shareVia('com.facebook.orca', 'Awesome message', null, null, null, function(){
            console.log('share ok')
        }, function(msg) {
            alert('error: ' + msg)
        });
```

**Comment by muhzi4u** [comment]
@samuelralak Is it working in ios?

**Comment by samuelralak** [comment]
@muhzi4u I haven't tried it out on iOS so am not sure. I would advise that you find out how the Facebook Messenger package is named on iOS; if its the same then it should work, if not then try replacing `com.facebook.orca` with the package name provided for Facebook Messenger in iOS.
