### ISSUE TITLE
base64 attachment doesn't work in Windows

### ISSUE THREAD

**Issue by jdnichollsc** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#500]
Hi guys, 

See please the error: http://screencast.com/t/N0Sr2G3nJ

Thanks in advance! :+1:

**Comment by jdnichollsc** [comment]
¿Can I help you? If you explain me the code, I'll try :)

**Comment by EddyVerbruggen** [comment]
As you found out, sharing a base64 encoded file is not currently supported on the windows platform with this plugin. Is there a way you can turn in into a regular attachment?

**Comment by jdnichollsc** [comment]
The current code is WinJS? If you want I can investigate to support a base64 encoded file :)

**Comment by EddyVerbruggen** [comment]
Yes - that would be awesome and really helpful for others!

**Comment by jdnichollsc** [comment]
Maybe, we need the following: 

1. Convert the base64 string to BitmapImage: http://stackoverflow.com/questions/13529301/load-bitmapimage-from-base64string
2. Convert BitmapImage to Storage File http://webdesignpluscode.blogspot.com.co/2015/04/how-to-convert-bitmapimage-to-storage.html

What do you think? :dancers:

**Comment by jdnichollsc** [comment]
Other example http://sanjeev.dwivedi.net/?p=39 :100:

**Comment by EddyVerbruggen** [comment]
Yes, looks promising!

**Comment by jdnichollsc** [comment]
Hi man! Do you have any example to get the extension from the base64 string? :octocat:

**Comment by jdnichollsc** [comment]
Hi man!
I can attach the file, but I don't know the way to assign the name to the file => https://gist.github.com/jdnichollsc/619f9db2c3e61667ea35

**Comment by jdnichollsc** [comment]
mmm saving in a temporary folder => https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/windows/EmailComposerProxyImpl.js

And below get the IStorageItem :)

What do you think?

**Comment by jdnichollsc** [comment]
Solved! See please my pull request! One question my friend... in iOS works the base64?

Regards, Nicholls

**Comment by EddyVerbruggen** [comment]
Hey @jdnichollsc supercool!

iOS should be fine, there is an example in the readme.

**Comment by jdnichollsc** [comment]
Hi @EddyVerbruggen, thanks for the merged!

Can I get this update using the Cordova CLI?

**Comment by EddyVerbruggen** [comment]
`cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin` will always give you the latest from the master branch.

**Comment by jdnichollsc** [comment]
Thanks! :dancers:
