### ISSUE TITLE
LinkedIn sharing via plugin

### ISSUE THREAD

**Issue by catimos** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#501]
Does the plugin allow LinkedIn sharing on iOS ? There are icons for twitter , Facebook but not for linked when we do 
    'window.plugins.socialsharing.share'

**Comment by EddyVerbruggen** [comment]
AFAIK it does, do you have the app installed?

**Comment by catimos** [comment]
Yes the linked app is installed on iOS but the plugin does not show linkedin icon for sharing .

**Comment by EddyVerbruggen** [comment]
Seems like they dropped the share widget: https://community.linkedin.com/questions/399874/ios-linkedin-activity-missing.html

Can't help it on my side if they don't support it..

**Comment by catimos** [comment]
Ok, on iOS,  the linkedin share widget appears on the plugin menu 'window.plugins.socialsharing.share' . Choosing linkedin from there works fine. 
But how do i share directly to linkedin just like we have shareViaFacebook, shareViaTwitter  how to do shareViaLinkedIn   for iOS

**Comment by ppetree** [comment]
There's no reason this should be closed... at least give us a work around.

**Comment by EddyVerbruggen** [comment]
@ppetree I'm not sure what you mean - LinkedIn is part of the share widget (if the app is installed), right?

**Comment by ppetree** [comment]
Just because it's installed doesn't mean it's on the share widget, you actually have to give it permission first and then it appears.

However, it still doesn't work and there's no error reporting at all.

```
function LinkedIn()
{
  alert("Calling LinkedIn!");
  window.plugins.socialsharing.shareVia('LinkedIn', 'Message via TapToReport', 
                                        null, 
                                        null, 
                                        null, 
                                        function(){alert("Shared to LinkedIn OK")}, 
                                        function(msg) {alert('error: ' + msg)});
}
```

The above code will produce the initial alert() and then nothing.  No LinkedIn share widget interface, no success callback, no failure call back nothing.  As @catimos said...

**Comment by EddyVerbruggen** [comment]
LinkedIn is not one of the apps you can share directly to - you have to use the share widget. If you want to share directly to LinkedIn look elsewhere, or figure out how to do it and send a PR.

**Comment by ppetree** [comment]
So, while you're addressing issues, would you please document the canShareVia('xxx', 'msg', null, null, null, success, failed)

I'll root around on the LinkedIn issue and see what I can find... it would be a great win for my next app.

**Comment by fouzko** [comment]
Same problem hm hmm

**Comment by alebret** [comment]
Try this.

window.plugins.socialsharing.shareVia(**'com.linkedin.android'**, 'Message via TestTube', 
            null, null, null, 
            console.log("Shared to LinkedIn OK"), 
            console.log('error')
        );

**Comment by alebret** [comment]
Try this.
window.plugins.socialsharing.shareVia('com.linkedin.android', 'Message via TestTube', 
            null,  null, null, 
            console.log("Shared to LinkedIn OK"), 
            console.log('error')
        );
