### ISSUE TITLE
Facebook share problem

### ISSUE THREAD

**Issue by phuongtailtranminh** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#502]
Hi,

I'm trying to use facebook share function but got this error:

I've included this code in <body>:

    <button onclick="window.plugins.socialsharing.shareViaFacebook('Message via Facebook', null /* img */, null /* url */, function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">msg via Facebook (with errcallback)</button>

![fb_share_prob](https://cloud.githubusercontent.com/assets/12473996/12268051/b0811d24-b97d-11e5-9e9d-c837d8f54dd3.png)

**Comment by EddyVerbruggen** [comment]
Seems like Facebook is not installed..

**Comment by phuongtailtranminh** [comment]
Oh! I've just figured out that. Thank you, but is there any way that don't need Facebook installed?

**Comment by EddyVerbruggen** [comment]
Yeah, check if the app is installed (can be done with this plugin, or the AppAvailability plugin) - if not, redirect to the Facebook website.

**Comment by byelik** [comment]
> Yeah, check if the app is installed (can be done with this plugin, or the AppAvailability plugin) - if not, redirect to the Facebook website.

Hi, how exactly I can redirect to the Facebook website?
