### ISSUE TITLE
Social sharing js shareViaFacebook not working in window phone

### ISSUE THREAD

**Issue by cl-sah** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#504]
I have used SocialSharing.js plugin for share link in my phonegap app(Window Phone). Some function working and some not. I cannot share link direct on facebook. Example are below:-

Working:-

`<button onclick="window.plugins.socialsharing.share(null, null, null, 'http://www.x-services.nl')">link only</button>`

Not working:-

`<button onclick="window.plugins.socialsharing.shareViaFacebook('Message via Facebook', null /* img */, null /* url */, function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">Direct Fb link</button>`
 //when click on 'Direct Fb lin' button, it show error message i.e, Invalid action.

**Comment by EddyVerbruggen** [comment]
Correct, see this: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#4b-usage-on-windows-phone
