### ISSUE TITLE
Cannot read property 'share' of undefined

### ISSUE THREAD

**Issue by ankatimko** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#505]
Hello!
I try to use this plugin to share content into social media and I have this error - Cannot read property 'share' of undefined .
I think I've installed the plugin correctly and it's being recognized, but still doesn't work.

I use buttons as shown in usage 
<button onclick="window.plugins.socialsharing.share('Message only')">message only</button>
<button onclick="window.plugins.socialsharing.shareViaFacebook('Message via Facebook', null /* img */, null /* url */, function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">msg via Facebook (with errcallback)</button>	</center>

Can anyone help?

**Comment by EddyVerbruggen** [comment]
Have you checked already open issues? [here you go](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/search?q=Cannot+read+property+%27share%27+of+undefined&type=Issues&utf8=%E2%9C%93)
