### ISSUE TITLE
Class not found?

### ISSUE THREAD

**Issue by AljosaH** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#509]
Hi
I'm able to install the plugin with Cordova CLI:
cordova plugin add https://github.com/Telerik-Verified-Plugins/SocialSharing
(By the way: plugin link form 'official' instructions is not working. "cordova plugin add cordova-plugin-x-socialsharing" returns error 404.)
After that the plugin is in my "plugins" map as it should be.

I add simple button from examples:
\<button onclick="window.plugins.socialsharing.share('Message only')">message only\</button>

Nothing happens and I get error message in console:
The injected error callback of 'share' received: "Class not found"
(file SocialSharing.js, line 101)

Any ideas? I have a feeling it's something trivial.
Thanks for your help.

**Comment by EddyVerbruggen** [comment]
Please share your project with me.

You are aware you're using the version of a fork, not this repo?

**Comment by AljosaH** [comment]
I'm sorry, I'm not the owner of the project, so unfortunately I can't share it.

How should I install this repo through Cordova CLI? As mentioned, "cordova plugin add cordova-plugin-x-socialsharing" does not work (Server error 404).
I also tried "cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git" and the plugin was installed, but it also ended with the above error: The injected error callback of 'share' received: "Class not found"

**Comment by EddyVerbruggen** [comment]
If that command fails please update your cordova cli as it should work just fine. It retrieves the plugin from npm.

If you need me to look at your code, reproduce this in a new small app.

**Comment by AljosaH** [comment]
Indeed, that solved the issue - I updated the CLI, added plugin in it worked. Thanks.

**Comment by mohsin-ahead** [comment]
Hi,

I am facing the same issue, I tried to add this plugin manually and through CLI but no luck, also I updated my CLI but still saying "The injected error callback of 'share' received: "Class not found""

**Comment by devahernandez** [comment]
hi, I have the problem of Class not found

this my info
Cordova CLI: 6.5.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.0.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 1.0.1

This is the error in the browser
Uncaught TypeError: Cannot read property 'addConstructor' of undefined
    at SocialSharing.js:123

**Comment by josefbernadi** [comment]
i have same issue.
i use telerik platform to build an apps. i try both automatic and manual installation but not working.
the error message show "class not found".
i use SocialShare version 5.1.1

what did i missed?

[socialshare.try1.zip](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/files/1158210/socialshare.try1.zip)

**Comment by pookdeveloper** [comment]
The same problem.. any solution ? Whats the correct version for cordova thats work ?
