### ISSUE TITLE
Tweeting a base64 image

### ISSUE THREAD

**Issue by scotthooker** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#51]
I'm trying to achieving tweeting a screenshot of the app page. I.e. let someone share a snapshot of the html on the page. I've managed to work out the first bit by generating a canvas of some html, converting the canvas to an image. 

I just need to attach that image to the tweet.

Do you think this is achievable?

**Comment by hoongoon86** [comment]
+1 for this answer.
