### ISSUE TITLE
Cordova social sharing dynamic content

### ISSUE THREAD

**Issue by ezzuah** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#518]
I've got the cordova social sharing plugin which allows me to share info on social media to my friends. But i'm finding it difficult to make the info sent dynamic and it always have to be static.
What i want to achieve its there's an info i load in a div called `"data"` with ajax and i want that information loaded in the div `data` to be the one shared on the social media
below its the static info.
    <button class="invite" data-role="none" onclick="window.plugins.socialsharing.share('Static info')">Share Message with a Friend</button>
Please how do i make it dynamic.
And another i've notice its at times which you in put information that is having an apostrophe('). it doesn't work

**Comment by EddyVerbruggen** [comment]
Please use StackOverflow for a question like this.

**Comment by mzrokz** [comment]
@ezzuah Have you got the solution
