### ISSUE TITLE
I am fresh on Cordova plugin

### ISSUE THREAD

**Issue by tailerang** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#519]
I create apps on this [ https://build.phonegap.com/apps/ ]
1 ) i have add this code to config.xml already.
     < gap:plugin name="nl.x-services.plugins.socialsharing" / >
2 ) I have linking JavaScript file 
     SocialSharing.js
3 ) I try to test all button also no effect
     < button onclick="window.plugins.socialsharing.share(null, null, null, 'http://www.x-services.nl')">link only< /button >
     < button onclick="window.plugins.socialsharing.shareViaFacebook('Message via Facebook', null /* img */, null /* url */, function() {console.log('share ok')}, function(errormsg){alert(errormsg)})">msg via Facebook (with errcallback)< /button >
4 ) than i debug at computer 
     show me this error [ window.plugins is undefined ]
Can u teach me how my next step?
Thank you

**Comment by EddyVerbruggen** [comment]
Sorry, this is a question you should ask on stackoverflow. It's not related to this specific plugin.
