### ISSUE TITLE
is this plugin compatible for bb10?

### ISSUE THREAD

**Issue by deryfebriantara** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#521]
#I'm using ionic to build a hybird mobile apps and I build an android app this plugin work like a charm, then I build in bb10 platform, when I using 
```
<button onclick="window.plugins.socialsharing.share(null, null, 'https://www.google.nl/images/srpr/logo4w.png', null)">image only</button>
```
it output  
```
The injected error callback of 'share' received: undefined
```
same output when I use shareVia and canShare, sorry for stupid question. thanks in advance 
-dery

**Comment by EddyVerbruggen** [comment]
I think you've answered your own question. It's  not.
