### ISSUE TITLE
Invalid Version: undefined (error during installation)

### ISSUE THREAD

**Issue by alokjain-lucky** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#528]
![screen shot 2016-02-12 at 12 38 38 pm](https://cloud.githubusercontent.com/assets/5526402/13000943/ac903be8-d186-11e5-877a-2da5ecd0482a.png)

----

**system information:**

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by EddyVerbruggen** [comment]
So remove and then add it?

**Comment by alokjain-lucky** [comment]
Still same error.

**Comment by EddyVerbruggen** [comment]
Try a new app, then add the plugin. It's a bit impossible for me to fix this CLI install error.

**Comment by alokjain-lucky** [comment]
Upgrading Cordova solved the issue.
