### ISSUE TITLE
shareFacebook / shareViaFacebookWithPasteMessageHint (ios9)

### ISSUE THREAD

**Issue by igorbrandao18** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#529]
Hello , I'm having trouble sharing by facebook . I saw that in your plugin it's all ok , but when I go to share content through Facebook or image and not text are going . so this problem is occurring in ios9 because in relation to Android and other devices are all ok . an answer to this problem ?

**Comment by Trimud** [comment]
Hello,

We just solved the same issue on our app. Turns out that if the URL that is going to be shared is not valid URL the sharing function fails on iOS.

`vm.share = {
					'networks': ['facebook'],
					'message': item.title,
					'subject': item.category.title,
					'file': item.img,
					'link': item.source,
					'toArr': ['some@mail.com'],
					'bccArr': [],
					'ccArr': [],
					'phone': '098765432'`

'link': item.source was returning string instead of URL. There was no problem on Android however.

**Comment by EddyVerbruggen** [comment]
I'm not sure what the problem is here, but if it's that no text is prefilled when sharing to Facebook then please check the readme.
