### ISSUE TITLE
Special chars on Iphone

### ISSUE THREAD

**Issue by hakikihacioglu** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#530]
Hi,

i have problems with only some special characters, when used in title and only on IOS. These are ışğ which are used in turkish.

When I use other special chars from other languages like çéîü which are used in german or french, no problems at all.

And the problem occurs only on IOS. Android works fine. What can be the reason?

Thank you.

**Comment by EddyVerbruggen** [comment]
Can you try adding `<meta charset="utf-8" />` to your html file?

**Comment by hakikihacioglu** [comment]
it is already set to utf-8 :(

**Comment by EddyVerbruggen** [comment]
Which title are you referring to exactly? A complete example will help.

Thx!

**Comment by hakikihacioglu** [comment]
For example:
html +=  "<button onclick=\"window.plugins.socialsharing.shareViaFacebook('" + node.title + "', null, '" + node.path + "');\">";

I used your plugin, in 2 Adroid Apps and in 1 Iphone App, which work correctly. This time, as I have already written, i am making use of 3 more special chars - ışğ - , which only appears in turkish titles.
When I delete those chars, the plugin works as expected. My titles are from an ajax request to 

https://www.zamanfrance.fr/view-mobile-frontpage

Really appreciate your hepl. Thank you very much

**Comment by EddyVerbruggen** [comment]
I just tried again with my device and simulator, all works fine:

<img width="374" alt="screen shot 2016-02-17 at 20 34 59" src="https://cloud.githubusercontent.com/assets/1426370/13122188/16894b88-d5b6-11e5-937d-2176091e54ec.png">

But only with that utf-8 meta tag AND my index.html file is utf-8 encoded. Perhaps you editor has adjusted its encoding?

**Comment by hakikihacioglu** [comment]
My xcode projects configuration for encoding is set to utf-8. And I can not explain why other special chars are working. Maybe there is another configuration for language settings. I don't know. I will have to take a deeper look.  At least I now know, that it is something which normally works.

Thank you very very much for your help.

**Comment by EddyVerbruggen** [comment]
I hope you can figure it out! Good luck.

Perhaps as a test you can try to create a cordova project with the cli and never touch it with xcode...
