### ISSUE TITLE
Facebook is not installed  , message alert fails

### ISSUE THREAD

**Issue by LeoCFMoura** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#531]
Hi , looking to documents , i found:

if Facebook, Twitter, Instagram, WhatsApp, SMS or Email is not available, the errorCallback is called with the text 'not available'.

But when i try to use code below my message is different:

`<button onclick="window.plugins.socialsharing.shareVia('com.facebook.katana', 'Message via FB', null, null, null, function(){console.log('share ok')}, function(msg) {alert('error: ' + msg)})">message via Facebook</button>`

or 

`<button onclick="window.plugins.socialsharing.canShareVia('com.facebook.katana', 'msg', null, null, null, function(e){alert(e)}, function(e){alert(e)})">is facebook available ?</button>`

my error
alert 
error
com..task;com.asus.message,com.asus ......

**Comment by EddyVerbruggen** [comment]
If you use `shareViaSMS`, `shareViaEmail`, etc you'll get 'not available' as the doc says, but if you do `shareVia` or `canShareVia` the plugin will respond with what you found; a list of packages you can share to instead.

**Comment by LeoCFMoura** [comment]
Thanks for your help

**Comment by LeoCFMoura** [comment]
>>> the plugin will respond with what you found; a list of packages you can share to instead.

There's a way to change the message (  list of packages ) to something like : Facebook is not installed  ??

**Comment by EddyVerbruggen** [comment]
Sure, just show that.

**Comment by LeoCFMoura** [comment]
NP & congratulations amazing work!
