### ISSUE TITLE
I/Web Console: The injected error callback of 'share' received: "JSON error":106

### ISSUE THREAD

**Issue by hunkim** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#532]
Thanks for the wonderful plug-in. It works well in iOS. However, in Android, it does not work with the error message:
Web Console: The injected error callback of 'share' received: "JSON error":106

My code is prestty much standard:
```
factory.share= function(p) {
    console.log("Let's share");
    var msg="Check this out: ...";

    if (window.plugins && window.plugins.socialsharing) {
      window.plugins.socialsharing.share(msg, function() {
        console.log("Success")
      },
      function (error) {
        console.log("Share fail " + error)
      });
    }
    else console.log("Share plugin not available");
  }
```

I dit not change any settings or config.xml. Once again, it works perfectly, but it does not work on Android. Perhaps, I miss something here. I'm using Android 4.3, API 22.

Thanks for your help.

**Comment by hunkim** [comment]
I've installed Automatically (CLI / Plugman), and README says, "There is no need to change or add anything in your html."

However, after I add "<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />", it works.

Perhaps, it's just my phone's problem.

Sung

**Comment by EddyVerbruggen** [comment]
Hi, if you look closely at the API of the `share` function you'll see that the second param isn't a function (like in your example).
