### ISSUE TITLE
Hash Tag Fragment URL for angular 

### ISSUE THREAD

**Issue by rotemlevi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#534]
on IOS when sharing a hash tag URL the # is encoded to %23 and the link is no longer valid.

for example: 
http://www.wallashops.co.il/Mobile/Main#!/app/product/6NE932E13F
- >
http://www.wallashops.co.il/Mobile/Main%23!/app/product/6NE932E13F

**Comment by EddyVerbruggen** [comment]
Can you show the code you're using to share and also note which share target you pick?

**Comment by rotemlevi** [comment]
i use ng-cordova.js

 this is the function:

 share: function (message, subject, file, link) {
		  debugger;
        var q = $q.defer();
        subject = subject || null;
        file = file || null;
        link = link || null;
        $window.plugins.socialsharing.share(message, subject, file, link, function () {
          q.resolve(true);
        }, function () {
          q.reject(false);
        });
        return q.promise;
      },

**Comment by rotemlevi** [comment]
and i use this function like this:

 $scope.shareAnywhere = function () {
          var productURL = URI(BASEURL);
          productURL.fragment(true).pathname("/app/product/" + $scope.product.PfID);
          var ad = $scope.product.ShortName + "\n במחיר " + ($scope.product.StartPrice / 100) + "\n";
          $cordovaSocialSharing.share(ad, "היי, ראיתי מוצר מעניין בוואלה! שופס", $scope.product.ProductSmallImagePath, productURL.readable());
      };

**Comment by rotemlevi** [comment]
Then i share via Whatsapp but it doesn't meter, it happens in everything i try to share,
found on IOS 9.2

**Comment by EddyVerbruggen** [comment]
Hmm, it was fine before [this PR](#517) was merged.

**Comment by schmidt** [comment]
I just wanted to add, that I had the exact same problem and master fixes the bug in my case.

Thanks for the great work.

**Comment by EddyVerbruggen** [comment]
@schmidt Thanks for confirming that! I'll release a new version to npm later today.

**Comment by jeffthompson1971** [comment]
Has this been fixed? if so what version?  i have same issue.. my links with # are hosed up.   i'm using ngCordova on my ionic app.

**Comment by schmidt** [comment]
As far as I can tell, this has been fixed in 5.0.11. But there has been another change in that area, that is now part of 5.0.12 (#564). So you might want to try that as well.
