### ISSUE TITLE
Can't find plugin.xml for for plugin 'nl.x-services.plugins.socialsharing'.

### ISSUE THREAD

**Issue by kartagis** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#537]
Hi,
When I try to remove a plugin in order to get newer version, I get this error. I did a grep, and plugin.xml contains `id="nl.x-services.plugins.socialsharing.tests"` on line 6. Is this deliberate?

**Comment by EddyVerbruggen** [comment]
The root plugin.xml doesn't have it: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/plugin.xml#L6

The one in the tests folder has: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/tests/plugin.xml#L6

You can remove that if it bothers you.
