### ISSUE TITLE
Is there any event to indicate that attachement is ready for share?

### ISSUE THREAD

**Issue by Dineshrajaa** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#540]
Hi Eddy,
 Thanks for this awesome plugin, I would like to know whether there exist any event to indicate that the Attachment is loaded successfully? because sometimes its taking more time to show the Share Via popover when I need to share a  image so if there is any event I could show a progress bar and hide it when the image has been loaded.

**Comment by EddyVerbruggen** [comment]
No, but you can do that yourself - download the file from the internet while showing a progressbar, store it locally, then share that local file.
