### ISSUE TITLE
Is it possible to return which one is shared to?

### ISSUE THREAD

**Issue by zhouhao27** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#541]
I'm using **window.plugins.socialsharing.share** to share to social apps. I'm wondering if it's possible to return which social apps is shared in success callback? Thanks.

**Comment by avishayhajbi** [comment]
+1

**Comment by jolivier** [comment]
Looking for this too !

**Comment by nico66** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Please give the master branch of this repo a spin: it now supports a `.shareWithOptions` method which will return the app that was picked by the user. This only works on iOS currently though and I don't expect support to land soon on Android as it would require a lot of changes.

**Comment by nico66** [comment]
Thank you!

**Comment by jeffthompson1971** [comment]
+1 me too
