### ISSUE TITLE
Error building SocialSharing.m at XCode 6.1

### ISSUE THREAD

**Issue by rpassosgregorio** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#543]
The following errors apears when i try to build my project using this plugin:

SocialSharing.m:96:114: Expected ')'
SocialSharing.m:96:51: Incompatible block pointer types sending 'void (^)(NSString *__strong, BOOL, NSArray *__strong)' to parameter of type 'UIActivityViewControllerCompletionWithItemsHandler' (aka 'void (^)(NSString *__strong, BOOL, NSArray *__strong, NSError *__strong)')

These erros appears in this block of code at the second line:

if ([activityVC respondsToSelector:(@selector(setCompletionWithItemsHandler:))]) {
        [activityVC setCompletionWithItemsHandler:^(NSString *activityType, BOOL completed, NSArray * __nullable returnedItems, NSError * __nullable activityError) {
            [self cleanupStoredFiles];
            NSLog(@"SocialSharing app selected: %@", activityType);
            CDVPluginResult * pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsBool:completed];
            [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
        }];
      }else{
      // let's suppress this warning otherwise folks will start opening issues while it's not relevant
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
          [activityVC setCompletionHandler:^(NSString *activityType, BOOL completed) {
              [self cleanupStoredFiles];
              NSLog(@"SocialSharing app selected: %@", activityType);
              CDVPluginResult * pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsBool:completed];
              [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
          }];
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
      }

**Comment by rpassosgregorio** [comment]
I fetching the plugin via cordova today - 2016-03-16.
Ty

**Comment by EddyVerbruggen** [comment]
Damn. iOS 7 perhaps?

**Comment by infinitv** [comment]
Yes, i think. The target iOS of my app is 6.0. 
But i build the same project using this plugin, few minutes ago, in XCode 7.1 and build success.
I think the compability problem is with XCode version.
Sorry, my english is very poor.

**Comment by rpassosgregorio** [comment]
Yes, i think. The target iOS of my app is 6.0. 
But i build the same project using this plugin, few minutes ago, in XCode 7.1 and build success.
I think the compability problem is with XCode version.
Sorry, my english is very poor.

**Comment by EddyVerbruggen** [comment]
Yeah I'm thinking the same, thx!
