### ISSUE TITLE
Issue with longer image URL

### ISSUE THREAD

**Issue by Purus** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#544]
Sharing fails in services like Facebook and WhatsApp when the URL of the image shared is too long.

https://api.backendless.com/ca31bb1d-82e1-53e1-ff27-a63f89ef2200/v1/files/import%2F65F816E6-3F10-DE2F-FF69-71F999E262000dd44-blouse.png

The same code wtih shorter url's work fine. Is this a limit of the plugin or an issue?

**Comment by Purus** [comment]
If the below URL

https://api.backendless.com/ca31bb1d-82e1-53e1-ff27-a63f89ef2200/v1/files/import%2F65F816E6-3F10-DE2F-FF69-71F999E262000dd44-blouse.png

is changed as below, it works. (%2F is changed to /)

https://api.backendless.com/ca31bb1d-82e1-53e1-ff27-a63f89ef2200/v1/files/import/65F816E6-3F10-DE2F-FF69-71F999E262000dd44-blouse.png

**Comment by EddyVerbruggen** [comment]
Since part of the URL is encoded `%2F` and others are not `/` I'm assuming the URL isn't valid. The browser is forgiving, but Fb is not.
