### ISSUE TITLE
cordova-ios 4 support

### ISSUE THREAD

**Issue by veloce** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#549]
The buid fails with cordova-ios-4. Two errors:

SocialSharing.m:26:24: No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

SocialSharing.m:471:34: No known class method for selector 'dataFromBase64String:'

I'd love to see it compatible with last cordova-ios since cordova-ios 3.9 branch is pretty old now.

**Comment by EddyVerbruggen** [comment]
Which version are you loading from where?

**Comment by veloce** [comment]
I'm using version 4.3.81 from here: https://www.npmjs.com/package/cordova-plugin-socialsharing

Oh I see that it is not up to date, sorry. I should test again with github version.

**Comment by EddyVerbruggen** [comment]
Yeah also, it's not the correct one. Use this instead: https://www.npmjs.com/package/cordova-plugin-x-socialsharing

That guy published it without ever contacting me and I can't get hold of him.

**Comment by veloce** [comment]
I see, I've been using the wrong since the beginning... thank you for the quick reply!
