### ISSUE TITLE
CLI-6 Phonegap Build Failure Dure to Socialshare plugin

### ISSUE THREAD

**Issue by Divyaadz** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#550]
Using SocialSharing-PhoneGap-Plugin in Phonegap Build. 

When I use cli-6 in config.xml of PhonegapBuild, android build is failing due to an social media plugin error. Attached the log info.
 
<preference name="phonegap-version" value="cli-6.0.0" /> 

 
Followed this blog:
http://phonegap.com/blog/2016/02/09/phonegap_6_now_on_build/

:compileDebugJavaWithJavac/project/src/nl/xservices/plugins/SocialSharing.java:19: error: package org.apache.http.util does not exist
import org.apache.http.util.ByteArrayBuffer;
                           ^
/project/src/nl/xservices/plugins/SocialSharing.java:420: error: cannot find symbol
    ByteArrayBuffer baf = new ByteArrayBuffer(5000);
    ^
  symbol:   class ByteArrayBuffer
  location: class SocialSharing
/project/src/nl/xservices/plugins/SocialSharing.java:420: error: cannot find symbol
    ByteArrayBuffer baf = new ByteArrayBuffer(5000);
                              ^
  symbol:   class ByteArrayBuffer
  location: class SocialSharing
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
 FAILED

https://forums.adobe.com/message/8618795#8618795

**Comment by Dineshrajaa** [comment]
please share the config.xml contents here

**Comment by Divyaadz** [comment]
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="com.AllTamilNews" version="2.9.1" versionCode="13">
  <name>OM Tamil News</name>
  <description>Tamil Online News Papers to read dinamalar, dinathanthi, vikatan, Puthiyathalaimurai and One India Tamil</description>
  <author href="http://erpfog.com" email="support@erpfog.com">ERPfog</author>
  <content src="index.html"/>
  <preference name="permissions" value="none"/>
  
  <preference name="target-device" value="universal"/>
  <preference name="fullscreen" value="false"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="prerendered-icon" value="true"/>
  <preference name="stay-in-webview" value="false"/>
  <preference name="ios-statusbarstyle" value="black-opaque"/>
  <preference name="detect-data-types" value="true"/>
  <preference name="exit-on-suspend" value="false"/>
  <preference name="show-splash-screen-spinner" value="true"/>
  <preference name="auto-hide-splash-screen" value="true"/>
  <preference name="disable-cursor" value="false"/>
  <preference name="android-minSdkVersion" value="14"/>
  <preference name="windows-target-version" value="10.0" />
  <preference name="phonegap-version" value="cli-6.0.0" /> 
  <preference name="windows-identity-name" value="23016ERPfog.OmTamilNews" />
  <gap:plugin name="org.apache.cordova.device-orientation"/>
  
  <gap:plugin name="org.apache.cordova.inappbrowser"/>
  <gap:plugin name="org.apache.cordova.splashscreen"/>
  <gap:plugin name="org.apache.cordova.vibration"/>
  <gap:plugin name="nl.x-services.plugins.socialsharing" />
  <gap:plugin name="net.tunts.webintent" />
  <gap:plugin name="cordova-plugin-customurlscheme" source="npm">
	<param name="URL_SCHEME" value="omtamilnews" />
  </gap:plugin>
  <icon src="icon.png"/>
  <icon src="www/res/icon/android/icon-36-ldpi.png" gap:platform="android" gap:qualifier="ldpi"/>
  <icon src="www/res/icon/android/icon-48-mdpi.png" gap:platform="android" gap:qualifier="mdpi"/>
  <icon src="www/res/icon/android/icon-72-hdpi.png" gap:platform="android" gap:qualifier="hdpi"/>
  <icon src="www/res/icon/android/icon-96-xhdpi.png" gap:platform="android" gap:qualifier="xhdpi"/>
  <icon src="www/res/icon/blackberry/icon-80.png" gap:platform="blackberry"/>
  <icon src="www/res/icon/blackberry/icon-80.png" gap:platform="blackberry" gap:state="hover"/>
  <icon src="www/res/icon/ios/icon-57.png" gap:platform="ios" width="57" height="57"/>
  <icon src="www/res/icon/ios/icon-72.png" gap:platform="ios" width="72" height="72"/>
  <icon src="www/res/icon/ios/icon-57-2x.png" gap:platform="ios" width="114" height="114"/>
  <icon src="www/res/icon/ios/icon-72-2x.png" gap:platform="ios" width="144" height="144"/>
  <icon src="www/res/icon/webos/icon-64.png" gap:platform="webos"/>
  <icon src="www/res/icon/windows-phone/icon-48.png" gap:platform="winphone"/>
  <icon src="www/res/icon/windows-phone/icon-173-tile.png" gap:platform="winphone" gap:role="background"/>
  <gap:splash src="www/res/screen/android/screen-ldpi-portrait.png" gap:platform="android" gap:qualifier="port-ldpi"/>
  <gap:splash src="www/res/screen/android/screen-mdpi-portrait.png" gap:platform="android" gap:qualifier="port-mdpi"/>
  <gap:splash src="www/res/screen/android/screen-hdpi-portrait.png" gap:platform="android" gap:qualifier="port-hdpi"/>
  <gap:splash src="www/res/screen/android/screen-xhdpi-portrait.png" gap:platform="android" gap:qualifier="port-xhdpi"/>
  <gap:splash src="www/res/screen/blackberry/screen-225.png" gap:platform="blackberry"/>
  <gap:splash src="www/res/screen/ios/screen-iphone-portrait.png" gap:platform="ios" width="320" height="480"/>
  <gap:splash src="www/res/screen/ios/screen-iphone-portrait-2x.png" gap:platform="ios" width="640" height="960"/>
  <gap:splash src="www/res/screen/ios/screen-iphone-portrait-568h-2x.png" gap:platform="ios" width="640" height="1136"/>
  <gap:splash src="www/res/screen/ios/screen-ipad-portrait.png" gap:platform="ios" width="768" height="1024"/>
  <gap:splash src="www/res/screen/ios/screen-ipad-landscape.png" gap:platform="ios" width="1024" height="768"/>
  <gap:splash src="www/res/screen/windows-phone/screen-portrait.jpg" gap:platform="winphone"/>
  <splash src="splash.png" />
  <access origin="*" subdomains="true"/>
  <plugin name="com.danielcwilson.plugins.googleanalytics" spec="0.6.1" source="pgb" />
  <plugin name="cordova-plugin-whitelist" version="1"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
  </platform>
  <platform name="winphone" />
</widget>

**Comment by Dineshrajaa** [comment]
please use "Insert code" option or pastebin to share your config.xml

**Comment by Divyaadz** [comment]
Please find the detail below. Thanks

`<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="com.AllTamilNews" version="2.9.1" versionCode="13">
  <name>OM Tamil News</name>
  <description>Tamil Online News Papers to read dinamalar, dinathanthi, vikatan, Puthiyathalaimurai and One India Tamil</description>
  <author href="http://erpfog.com" email="support@erpfog.com">ERPfog</author>
  <content src="index.html"/>
  <preference name="permissions" value="none"/>
  
  <preference name="target-device" value="universal"/>
  <preference name="fullscreen" value="false"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="prerendered-icon" value="true"/>
  <preference name="stay-in-webview" value="false"/>
  <preference name="ios-statusbarstyle" value="black-opaque"/>
  <preference name="detect-data-types" value="true"/>
  <preference name="exit-on-suspend" value="false"/>
  <preference name="show-splash-screen-spinner" value="true"/>
  <preference name="auto-hide-splash-screen" value="true"/>
  <preference name="disable-cursor" value="false"/>
  <preference name="android-minSdkVersion" value="14"/>
  <preference name="windows-target-version" value="10.0" />
  <preference name="phonegap-version" value="cli-6.0.0" /> 
  <preference name="windows-identity-name" value="23016ERPfog.OmTamilNews" />
  <gap:plugin name="org.apache.cordova.device-orientation"/>
  
  <gap:plugin name="org.apache.cordova.inappbrowser"/>
  <gap:plugin name="org.apache.cordova.splashscreen"/>
  <gap:plugin name="org.apache.cordova.vibration"/>
  <gap:plugin name="nl.x-services.plugins.socialsharing" />
  <gap:plugin name="net.tunts.webintent" />
  <gap:plugin name="cordova-plugin-customurlscheme" source="npm">
	<param name="URL_SCHEME" value="omtamilnews" />
  </gap:plugin>
  <icon src="icon.png"/>
  <icon src="www/res/icon/android/icon-36-ldpi.png" gap:platform="android" gap:qualifier="ldpi"/>
  <icon src="www/res/icon/android/icon-48-mdpi.png" gap:platform="android" gap:qualifier="mdpi"/>
  <icon src="www/res/icon/android/icon-72-hdpi.png" gap:platform="android" gap:qualifier="hdpi"/>
  <icon src="www/res/icon/android/icon-96-xhdpi.png" gap:platform="android" gap:qualifier="xhdpi"/>
  <icon src="www/res/icon/blackberry/icon-80.png" gap:platform="blackberry"/>
  <icon src="www/res/icon/blackberry/icon-80.png" gap:platform="blackberry" gap:state="hover"/>
  <icon src="www/res/icon/ios/icon-57.png" gap:platform="ios" width="57" height="57"/>
  <icon src="www/res/icon/ios/icon-72.png" gap:platform="ios" width="72" height="72"/>
  <icon src="www/res/icon/ios/icon-57-2x.png" gap:platform="ios" width="114" height="114"/>
  <icon src="www/res/icon/ios/icon-72-2x.png" gap:platform="ios" width="144" height="144"/>
  <icon src="www/res/icon/webos/icon-64.png" gap:platform="webos"/>
  <icon src="www/res/icon/windows-phone/icon-48.png" gap:platform="winphone"/>
  <icon src="www/res/icon/windows-phone/icon-173-tile.png" gap:platform="winphone" gap:role="background"/>
  <gap:splash src="www/res/screen/android/screen-ldpi-portrait.png" gap:platform="android" gap:qualifier="port-ldpi"/>
  <gap:splash src="www/res/screen/android/screen-mdpi-portrait.png" gap:platform="android" gap:qualifier="port-mdpi"/>
  <gap:splash src="www/res/screen/android/screen-hdpi-portrait.png" gap:platform="android" gap:qualifier="port-hdpi"/>
  <gap:splash src="www/res/screen/android/screen-xhdpi-portrait.png" gap:platform="android" gap:qualifier="port-xhdpi"/>
  <gap:splash src="www/res/screen/blackberry/screen-225.png" gap:platform="blackberry"/>
  <gap:splash src="www/res/screen/ios/screen-iphone-portrait.png" gap:platform="ios" width="320" height="480"/>
  <gap:splash src="www/res/screen/ios/screen-iphone-portrait-2x.png" gap:platform="ios" width="640" height="960"/>
  <gap:splash src="www/res/screen/ios/screen-iphone-portrait-568h-2x.png" gap:platform="ios" width="640" height="1136"/>
  <gap:splash src="www/res/screen/ios/screen-ipad-portrait.png" gap:platform="ios" width="768" height="1024"/>
  <gap:splash src="www/res/screen/ios/screen-ipad-landscape.png" gap:platform="ios" width="1024" height="768"/>
  <gap:splash src="www/res/screen/windows-phone/screen-portrait.jpg" gap:platform="winphone"/>
  <splash src="splash.png" />
  <access origin="*" subdomains="true"/>
  <plugin name="com.danielcwilson.plugins.googleanalytics" spec="0.6.1" source="pgb" />
  <plugin name="cordova-plugin-whitelist" version="1"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
  </platform>
  <platform name="winphone" />
</widget>`

**Comment by Dineshrajaa** [comment]
@Divyaadz please update your plugins and make its source as "npm" and for social sharing plugin you need to include like this.

`<gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />`

**Comment by Divyaadz** [comment]
Thank you for your help.

**Comment by Dineshrajaa** [comment]
welcome please close the issue if you have resolved it..
