### ISSUE TITLE
canShareVia('instagram'..) returns null despite instagram installed

### ISSUE THREAD

**Issue by barocsi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#561]
Hello,

Sharing an image through instagram works on android, however on ios 9 it is not.
Instagram is whitelisted in the .plist within LSApplicationQueriesSchemes.

window.plugins.socialsharing.canShareVia('instagram', null, null, share_image_uri, null, function (e) {
                       console.log(e);
                       // returns null
                     });

Where else should I add configuration parameters to make it work?

Thanks!

**Comment by EddyVerbruggen** [comment]
With this in your `.plist`:
```xml
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>instagram</string>
</array>
```

And this button in your html:
```html
<button onclick="window.plugins.socialsharing.canShareVia('instagram', 'msg', 'subj', ['www/img/ionic.png'], null, function() {alert('yep')}, function(errormsg){alert(errormsg)})">can use instagram?</button>
```

You should see an alert: `yep` when running it on iOS with Instagram installed. Reopen if not but also share your app with me.

**Comment by barocsi** [comment]
Thanks, so far this is what I did except msg and subj were null and image uri not being an array.
Will test for this also.

**Comment by mtxa** [comment]
Hi! I'm try this solution, but this not working for me.
Can't run Facebook, Messanger, Watsapp and other apps via 'canShareVia' on iOS (but this work fine on Android). Have any ideas?
