### ISSUE TITLE
Sharing on IOS encodes special characters (#)

### ISSUE THREAD

**Issue by petertenhoor** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#564]
Hi there,

First of all I want to say that I love this plugin. It does exactly what it needs to do for my Android app and hopefully it will soon function for my IOS app.

I use your plugin to share a message, image, url and subject with the global share function (window.plugins.socialsharing.share()). This works fine on IOS for all parameters except the url. In an URL like this one: 'http://www.subscribercounter.com/#!/pewdiepie' the hashtag gets encoded to this "http://www.subscribercounter.com/%23!/pewdiepie". This causes people sharing broken links.

It works fine for android and when I console.log the parameter that is given to the plugin the url is not encoded..

I create the URL like this: 

`var shareURL = 'http://www.subscribercounter.com/#!/' + username;`

Any idea's?

Greetings,

Peter

**Comment by EddyVerbruggen** [comment]
Hi! What's the exact version of the plugin you're using and hoe do you include it in your project?

Thx!

**Comment by petertenhoor** [comment]
Hi Eddy,

I use version 5.0.10 and installed by npm (cordova plugin add cordova-plugin-x-socialsharing).

Best Regards,

Peter

**Comment by AlmogCohen** [comment]
Actually I've came here to report a pretty similar problem with the special # character.

When I'm sharing a link to my website http://coryvo.com/##2I2BRWMEOS it works great on Android but crushes the whole application on the iPhone emulator.

I'm using version 5.0.11, should I open a new bug report for that?

**Comment by EddyVerbruggen** [comment]
Thanks both, I'm looking into it.

**Comment by EddyVerbruggen** [comment]
The problem was not `#` but having it twice in the URL. That's not OK according the rfc2396 Apple checks the URL against.

I've changed the iOS code, it will now escape all but the first `#` in an URL.

Available in 5.0.12 which I just published.

**Comment by AlmogCohen** [comment]
OK cool thanks! Is there anyway for the crush to be more verbose or 'soft'?

On 8 April 2016 at 06:56, Eddy Verbruggen <notifications@github.com> wrote:

> The problem was not # but having it twice in the URL. That's not OK
> according the rfc2396 Apple checks the URL against.
>
> I've changed the iOS code, it will now escape all but the first # in an
> URL.
>
> Available in 5.0.12 which I just published.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/564#issuecomment-207441934>
>



-- 

Almog Cohen

<https://htmlsig.com/signatures/01ADE8F6/edit>

[image: Linkedin] <http://linkedin.com/in/almogcohen>
*US: (415) 413-6714*
*Israel (Whatsapp): +972-54-220-7975 <%2B972-54-220-7975>*
*Skype: almog.cohen1232*

**Comment by EddyVerbruggen** [comment]
The URL needs to be passed as a valid URL to the share sheet, conforming to the aforementioned spec, so this is really the only option - your link should work fine though(?)

**Comment by petertenhoor** [comment]
Updating to 5.0.12 fixed it for me. Thanks :)
