### ISSUE TITLE
ios share breaks url with %

### ISSUE THREAD

**Issue by tony6waves** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#566]
looks like when pass in a proper url already encoded with %, say http://example.com/abc%20def/, the % will be further encoded to %25, which will break the resulting url (it is still a valid url syntax, but it becomes another url to the server)

the js code called is this:
window.plugins.socialsharing.share(msg, null, null, link);

looks like the line
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/5.0.10/src/ios/SocialSharing.m#L84
changed after 5.0.10 and it further changed in later versions caused this.

Once I build with 5.0.8, the problem is gone.

The issue does not happen with android.

**Comment by EddyVerbruggen** [comment]
Can you try changing [this line](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/src/ios/NSString%2BURLEncoding.m#L10) to `CFSTR("#%"),` ?

**Comment by tony6waves** [comment]
I am actually not a direct user of your code. I am using Apppresser which rely on your library. The js code I referenced is what I dig out from Apppresser.

But then I believe the code change you suggest will resolve the problem I am facing (although I didn't run that myself).

**Comment by EddyVerbruggen** [comment]
OK, grab the latest from `master` and it should be fine.
