### ISSUE TITLE
Uncaught Type Error: cannot read property ' ' of undefined

### ISSUE THREAD

**Issue by TarneemOmar** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#568]
Hi,

I am getting the error message : Uncaught Type Error: cannot read property ' ' of undefined 
for all 'share', 'shareViaTwitter', 'canSharViaEmail' means for all social meadia. I have included cordova.js in my index.html, and  the plugin of social media is there in the plugins files. 
Also I added the code in the config.xml file:
    <gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />

I have tried it in my both android mobiles (android version 5.1.0) using phonegap as well as the android emulator for nexus (android version 6) and the same problem I am facing with all of them

I have read the issues posted here, but I have tried every solution mentioned with no result. Is it possible because of the version of the android?
Also, how to check the setting of my social app in settings to make sure it has sharing feature enabled?

**Comment by EddyVerbruggen** [comment]
Doing this here: https://github.com/Telerik-Verified-Plugins/SocialSharing/issues/9
