### ISSUE TITLE
Sharing directly to Snapchat

### ISSUE THREAD

**Issue by mjaensch** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#569]
Is it possible to add direct sharing on snapchat to your plugin?
That would be awesome!

**Comment by EddyVerbruggen** [comment]
Android would be possible but if you can find a way to do that on iOS then please reopen - I was looking for urlscheme support and other bits but it doesn't look like it's "open" enough to support direct image sharing..

**Comment by sandeshbsuvarna** [comment]
Any update on the above query for the iOS platform?

**Comment by mspanesar145** [comment]
hi @EddyVerbruggen ,

How can we share text to Snapchat in ionic. I tried several ways none got succeeded.

**Comment by nnonimus** [comment]
same here no luck with text sharing text on snapchat although image is getting shared.

**Comment by redblinkconsulting** [comment]
@nnonimus i can share text on android in snapchat. So, were you able to share image in ios.i f you are able to share image then can share text also. Can you please let me know how are you sharing images.

**Comment by mspanesar145** [comment]
@nnonimus i can share text on android in snapchat. So, were you able to share image in ios.i f you are able to share image then can share text also. Can you please let me know how are you sharing images.
