### ISSUE TITLE
Whatsapp 2.16 sharing via .share('message...') "This item cannot be shared." error 

### ISSUE THREAD

**Issue by phenchanter** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#571]
Greetings!
After updating Whatsapp for iOS to version 2.16 sharing stopped working. 
When share via `window.plugins.socialsharing.share('Message')` then selecting Whatsapp and then any contact I'm getting error _This item cannot be shared. Please select a different item._

Sharing directly to whatsapp `window.plugins.socialsharing.shareViaWhatsApp` works fine

Sharing like `window.plugins.socialsharing.share('Message', 'Subject', null, 'http://example.com')` will share only link.

Maybe it is something related to [Whatsapp faq, sharing extension](https://www.whatsapp.com/faq/en/iphone/23559013) and UTI, but I have no idea actually since I'm javascript guy.

**Comment by skiipx** [comment]
Having the exact same issue after testing with new version of whatsapp in ios.

**Comment by EddyVerbruggen** [comment]
Sounds like WhatsApp stopped allowing you to share only a message, like Facebook and Instagram do?

**Comment by phenchanter** [comment]
>Sounds like WhatsApp stopped allowing you to share only a message, like Facebook and Instagram do?

Might be the case, but sharing via `window.plugins.socialsharing.shareViaWhatsApp('just message')` works fine. And `whatsapp://send?text=Hello%2C%20World!` as well.

Just checked sharing from notes application, native iOS one. It returns the same error. It seems it's Whatsapp itself issue, and not a API changing.

ps: Updated issue, it is relevant for iOS.

**Comment by EddyVerbruggen** [comment]
[`shareViaWhatsApp` also uses that URL scheme](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/src/ios/SocialSharing.m#L594), so that makes sense.

I must agree it's an issue with the WhatsApp share extension. That's part of their app and is either buggy since a recent release or it's on purpose.

**Comment by piyushmanurkar** [comment]
I have same issue when using
window.plugins.socialsharing.share('Message', 'Subject', null, null)
message show...
'this item cannot be shared. please select a different item'.
any update on this issue???

Thank You!!!

**Comment by phenchanter** [comment]
I wrote to whatsapp support about this issue and got reply from them
> Thank you for informing us about the issue; it will be fixed in a future version of WhatsApp. Unfortunately, we cannot comment on any future timelines, sorry. Thank you for your continued patience and support of WhatsApp.
It was ~ 3 weeks ago.

**Comment by piyushmanurkar** [comment]
Okay...
Thank you for the information about this... @phenchanter
