### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Marceel13** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#581]
i followed the steps you said but it doesn't work, when i click the button anything happens. I tried to debug and i've write a console.log() inside the function and it doesn't appear on the console. Maybe you can know what's wrong. I use 
<button onclick="test()">message via Twitter</button>

var test = function(){
		console.log("Testing");
		window.plugins.socialsharing.shareViaTwitter('Message via Twitter');
	}

Thanks

**Comment by EddyVerbruggen** [comment]
If that `console.log` doesn't work (on iOS?) make sure you have the `cordova-plugin-console` plugin installed.

Are you testing on a real device, browser, simulator or companion app?

**Comment by Marceel13** [comment]
i'm testing on a real device on android. This log is to check if the js reaches that point, because inside the function there's another log to check if it works but it never reaches the other point.
So in the console i can see the first log the one you see in my first post but not the second one i put inside the plugin function.

**Comment by EddyVerbruggen** [comment]
Please post your entire app because it's impossible to deduce what the problem is from such a small snippet.

**Comment by Marceel13** [comment]
ok, i'll do it as soon as i can. thank you.

**Comment by Marceel13** [comment]
here you have the repository https://github.com/Marceel13/test-socialSharing

**Comment by EddyVerbruggen** [comment]
There's all kinds of things wrong with it. Let's take the discussion over there.
