### ISSUE TITLE
setCompletionHandler is deprecated

### ISSUE THREAD

**Issue by Bouzmine** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#582]
I was compiling using XCode and found out that this method is deprecated. I don't know about ObjC or Swift, but I don't think using a deprecated method is great.
![capture d ecran 2016-04-27 a 08 33 57](https://cloud.githubusercontent.com/assets/15067923/14852195/db450354-0c52-11e6-980f-7487ce12f48f.png)

**Comment by EddyVerbruggen** [comment]
Have you seen the TODO in green there? I'll take care of it some day but don't expect it to be removed before iOS 12 or so.
