### ISSUE TITLE
"messaging failed to load attachment" 

### ISSUE THREAD

**Issue by yesitspeter** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#589]
I'm using the Android Emulator with API 23 loaded.  

I have tried sharing a file:// URI pointing to an image in the documents directory.  I have also tried sending a Data URL which is in the default PNG image format.

I'm not getting any choice as to the share destination.  Messaging automatically opens.  When I have entered a message recipient, I receive the error "messaging failed to load attachment" 

On a real device, a Samsung Galaxy Duos, Android 4.4.4 I was able to use the share plugin successfully.    However  this is API 20.

**Comment by EddyVerbruggen** [comment]
You probably have no apps installed on the eumlator besides the default mail client. And if that doesn't have an email account setup then messaging will fail..
