### ISSUE TITLE
Version 5.1.0  shareWithOptions(Using the share sheet) not published

### ISSUE THREAD

**Issue by virtualprodigy** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#592]
I noticed your README.md mentions using the new shareWithOptions for Android and iOS and it's available in version 5.1.0. I tried updating my plugin a few times before I went over to the Cordova and Telerik market places. It appears that 5.1.0 isn't released yet.   Can you please advise on what's happening here? Was it taken down or was the documentation push to the public too early?

Thanks in advance
![share with options 1](https://cloud.githubusercontent.com/assets/3647217/15077905/9cf87468-137e-11e6-954a-88fc60f15b04.png)
![share with options 2](https://cloud.githubusercontent.com/assets/3647217/15077906/9d0a2bea-137e-11e6-9ef1-4fb47faf0e1a.png)
![share with options 3](https://cloud.githubusercontent.com/assets/3647217/15077908/9d1c5450-137e-11e6-9ffc-90820a3ce6e5.png)

**Comment by dnoliver** [comment]
+1! cannot get the latest version! maybe the tag was not added?

**Comment by EddyVerbruggen** [comment]
I have not created a [5.1.0 release](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/releases) yet.

**Comment by blupu** [comment]
Ouch... I was banging my head on this and didn't realized that 5.1.0 didn't exist :-( So for the moment, do you advise to stay with the classic _share_ function? (Note: I am using PGB.)

**Comment by EddyVerbruggen** [comment]
Yep, but I will release it this month (so a few days left really)

**Comment by hopesourav** [comment]
Can I expect the release today ? I have already used the new syntax in my code as it's nice :)
However, cant build the app in cordova until the 5.1.0 get released
- Thanks !!

**Comment by EddyVerbruggen** [comment]
I released 5.1.1 yesterday 👍

**Comment by hopesourav** [comment]
Thank you so much !!

**Comment by edirectorios** [comment]
What is wrong... it says to me window.plugins.....shareWithOptions is not a function ¿?¿?
