### ISSUE TITLE
IOS dialog not showing

### ISSUE THREAD

**Issue by flieks** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#595]
Hi,

Only when i press 2 times the home button, the dialog pops up (see img), and from then on the share button always works.

![image](https://cloud.githubusercontent.com/assets/5032389/15106999/5a964d2e-15cd-11e6-84d8-811e13b3983a.png)

Thanks

**Comment by EddyVerbruggen** [comment]
Can you please elaborate? How are you triggering the plugin in your code?

**Comment by flieks** [comment]
just simply by this:
```
window.plugins.socialsharing.share(__this.model.Data.html, null, null, null, null, null);
      __this.tools.trackEvent('[tips] ' + __this.model.Data.title, "share", "share tips article");
```
But now i rebuild it in appBuilder in release mode and now it shows the popup fine.
Really strange
