### ISSUE TITLE
Cordova ios 4 Support

### ISSUE THREAD

**Issue by sammyukavi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#605]
The build fails with cordova-ios-4. Two errors:

SocialSharing.m:95:110: Expected ')'

SocialSharing.m:95:17: No visible @interface for 'UIActivityViewController' declares the selector 'setCompletionWithItemsHandler:'

I am working with cordova-plugin-x-socialsharing 5.1.0

Please advise

**Comment by EddyVerbruggen** [comment]
That should be fine when building from master, but the version on npm indeed not yet have this fix. Just published 5.1.1 which should work fine. Please give it a quick test and let me know if it's solved indeed.

**Comment by sammyukavi** [comment]
Thanks a lot for your response I am now seeing this

SocialSharing.m:124:19: No visible @interface for 'UIActivityViewController' declares the selector 'setCompletionWithItemsHandler:'

**Comment by EddyVerbruggen** [comment]
That doesn't make sense to me at all since the line before is supposed to guard that it's not called when that method is not defined.

Which iOS version is that? 7 perhaps?

**Comment by sammyukavi** [comment]
Yes. iOS 7

**Comment by EddyVerbruggen** [comment]
and you build with xcode 5, or? Tell me more plz

**Comment by sammyukavi** [comment]
Yes. Xcode 5 is what I am using

**Comment by sammyukavi** [comment]
I am also a beginner on iOS development

**Comment by EddyVerbruggen** [comment]
Please update to Xcode 6, the error will go away.

**Comment by sammyukavi** [comment]
Thank you so much
