### ISSUE TITLE
Whatsapp Sharing Issue with iPhone

### ISSUE THREAD

**Issue by artwaniparas** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#608]
Hi, I am facing an issue with whatsapp share, either text or either image is being shared but want to share both .. Any fixes?

`$cordovaSocialSharing
    .share(message, subject, file, link) // Share via native share sheet
    .then(function(result) {
      // Success!

    }, function(err) {
      // An error occured. Show a message to the user
    });

`
Using this code, The above code works very well with Android but gives issue with iPhone. Any suggestions ?

**Comment by yonihei** [comment]
"Note that on iOS when sharing an image and text, only the image is shared - let's hope WhatsApp creates a proper iOS extension to fix this."
sorry :|

**Comment by artwaniparas** [comment]
Thanks for guiding !
