### ISSUE TITLE
Image not getting shared in IOS devices for facebook

### ISSUE THREAD

**Issue by saurabhudaniya200** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#612]
I am using the following snippet which works on android fb, android whatsapp, ios twitter etc but is not working for facebook in ios, image is base64 string.

 var options = {
                        message: "share",
                        subject: "subject",                        
                        url: "url",
                        chooserTitle: 'Pick an app',
			files: [image];
                    }                   
                    window.plugins.socialsharing.shareWithOptions(options, function(){                        
                    }, function(error){                        
                    });

after running the following code I see everything except image in facebook for IOSs share

**Comment by izaaz** [comment]
Same here. Using a base64 image does not work in ios Facebook. It does work in ios mail app though.

Thanks,
Izaaz

**Comment by saurabhudaniya200** [comment]
I spent a lot of time on this one and found that the url option is creating this problem, if you pass the url option to the facebook then facebook rejects all the other params and scrape the content from the link itself so I think this is the issue with the facebook policy itself

https://developers.facebook.com/docs/sharing/ios
