### ISSUE TITLE
Windows phone lumia help :)

### ISSUE THREAD

**Issue by daniele777** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#616]
`   window.plugins.socialsharing.shareViaEmail(
     'Nome del Farmaco : ' +(dbfarm)+ '<BR>Dosaggio : ' +(dbdos)+'<BR>Nome : '+(dbname)+'<BR>Cognome : ' +(db_cognome)+'<BR>Codice Fiscale : '+ (dbcf),
  'Richiesta Farmaco Online',
  ['prova@libero.it'], // TO: must be null or an array
  null, // CC: must be null or an array
  null // BCC: must be null or an array

);`

For android and ios all ok.. but in windows phone i can't see email address and the body of message... any idea ?

**Comment by EddyVerbruggen** [comment]
The signature of the methods is this, your usage looks differntly:

```js
shareViaEmail(message, subject, toArray, ccArray, bccArray, fileOrFileArray, successCallback, errorCallback) {}
```

**Comment by daniele777** [comment]
Eddye can write and exaple please? for windows phone..

**Comment by EddyVerbruggen** [comment]
That's the behavior of share() instead of shareViaEmail(). Just check the readme.
