### ISSUE TITLE
shareWithOptions: wrong TO field when sharing image through Email 

### ISSUE THREAD

**Issue by FraBastiano** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#618]
Hi, I'm using shareWithOptions method to share an image on various sharing apps. Everything works fine when I choose whatsapp, twitter, facebook from share sheet. The problem arises when I try to share the image through email: when I choose Gmail (or sony default email app or samsung default email app) from share sheet, composing page appears correctly, subject is correct, message is correct and the image is there, but the "TO" field is not blank as supposed, but is set with the string of the image path as you can see in the attached screenshot.
I'm testing on sony xperia z5 with Android 6.0.1 and Samsung Galaxy S5 with Android 6.0

The code I use is the following

```
var options = {
  message: 'Message: I shared an image',
  subject: 'Subject: an image',
  files: [path_to_image]
};

window.plugins.socialsharing.shareWithOptions(
  options,
  function (result) {
    console.log("Share completed? " + result.completed);
    console.log("Shared to app: " + result.app);
  },
  function (e) {
    console.log("Sharing failed with message: " + e);
  }
);
```

![sharewithoptions-email-problem](https://cloud.githubusercontent.com/assets/19978277/16124290/ab921408-33ee-11e6-9b24-623c0cf5e17e.jpg)

Thank you for your help

**Comment by FraBastiano** [comment]
I found the solution for this problem. I'm not and adroid developer so I don't really know what does it mean, but changing this line at the end of getFileUriAndSetType method
`sendIntent.setDataAndType(Uri.fromFile(new File(image)), type);`
with this one
`sendIntent.setType(type);`
solves the problem. I found this on stackoverflow
[http://stackoverflow.com/a/36265691](url)

**Comment by jycouet** [comment]
Hello, 
I'm facing the same issue. And it's the same for all attachment (not only images).
Is it possible to correct it in the plugin directly?

**Comment by EddyVerbruggen** [comment]
@jycouet If you're building on your local machine you can change the Java file and see if it helps..

**Comment by MusicCog** [comment]
@FraBastiano Thanks your change worked for me.

**Comment by EddyVerbruggen** [comment]
Thanks guys for testing that change. I've now added it as well and 5.1.2 has been published to npm.
