### ISSUE TITLE
Share sheet doesn't show all targets

### ISSUE THREAD

**Issue by ezequielrozen** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#619]
In android 6.0. I haven't tryed it on iOS. Why it doesn't show facebook and others apps? Only showes gmail, drive and telegram.

I'm using: `window.plugins.socialsharing.shareWithOptions(options, onSuccess, onError);`

**Comment by EddyVerbruggen** [comment]
Thanks for changing the title 💩 

Interesting.. I don't have an Android 6 device.. could it be a permission thing? What is the exact content of your `options` object? Does it matter if you fi only share an image, or only text?

**Comment by ezequielrozen** [comment]
I'm trying to use your example. I don't know, it happens on Android 4.4.4 too.

**Comment by EddyVerbruggen** [comment]
If you have Facebook installed on 4.4.4 it should show Facebook in the sheet. C'mon show your exact code!

**Comment by ezequielrozen** [comment]
I have Facebook installed and it doesn't show in the sheet. This is my code:

`angular

  .module('exposureBusinessApp')
  .factory('$share', shareService)

function shareService(_) {

  return {
    shareApp: shareApp
  }

  function shareApp () {
    // this is the complete list of currently supported params you can pass to the plugin (all optional)
    var options = {
      message: 'share this', // not supported on some apps (Facebook, Instagram)
      subject: 'the subject', // fi. for email
      files: ['', ''], // an array of filenames either locally or remotely
      url: 'https://www.website.com/foo/#bar?a=b',
      chooserTitle: 'Pick an app' // Android only, you can override the default share sheet title
    }

    var onSuccess = function(result) {
      console.log("Share completed? " + result.completed) // On Android apps mostly return false even while it's true
      console.log("Shared to app: " + result.app) // On Android result.app is currently empty. On iOS it's empty when sharing is cancelled (result.completed=false)
    }

    var onError = function(msg) {
      console.log("Sharing failed with message: " + msg)
    }

    window.plugins.socialsharing.shareWithOptions(options, onSuccess, onError)
  }
}
`

Where `shareApp` is my ng-click handler.

**Comment by EddyVerbruggen** [comment]
Is your `files` param actually empty? Remove it if so.

**Comment by ezequielrozen** [comment]
Ok, let me check...

**Comment by ezequielrozen** [comment]
Great! Thank you for all. It is working well!
