### ISSUE TITLE
FilePath used in To-field Email on Android 

### ISSUE THREAD

**Issue by TheMysticMan** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#624]
When sharing a file via Email on Android the filepath is used in the To-field.
Api method: shareWithOptions.

Plugin version : 5.1.1
Android version: 6.0.1

**Comment by FraBastiano** [comment]
That's the same issue I opened 18 days ago. If you look at my post I suggested a solution. You have to manually modify the Java file of the plugin, at least until a solution is posted on github.

[https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/618](url)

**Comment by TheMysticMan** [comment]
@FraBastiano 
Thanks. That seems to work.

**Comment by TheMysticMan** [comment]
@EddyVerbruggen 
Can't you use this solution or will it break other things?

**Comment by EddyVerbruggen** [comment]
Part of version 5.1.2.
