### ISSUE TITLE
Can i get the post_id on success callback in facebook? On ios and android?

### ISSUE THREAD

**Issue by roysG** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#625]

**Comment by roysG** [comment]
Can i get the post_id on success callback in facebook? On ios and android?

**Comment by EddyVerbruggen** [comment]
Nope, that would require the Facebook widget to send that back to the calling app. Which it doesn't.

Perhaps you can integrate the Facebook SDK instead.
