### ISSUE TITLE
iOS - Sharing on Twitter through the sheet doesn't show the url

### ISSUE THREAD

**Issue by ezequielrozen** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#628]
Hi!

Like the title says, the url does not appear on Twitter. It only shows the message.

**Comment by EddyVerbruggen** [comment]
Can you try a different URL to be sure? And if the URL matters, then what is it exactly?

**Comment by ezequielrozen** [comment]
Sorry it is working well. The thing was when you are writing the post, there is a preview about the link, then when you do the post, it appears!
