### ISSUE TITLE
Android share not loading all apps in version 4.2.1 or less

### ISSUE THREAD

**Issue by rtomas** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#629]
I recommend not to include 
files: ['', ''] in options unless you have files to share.
Otherwise not all apps would appear !

**Comment by EddyVerbruggen** [comment]
I'd gladly accept a PR to fix that! It doesn't have to be a native fix, can also be solved in socialsharing.js.

**Comment by rtomas** [comment]
No permission to commit en PR.

Change in SocialSharing.java

Delete line 232
final boolean hasMultipleAttachments = files.length() > 1;

 and add this
int totalRealFiles = 0;
        try {
          for (int i =  0; i < files.length(); i++)
          {
            if (!"".equals(files.getString(i))) 
              totalRealFiles++;
          }
        } catch (Exception e) {
          totalRealFiles = files.length();
        }
        final boolean hasMultipleAttachments = totalRealFiles > 1;

**Comment by EddyVerbruggen** [comment]
I think your code will get the job done indeed, thanks!

Can you hit that 'fork' button at the top right and make the changes in your account? Then you'll be able to browse to 'pull requests' and submit a PR.

**Comment by rtomas** [comment]
did you get it ok ?

i add one more line to add the type if fileUris are empty.

Thanks !

--
http://www.tomasrawski.com.ar/
