### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by kalmecak** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#633]
Hey team!

I'm using your nice plugin and I've find an error that throws the console:

`ReferenceError: Can't find variable: require  --  SocialSharing.js:1`

I think is not necessary to use `require` because the `cordova` variable is already defined on the `window` object.

**Comment by EddyVerbruggen** [comment]
Hey, thanks for reporting this - fixed in 5.1.2
