### ISSUE TITLE
Share like Instagram

### ISSUE THREAD

**Issue by erperejildo** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#635]
I'm working with this plugin and so far looks great but I'm wondering if it would be posible, to do a sharing like Instagram. I mean, share content without opening the social app.
In this case we could do multiples sharing in the "same" time.

**Comment by EddyVerbruggen** [comment]
You can't 'silently' share to Instagram as you need the user's consent. You can probably use the Instagram SDK to show a consent screen first, but with this plugin the user doesn't need to agree with anything since he uses the actual (Instagram) app to perform the share.
