### ISSUE TITLE
socialshare is undefined

### ISSUE THREAD

**Issue by thomashrabe** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#636]
Hi there,

I am trying to follow the tutorial example in ionic with the line 

`window.plugins.socialsharing.shareWithOptions(options, onSuccess, onError);`

but I keep getting 

`ionic.bundle.js:20306 TypeError: Cannot read property 'socialsharing' of undefined`

I guess I am missing something in the `app.js` to include the library? 

`angular.module('starter', ['ionic','leaflet-directive', 'ngCordova', ... ? `

Do I need to load it in the above line? 
Do I have to load it into the controller as a module? I didnt find that on the tutorial and it's not clear?

I tried `cordova plugin add` multiple times, either as the package name or through git

**Comment by GMaiolo** [comment]
- Does the plugin appear if you run `cordova plugin list`?
- Are you trying to use it on the browser or the device?
- Does `$window.plugins` or `$window.cordova` output `undefined` aswell?

**Comment by thomashrabe** [comment]
Hi

Turns out I was looking into the wrong documentation. If using `Ionic`, check [ngCordova](http://ngcordova.com/docs/plugins/socialSharing/) docs rather then the offical package documentations. They are not consistent.

I had to add $cordovaSocialSharing to my controller and it worked on the device, but not in the simulator and neither in my dev browser chrome.

**Comment by EddyVerbruggen** [comment]
That's all normal behavior. Closing.
