### ISSUE TITLE
New (5.1.0) syntax doesn't support dataURIs?

### ISSUE THREAD

**Issue by blukis** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#638]
DataURIs don't seem to work properly using the new recommended shareWithOptions() syntax.  When I share with the following code (on android) and select gmail, it just dumps the datauri text itself into an email body.  (I'm expecting the file itself appearing as an attachment instead.)  Works as desired using the old share() without callbacks.

`var options = {
	url: "data:image/png;base64,R0lGODlhDAAMALMBAP8AAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAUKAAEALAAAAAAMAAwAQAQZMMhJK7iY4p3nlZ8XgmNlnibXdVqolmhcRQA7",
}
window.plugins.socialsharing.shareWithOptions(options, function(result) {
	}, 
	function(msg) {
		alert("Sharing failed with message: " + msg);
	}
);`

BTW, using this in my config.xml:
`<plugin name="cordova-plugin-x-socialsharing" version="5.1.1" />`

**Comment by claudiobadii** [comment]
It works inserting the dataUri as element of the files array.

**Comment by blukis** [comment]
Oh, that works better.  Thanks!
