### ISSUE TITLE
Phonegap Build | error: package org.apache.http.util does not exist

### ISSUE THREAD

**Issue by JanST123** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#639]
Hi,

when Using Phonegap CLI  6.1.0 in PhoneGap Build the build fails. See the log below. Is that something you can fix?

> Build Date: 2016-07-19 13:42:24 +0000
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJavaWithJavac/project/src/nl/xservices/plugins/SocialSharing.java:19: error: package org.apache.http.util does not exist
import org.apache.http.util.ByteArrayBuffer;
                           ^
/project/src/nl/xservices/plugins/SocialSharing.java:420: error: cannot find symbol
    ByteArrayBuffer baf = new ByteArrayBuffer(5000);
    ^
  symbol:   class ByteArrayBuffer
  location: class SocialSharing
/project/src/nl/xservices/plugins/SocialSharing.java:420: error: cannot find symbol
    ByteArrayBuffer baf = new ByteArrayBuffer(5000);
                              ^
  symbol:   class ByteArrayBuffer
  location: class SocialSharing
Note: /project/src/nl/xservices/plugins/SocialSharing.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.846 secs
undefined

**Comment by ecoboff1** [comment]
In the build.gradle file inside platforms/android
place this line after 'buildToolsVersion cdvBuildToolsVersion' line 180

useLibrary 'org.apache.http.legacy'

I'll commit the fix now

**Comment by EddyVerbruggen** [comment]
I'm guessing you're not using `cordova-plugin-x-socialsharing` from `npm`, right?

**Comment by JanST123** [comment]
Hi,
This is duplicate of issue #640 and already solved.

**Comment by EddyVerbruggen** [comment]
Let's close this one.
