### ISSUE TITLE
Phonegap Build | error: package org.apache.http.util does not exist

### ISSUE THREAD

**Issue by JanST123** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#640]
Hi,

when Using Phonegap CLI  6.1.0 in PhoneGap Build the build fails. See the log below. Is that something you can fix?

<pre>
Build Date: 2016-07-19 13:42:24 +0000
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJavaWithJavac/project/src/nl/xservices/plugins/SocialSharing.java:19: error: package org.apache.http.util does not exist
import org.apache.http.util.ByteArrayBuffer;
                           ^
/project/src/nl/xservices/plugins/SocialSharing.java:420: error: cannot find symbol
    ByteArrayBuffer baf = new ByteArrayBuffer(5000);
    ^
  symbol:   class ByteArrayBuffer
  location: class SocialSharing
/project/src/nl/xservices/plugins/SocialSharing.java:420: error: cannot find symbol
    ByteArrayBuffer baf = new ByteArrayBuffer(5000);
                              ^
  symbol:   class ByteArrayBuffer
  location: class SocialSharing
Note: /project/src/nl/xservices/plugins/SocialSharing.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.846 secs
undefined
</pre>

**Comment by JanST123** [comment]
Sorry for submitting it twice...

**Comment by Dineshrajaa** [comment]
which version of Social-Sharing your using?

**Comment by JanST123** [comment]
Hi,
I'm using 4.3.8 from the Phonegap Build Plugin Repository

**Comment by Dineshrajaa** [comment]
can you please update it to the latest version??
<gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />

**Comment by kiwinewt** [comment]
Hi,
I am having the same issue after doing the plugin change. It appears the phonegap build service may be caching the plugins requested or somesuch?
I've tried rebuilding, re-pulling and rebuilding, updating the code and rebuilding and it is still getting the same issue in the log files.
Thanks

**Comment by EddyVerbruggen** [comment]
@kiwinewt If caching is the issue then specify the version as well. That'll defeat caching IMO.

**Comment by JanST123** [comment]
Build runs fine when changing the source from pgb to npm :)
