### ISSUE TITLE
Why shareViaTwitter returnes "false" on Android even when successfully shared?

### ISSUE THREAD

**Issue by annapogorelova** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#642]
I used **shareViaTwitter** function to share message (plugin v5.0.12) and it always returned **"false"** in response. I tried to update the version to 5.1.1 and use **shareWithOptions** and it still returned **"false"** when post is successfully shared (not to mention that almost every time when I launch my app window.plugins.socialsharing is undefined). I examined the docs:

```
var onSuccess = function(result) {
  console.log("Share completed? " + result.completed); // On Android apps mostly return false even while it's true
  console.log("Shared to app: " + result.app); // On Android result.app is currently empty. On iOS it's empty when sharing is cancelled (result.completed=false)
}
```

What do you mean by saying "mostly"? Why can't it return **true** or **false** for sure?
And how do I know that my tweet is shared then?

Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Because we just need to swallow whatever the other app gives us. That different per app and may even be different per app version, so that's "mostly" for you.
