### ISSUE TITLE
Would like success callback to include the selected contact maybe?

### ISSUE THREAD

**Issue by jeffthompson1971** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#643]
The plugin is working well for me on Ionic on both Android and IOS.   But what I need is to know what contact the user selected to share with.   Seems like that should be a pretty easy thing to do.   This way in my app the next time the user chooses to share the same item, I can have it default to the same contact that was used previously for item.    I have no way to know right now so every time even though they will alwasy share this particular item with the same person, they have to select it from contacts picker every time.    just not a very complete user experience.

**Comment by EddyVerbruggen** [comment]
Impossible AFAIK, but if it is indeed ".. a pretty easy thing to do." then please point me to the API.
