### ISSUE TITLE
Sharing Not Working When Using Variables In The Parameters

### ISSUE THREAD

**Issue by lethalazo** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#644]
These Are My Parameters.
And I am using variables as the url of image and text.
```
var options2 = {
  message: 'Hello! I Am Waving From '+ locatedate +' Via Adorbx ', 
  subject: 'Wave!', 
  files: [ img_urle , ''], 
  url: 'https://play.google.com/store/apps/details?id=com.arxiz.adorbx',
  chooserTitle: 'Wave With' 
};

var locatedate = localStorage.getItem('locatedat');
var img_urle = localStorage.getItem('imageurl');
```
While Sharing With Instagram Using 

`window.plugins.socialsharing.shareViaInstagram('Hello! I Am Waving From '+ locatedate +' Via Adorbx ', img_urle , function() {console.log('share ok');}, function(errormsg){console.log(errormsg);});`

And On Twitter Using 

`window.plugins.socialsharing.shareViaTwitter('Hello! I Am Waving From '+ locatedate +' Via Adorbx ', img_urle ,'https://play.google.com/store/apps/details?id=com.arxiz.adorbx', function() {console.log('share ok');}, function(errormsg){console.log(errormsg);});`

It Shares.

But While Using 

`window.plugins.socialsharing.shareWithOptions(options2, onSuccess2, onError2);`

For Sharing Everywhere Else Including Fb And Whatsapp, It Fails.

**Comment by junerockwell** [comment]
@lethalazo  You closed this. Did you find a solution?
