### ISSUE TITLE
Plugin breaks PhoneGap Build

### ISSUE THREAD

**Issue by iEchoic** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#648]
Hello,

Projects with SocialSharing no longer build on PhoneGap Build, producing this error:

"The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-socialsharing"

However, I'm already on the latest version. I'm building for iOS.

**Comment by Dineshrajaa** [comment]
you can try using git version

**Comment by DamodarSojka** [comment]
Make sure to use
<gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />
instead of
<gap:plugin name="cordova-plugin-socialsharing" source="npm" />
