### ISSUE TITLE
Is it possible to read sharing information?

### ISSUE THREAD

**Issue by claudioviola** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#652]
Hello
is it possible to read about sharing information?
Example: if run shareViaEmail() method can I get email address recipient?
Thanks!

**Comment by EddyVerbruggen** [comment]
You can pass in the recipient. But if the user wishes to change it you have no way of knowing that.

**Comment by claudioviola** [comment]
Thanks very much!
Is it possible to disable email sharing feature in the modal window when I run shareWidhtOptions() method?
