### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by asafco4** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#654]
Hi,
I had version 5.1.2 installed, but now I get error trying to fetch it.

Running "cordova plugin add cordova-plugin-x-socialsharing" gets me 5.1.1.

Can anyone clarify this???

**Comment by EddyVerbruggen** [comment]
I guess you were pulling it from the master branch in the GitHub repo ([currently at 5.1.2 which is work in progress, not released](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/plugin.xml#L5)), and are now including the latest version from npm (which is 5.1.1).
