### ISSUE TITLE
Spinner till loaded

### ISSUE THREAD

**Issue by peterpeterparker** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#655]
Hi,

First thx for the awesome plugin!

At least on Android phone, I find that calling the share function take a little bit of time, like 3-4 sec.
For that reason, I would like to display a spinner till the popup with the different share options is loaded, which would be more user friendly.

Is there any way to detect when the plugin have opened the popup with the sharing choices so I could display a spinner and close that spinner where that state is reached?

Had a look at the js file, didn't found any method to get the information about that state.

Thx in advance for the help.

**Comment by TheMysticMan** [comment]
@peterpeterparker 
Maybe the pause event can help you : [cordova pause event](https://cordova.apache.org/docs/en/5.1.1/cordova/events/events.pause.html)

**Comment by peterpeterparker** [comment]
@TheMysticMan good call, thx!

let loading:Loading = this.loadingController.create({
     spinner: 'crescent',
     content: 'Gonna share ...'
});

loading.present();

document.addEventListener('pause', () => {
     loading.dismiss();
});

**Comment by peterpeterparker** [comment]
Well looks like neither `pause` or `resume`, at least on iOS, are fired anymore when the share "popup" appears
