### ISSUE TITLE
Twitter and Facebook are not listed in the native share sheet in iOS

### ISSUE THREAD

**Issue by junerockwell** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#658]
Twitter and Facebook are not listed in the native share sheet in iOS if I concatenate a variable in the image file parameter. It's the same thing if I use just a variable instead of concatenation. 

````
var imgToShare = "one.jpg";
if ($scope.hasImages.length > 0) {
   imgToShare = $scope.hasImages[0].file_name; // a .jpg
}
$cordovaSocialSharing
      .share(mainMessage,
        "",
       "http://someSite.org/photos/" + imgToShare,
       linkToSomewhere)
      // Share via native share sheet
      .then(function(result) {
        // Success!
        // console.log("socialShare success");
      }, function(err) {
        // An error occured. Show a message to the user
        alert("socialShare error: " + err);
      });
````

I've tried like `imgToShare.toString()`, `JSON.stringify(imgToShare)` and `.concat(imgToShare)` when concatenation but none worked. However if I concatate a string (not as a content of a variable) like this `http://someSite.org/photos/" + "one.jpg"`, Twitter and Facebook appear on the native share sheet.

**Comment by EddyVerbruggen** [comment]
That's very odd. If you would extract `"http://someSite.org/photos/" + imgToShare` into a variable first and then pass that variable to `share`, would that make a difference? Please also log the variable and try passing it to `share` directly - does that make a difference?

**Comment by junerockwell** [comment]
@EddyVerbruggen It works now. The problem was that the value in `imgToShare` somehow became `undefined`. I fixed this problem and Twitter and Facebook are now listed in the iOS native share sheet!
