### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'window.plugins.socialsharing')

### ISSUE THREAD

**Issue by samratshaw** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#66]
Hey,

I am trying to use this in a sample iOS project.
I have added the files as you mentioned, but on click I am getting this error -

TypeError: 'undefined' is not an object (evaluating 'window.plugins.socialsharing').

I am using Cordova 3.4.0.

**Comment by josnys** [comment]
Hello mates, i made everything being said here so i can have this plugin works on either ios and android but still nothing yet. When i console.log($cordovaSocialSharing), it gives me an empty object. I can actually see the plugin files in the plugins folder and the js file that i put in the js folder. I link the socialsharing.js in the index.html, but still nothing works. Any help please..!

**Comment by josnys** [comment]
I forgot to add the line of error thrown to me
Error: 'undefined' is not an object (evaluating 'n.plugins.socialsharing.canShareVia')

**Comment by awuge** [comment]
The custom plug-in cordova is wrong， undefined is not an object (evaluating 'window.plugins.oaCommonOperate.finish')！How did you solve it？
