### ISSUE TITLE
using SocialSharing plugin with ripple / web browser

### ISSUE THREAD

**Issue by netvillage** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#663]
New to this so forgive a possible naive question.

I'm using phonegap build, and also trying to test via a browser using ripple. By that I meaning, I am running phonegap desktop and from my chrome browser running 
http://192.168.102.2:3000/?enableripple=cordova
to see my app run

My config.xml has the line
  `<plugin name="cordova-plugin-x-socialsharing" source="npm" />`

I downloaded SocialSharing.js and put it in \js\
Added this line to index.html
`<script type="text/javascript" src="js/SocialSharing.js"></script>`

with this code for the call
`<button onclick="window.plugins.socialsharing.share('Test Share', null, null, 'http://link');">Test Share</button>
` 
when I make the call I get erros on the console:
Error: exec proxy not found for :: SocialSharing :: share
(index):273 The injected error callback of 'share' received: "Missing Command Error"

Reading around a bit has me to start thinking that possibly this configuration (where the plug-in is run from a browser using the ripple extension), is not something that is supported. Is that correct?

**Comment by EddyVerbruggen** [comment]
Correct 😄 

And btw, you can remove `<script type="text/javascript" src="js/SocialSharing.js"></script>` from `index.html`.

**Comment by netvillage** [comment]
arg. Ok thank you for answering this question so quickly!

**Comment by netvillage** [comment]
hmm, does that mean it won't work from the PhoneGap developer mobile app either?

**Comment by EddyVerbruggen** [comment]
It only works for core plugins AFAIK since those are bundled with the dev app.
