### ISSUE TITLE
PhoneGap build Versions cli-6.0.0 

### ISSUE THREAD

**Issue by andreshenao206** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#666]
hello always use the plugin in phonegapbuild CLI.6.0 upgrade to 3.7 but no longer works and can be

thanks for your help

**Comment by EddyVerbruggen** [comment]
How are you including this plugin? I mean, what's in your `config.xml` exactly?

**Comment by andreshenao206** [comment]
hello  this config.xmlphonegap build
<plugin name="nl.x-services.plugins.socialsharing" spec="4.3.8" source="pgb" />

Thanks

**Comment by EddyVerbruggen** [comment]
Yeah exactly.. that's super old. Use the plugin from npm instead (I think that's default for the `source` param these days).. so this should be OK:

```xml
<plugin name="cordova-plugin-x-socialsharing" />
```

**Comment by andreshenao206** [comment]
thanks
