### ISSUE TITLE
Name collision with URLEncodedString in AmazonAd framework on iOS

### ISSUE THREAD

**Issue by skicson** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#683]
Causes link URLs to not appear in the output email/text/etc.

The AmazonAd framework implements a URLEncodedString method which overrides, and works differently than, the one provided with the plugin.  This causes UIActivity to not recognize the URL as a valid URL.

My workaround is to rename URLEncodedString to SSURLEncodedString.

**Comment by EddyVerbruggen** [comment]
Good suggestion, thx
