### ISSUE TITLE
Is WRITE_EXTERNAL_STORAGE really required for Android?

### ISSUE THREAD

**Issue by JTronLabs** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#685]
In plugin.xml, Android requires a special permission, but seems to work fine on my device when I comment it out. https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/plugin.xml#L61

    <config-file target="AndroidManifest.xml" parent="/*">
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    </config-file>

**Comment by EddyVerbruggen** [comment]
Yep, see the README for the case when it's required (and it would crash your app if it wasn't added, hence the default).

**Comment by JTronLabs** [comment]
Ah ok, sorry about that!

**Comment by monove** [comment]
If you avoid any function calls to share an image is it still required?

**Comment by rodrigograca31** [comment]
I got the same question as @monove .... My app only shares text (app URL) and just got this message from the Play Store while updating my app:

```
New permissions added
Warning:

Users that have the APK with version code 10006 may need to accept the android.permission.WRITE_EXTERNAL_STORAGE permission, which may result in them not upgrading to this version of the app.

Tip:

Ensure that the new permissions are necessary, and consider mentioning these permissions in the What's new in this release text.
```
I guess only Android 4.4 will get this permission "warning" but still......
