### ISSUE TITLE
Build failed for iOS with SocialSharing-PhoneGap-Plugin

### ISSUE THREAD

**Issue by AdamDiment** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#689]
I recently upgraded to Cordova 4.1.0 from 3.9.2 for iOS.  iOS platform:Xcode 7.3.1, Build version 7D1014

I now get two errors when building for ios from the command line:

Error 1. 

Plugins/cordova-plugin-socialsharing/SocialSharing.m:26:24: error: 
      no visible @interface for 'UIView' declares the selector
      'stringByEvaluatingJavaScriptFromString:'

Error 2.
Plugins/cordova-plugin-socialsharing/SocialSharing.m:471:34: error: 
      no known class method for selector 'dataFromBase64String:'
      NSData *fileData = [NSData dataFromBase64String:base64content];

for reference, seems like a similar issue to the one you fixed here https://github.com/Telerik-Verified-Plugins/PushNotification/issues/71 with your push plugin earlier this year.

There are also 2 warnings:

1. 
/Plugins/cordova-plugin-socialsharing/SocialSharing.m:20:8: warning: 
      incompatible pointer to integer conversion initializing 'BOOL'
      (aka 'signed char') with an expression of type 'Class _Nullable'
      [-Wint-conversion]
  BOOL avail = NSClassFromString(@"UIActivityViewController");

2. 
/Plugins/cordova-plugin-socialsharing/SocialSharing.m:76:15: warning: 
      'setCompletionHandler:' is deprecated: first deprecated in iOS 8.0 - Use
      completionWithItemsHandler instead. [-Wdeprecated-declarations]
  [activityVC setCompletionHandler:^(NSString *activityType, BOOL completed) {
              ^
In module 'UIKit' imported from /Users/AdamDiment/projects-github/vfi-mobile/platforms/ios/build/device/include/Cordova/CDVAvailabilityDeprecated.h:20:

Really appreciate your plugins, and your help with this, thanks!

**Comment by EddyVerbruggen** [comment]
Which version of the plugin is this? Surely not the most recent one as [line 26](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/src/ios/SocialSharing.m#L26) (error 1) is not the same. Please update and try again.
