### ISSUE TITLE
utm tracking parameters in url

### ISSUE THREAD

**Issue by jackocnr** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#70]
Is it possible to somehow alter the share URL after the user has selected which app they want to share with? Or specify different URLs for different apps? The reason is that we want to add utm tracking parameters to the URL, which would vary depending on the app e.g. for Facebook, we would want something like "http://example.com?utm_source=facebook".

**Comment by premtemp1** [comment]
Hello,
I am trying to implement utm in my app. Can you share some hints on your implementation for UTM?

Is there an option to change the .m and java file to get the click event  for the social sharing icon
