### ISSUE TITLE
ShareViaEmail on Ios button send is grey (Ionic Native implementation)

### ISSUE THREAD

**Issue by mrweiland** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#704]
I cannot share via email on IOS - button is grey when i try to send... I try to search for this issue and cant find anything about it. 

My code:
```
  SocialSharing.shareViaEmail('I found a queue for you...', 'Check out this queue', ['xxx@xxx.com']).then(() => {
      // Success!
    }).catch(() => {
      // Error!
    });
```

![shareviamail](https://cloud.githubusercontent.com/assets/12168854/20029340/89a0e994-a349-11e6-8781-74f72390ca38.png)

Is it something with my implementation or is it problem share via email on IOS10?

**Comment by d7laungani** [comment]
Did you ever fix this ? I am having the same issue .

**Comment by mrweiland** [comment]
I close this issue because its old - can have something todo when you not having a default mail client in IOS.
