### ISSUE TITLE
cordova-plugin-x-socialsharing vs cordova-plugin-socialsharing

### ISSUE THREAD

**Issue by miqmago** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#721]
I'm using this plugin `cordova plugin add cordova-plugin-x-socialsharing` in an app, but I've recently seen that [phonegap-app-developer](https://github.com/phonegap/phonegap-app-developer/blob/master/config.xml#L59) is using `cordova-plugin-socialsharing`.

Are there any differences? From what I've seen, [`cordova-plugin-socialsharing`](https://www.npmjs.com/package/cordova-plugin-socialsharing) is in version 4.3.81 while [`cordova-plugin-x-socialsharing`](https://www.npmjs.com/package/cordova-plugin-x-socialsharing) is in 5.1.3.

Is there any reason to be using an older version in phonegap-app-developer? (Right now what I've done is to clone phonegap-app-developer and change plugin :)

**Comment by EddyVerbruggen** [comment]
The one with the `x` is linked to this repo. The other one is from a dude that published it to npm before I did and I can't contact him.. so I'd rather see the dev app switch to the other id indeed.. can you perhaps open a ticket in their repo?

**Comment by miqmago** [comment]
Sure I will. That's very strange, cause in xml, the plugin is pointing to your repo, and so it does the npm one... Maybe the best thing would be to open a pull request to phonegap-app-developer
