### ISSUE TITLE
SocialSharing doesn't work iOS 10

### ISSUE THREAD

**Issue by ebhoren** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#729]
I'm having a very strange bug on iOS 10 using Phonegap 6.3.4 (cordova 6.1.1)
When pushing my share button, it execute **window.plugins.socialsharing.shareViaFacebook('Test', null, 'http://www.google.com');** and nothing happens.

But, when i put my app in background (open another app or just minimize the application) and I turn it to foreground, the Facebook's share appear to me.

I've tried @moisesbsfilho solution but it didn't work.
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/669#issuecomment-244478496

I've also tried to create a fresh new project and the same problem occur.

```
phonegap create testapp
cd testapp/
phonegap plugin add cordova-plugin-x-socialsharing
phonegap platform add ios
phonegap prepare
```

Am i doing something wrong?
Any help would be very appreciated :)
Thanks

**Comment by rockneverdies55** [comment]
@ebhoren refer to this issue: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/703

**Comment by ebhoren** [comment]
@rockneverdies55 It solve my problem. Thanks you so much. :)
