### ISSUE TITLE
Android 6.0.1 shareViaFacebook saved link instead of displaying share modal window

### ISSUE THREAD

**Issue by ebhoren** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#732]
When trying to share directly to Facebook on Android 6.0.1, the plugin saved link to user's Facebook saved links instead of displaying the share modal window.

See the bug in action here:
https://www.dropbox.com/s/yslo6xn8ba93fam/videoplayback.mp4?dl=0

As you can see, there is a small popup text saying "Saving to Facebook. Only you will see this."

I'm using window.plugins.socialsharing.shareViaFacebook('Hello World', null, 'http://www.google.com');

I've also tested socialsharing.share and it works, except it show Facebook App and a strange Save to Facebook option. See here: 
![bug](https://cloud.githubusercontent.com/assets/613562/21433701/d69e0da2-c83e-11e6-9f17-f819a43dcba9.jpg)

Look like Save to Facebook is always use instead of the formal Facebook App.

It work perfectly on iOS and Android 7.0. 
Am i doing something wrong?
The code is accessible here: https://github.com/ebhoren/fbtest

Thanks

**Comment by ebhoren** [comment]
Is it possible that Android returns the wrong Activity name for Facebook?

When listing all available apps on my device using **window.plugins.socialsharing.canShareVia(null, 'Hello World', null, null, null, function(e){ console.log(e); }, function(e){ console.log(e); });**, it list com.facebook.katana 2 times.

Any ideas?
I'm struggling for this bug for days.
Thanks

**Comment by ebhoren** [comment]
The code is accessible here: https://github.com/ebhoren/fbtest

**Comment by ebhoren** [comment]
I've solved my problem by using this plugin instead:
https://github.com/jeduan/cordova-plugin-facebook4

**Comment by almothafar** [comment]
@ebhoren if it is the issue with this plugin why you close this issue? also, do you get the plugin work with prefilled (or past hint workaround) with that native plugin?

**Comment by ebhoren** [comment]
@almothafar this plugin did not work the way i wanted it. That's why a strongly encourage you to use this plugin instead https://github.com/jeduan/cordova-plugin-facebook4

I'm closing this issue because i'm not interested in finding the solution to this bug anymore since i do not use it in my project.

**Comment by almothafar** [comment]
Yeah, but please open it for us who we use it :) or do I need to duplicate it?
Since this is an issue keep it open and just ignore it if you not interesting.

**Comment by mircoc** [comment]
I have the same issue in my application, i'll try to get more details and hopefully a solution

**Comment by mircoc** [comment]
PR fixes the issue. I hope @EddyVerbruggen find that is mergeable :). Thanks!
