### ISSUE TITLE
sharing from Documents directory

### ISSUE THREAD

**Issue by alexfoxy** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#742]
I have an audio app where I record mp4's to the Documents directory. I had to modify your code to get it working. 

I added this case to getFile : 

`
else if ([fileName hasPrefix:@"documents://"]) {
      // stripping the first 11 chars, because the path should start with / instead of documents://
      NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
      NSString *documentsDirectory = [paths objectAtIndex:0];
      fileName = [fileName substringFromIndex:11];
      NSString *fullPath = [NSString stringWithFormat:@"%@/%@", documentsDirectory, fileName];
      file = [NSURL fileURLWithPath:fullPath];
`

Is this correct?

**Comment by EddyVerbruggen** [comment]
If it works it works..
