### ISSUE TITLE
Android App Not Install. An existing package by the same name with a conflict

### ISSUE THREAD

**Issue by imirs** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#744]
Hi,

When i am adding to config.xml file a source link to this:
`<plugin spec="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git" />
`
I get an Error message of 'Android App Not Install. An existing package by the same name with a conflict' when trying to install the app.

![image](https://cloud.githubusercontent.com/assets/5325640/21788697/c78b9138-d6d8-11e6-8e8c-7ffea32f8bcd.png)

So i changed to a npm source and wrote like this:
`<gap:plugin name="cordova-plugin-x-socialsharing" source="npm"/>
`
it worked.

So i think the git source should be updated to the npm source, no?

**Comment by EddyVerbruggen** [comment]
Please update to the latest npm version.
