### ISSUE TITLE
Add # of shares as an argument in success callback function?

### ISSUE THREAD

**Issue by shawns582** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#763]
Is it possible to have the success callback return the # of contacts shared with? If sharing with a group (ie. whatsApp), perhaps it would return the # of people within the group? I would like to be able to give "points" to people who share more, and would need a callback like this to do it.  Thanks!

**Comment by EddyVerbruggen** [comment]
If WhatsApp would return that to the calling app we could - but that's not the case.
