### ISSUE TITLE
Failed to find configured root that contains 

### ISSUE THREAD

**Issue by Mystearica** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#764]
Sharing failed with message: Failed to find configured root that contains

Hi, im trying to share an audio file, but i receive this message, it doesn't matter if the file are stored locally or not, i receive the same error, any clue?

Thanks!

**Comment by EddyVerbruggen** [comment]
Please update to the latest version.

**Comment by Mystearica** [comment]
I already installed the lastest version, i guess.

The comand i used was ionic plugin add cordova-plugin-x-socialsharing

I need to do anything else?

**Comment by ruisilva450** [comment]
Sorry to bring this up once more but I'm getting this 5.4.7
I applied this to my config.xml as per @kprigel [said](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/1026#issuecomment-499608318) in https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/1026
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application/provider">
  <provider android:authorities="${applicationId}.sharing.provider" android:exported="false" android:grantUriPermissions="true" android:name="nl.xservices.plugins.FileProvider">
    <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/sharing_paths" />
  </provider>
</edit-config>
```

But now I'm getting:
> Failed to find configured root that contains /data/data/app.name/files/console.log

Should this be treated as a regression or am I missing something?

Thanks!
