### ISSUE TITLE
Pollyfill the new web share api

### ISSUE THREAD

**Issue by awebdeveloper** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#766]
Could you migrate to the new web share api. Currently only available in chrome for android behind a origin trail. 

https://developers.google.com/web/updates/2016/10/navigator-share

```
navigator.share({
    title: document.title,
    text: "Hello World",
    url: window.location.href
}).then(() => console.log('Successful share'))
.catch(error => console.log('Error sharing:', error));
```

**Comment by mgiuca** [comment]
Looks like this was [completed](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/www/SocialSharing.js). Close?

**Comment by awebdeveloper** [comment]
u mean i will be able to use the above code or something almost similar like cordova.sharW3C

**Comment by mgiuca** [comment]
Note: I just discovered this and read the code; haven't tried it yet.

By the look of it, yes, you should be able to use `navigator.share` with the above code. Note that `plugins.socialsharing.shareW3C` is the internal name used by the plugin that implements the same interface as `navigator.share`, but you shouldn't need to call it directly. See the line `navigator.share = window.plugins.socialsharing.shareW3C`; that means `navigator.share` will call the Cordova share plugin if you have it installed.

**Comment by awebdeveloper** [comment]
thanks @mgiuca
