### ISSUE TITLE
Message is not passed to pinterest 

### ISSUE THREAD

**Issue by Raspire** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#768]
Hi,

I am trying to share the photo and message to Pinterest through share via method. Photo is successfully passed but message is not passed. 

This is my code 
$cordovaSocialSharing.shareVia('com.pinterest','pinterest','events','imgUrl',null,
        function(result){
          console.log(result);
        }, 
        function(errormsg){
          console.log(errormsg);
        });

Thanks in advance,

**Comment by EddyVerbruggen** [comment]
Correct, that's Facebook policy. Meh.
