### ISSUE TITLE
IOS open app to use function

### ISSUE THREAD

**Issue by SmugbugsPravesh** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#784]
hi, i using 3d touch plugin to share app url in IOS, when we choose share option on homeIcon press, it open app then show sharing option, i want to open directly open sharing option while on homescreen

**Comment by EddyVerbruggen** [comment]
You mean the share item iOS adds automatically to your app when it's installed from the AppStore? That has nothing to do with either this plugin nor the 3D Touch plugin.
