### ISSUE TITLE
Problem with the calling 'window.plugins'

### ISSUE THREAD

**Issue by gina17** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#795]
Hi, I have a problem with the plugin using Intel XDK.
I created a project, add the social sharing plugin and install on my iphone but it does not work, The error that returns on the phone is that window.plugins is undefined, I have looked everywhere but still not able to find a solutions, Do you know how what could be the problem? Thanks a lot.

**Comment by EddyVerbruggen** [comment]
Probably need to wait for `deviceready` to fire.
