### ISSUE TITLE
not able to add this plugin! Error!

### ISSUE THREAD

**Issue by aanchal-agarwal** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#797]
![social sharing plugin install](https://cloud.githubusercontent.com/assets/16732101/23787119/7dc104ec-0596-11e7-97b0-23683df6c495.png)

**Comment by aanchal-agarwal** [comment]
updated cordova to 5.0.0 
Work fine now!

**Comment by Dineshrajaa** [comment]
5.0.0? please update it cordova to 6.5.0 :) @aanchal-agarwal
