### ISSUE TITLE
Sharing on WhatsApp crashes the app in Android 7

### ISSUE THREAD

**Issue by yadutechnologies** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#801]
Hi, 
I have added the plugin in my app all goes well upto Android 6. It crashes the app when it comes to Android 7. As soon as user clicks on share with WhatsApp it crashes the app. 
I have these plugins installed in my app, 

`cordova-plugin-actionsheet@2.2.2` 
`cordova-plugin-compat@1.0.0`
`cordova-plugin-datepicker@0.9.3`
`cordova-plugin-device@1.1.2`
`cordova-plugin-device-motion@1.2.1` 
`cordova-plugin-device-orientation@1.0.3`
`cordova-plugin-file@4.2.0`
`cordova-plugin-file-transfer@1.5.1`
`cordova-plugin-geolocation@2.2.0`
`cordova-plugin-inappbrowser@1.4.0`
`cordova-plugin-network-information@1.2.1`
`cordova-plugin-splashscreen@3.2.2`
`cordova-plugin-whitelist@1.2.2`
`cordova-plugin-x-socialsharing@5.1.1`
`cordova.plugins.diagnostic@3.3.2`
`phonegap-plugin-push@1.8.4 --save --variable SENDER_ID=xxxx; `
`uk.co.workingedge.phonegap.plugin.launchnavigator@3.1.1`
`cordova-plugin-console@1.0.4`
`cordova-plugin-mauron85-background-geolocation@2.2.5`

This is from project.properties, 

`android.library.reference.1=CordovaLib`
`cordova.system.library.1=com.android.support:appcompat-v7:+`
`cordova.system.library.2=com.android.support:support-v13:23+`
`cordova.gradle.include.1=phonegap-plugin-push/app-push.gradle`
`cordova.system.library.3=com.google.android.gms:play-services-gcm:10.2+`
`cordova.system.library.4=me.leolin:ShortcutBadger:1.1.4@aar`
`cordova.system.library.5=com.squareup.okhttp3:okhttp:3+`
`cordova.system.library.6=com.android.support:support-v4:+`
`cordova.gradle.include.2=cordova-plugin-mauron85-background-geolocation/app-logtofile.gradle`
`cordova.system.library.7=com.google.android.gms:play-services-location:+`
`cordova.system.library.8=com.android.support:support-v4:+`

Please help.

**Comment by Dineshrajaa** [comment]
Please update your social sharing plugin, it will solve the issue

`cordova plugin rm cordova-plugin-x-socialsharing`
`cordova plugin add cordova-plugin-x-socialsharing@5.1.7 --save`

**Comment by yadutechnologies** [comment]
@Dineshrajaa That worked for me!!
Thanks 👍
