### ISSUE TITLE
ShareViaFacebook call callback before share in facebook app

### ISSUE THREAD

**Issue by TalissonBento** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#802]
My code is
`			           $cordovaSocialSharing.shareViaFacebook(null, canvas.toDataURL(), null)
					   .then(function(result){
						   CoinService.winCoins($scope, "add_coin");
					   });`
The callback is called before user share in facebook ap and the callback always pass 'true' in result param, so user receive coins without  share anything.
They have any way to fix it?

**Comment by peterpeterparker** [comment]
Duplicates:

#829
#733
#722

**Comment by TalissonBento** [comment]
Fine!

**Comment by peterpeterparker** [comment]
@TalissonBento follow #841, I found a way to let the callback be resolved after the user share on android too

About always getting 'true' as a result I tend to think that there is no solution about that, see post scriptum of  #841 too
