### ISSUE TITLE
Is there a way to get confirmation is something was shared?

### ISSUE THREAD

**Issue by robofred** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#812]
Newbie programmer - sorry if I'm asking in the wrong forum.

I was able to get this working in Ionic2, but I'd like confirmation whether someone actually shared the content or not. In other words, the action sheet came up, they chose a sharing medium (SMS, Email, FB, whatever...) and they actually hit OK and shared/posted the content. Is there a way to get a signal as to whether they hit OK or Cancel?

Please provide some sample code as I'm VERY new to all this. Thanks much in advance.

**Comment by EddyVerbruggen** [comment]
See the readme.
