### ISSUE TITLE
compatiblity with Android N file:// scheme changes

### ISSUE THREAD

**Issue by Ragzzy-R** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#814]
Hello,
using socialsharing with image causes fileUrlExposed Exception in Android N. after a bit of googling found this in google documentation.

Passing file:// URIs outside the package domain may leave the receiver with an unaccessible path. Therefore, attempts to pass a file:// URI trigger a FileUriExposedException. The recommended way to share the content of a private file is using the FileProvider.

will there be a fix for this anytime soon? or can I write a patch and send a PR?

**Comment by EddyVerbruggen** [comment]
A patch will (as always) be highly appreciated!

**Comment by Spartanace1024** [comment]
Just curious if this has been resolved yet? Thanks in advance!

**Comment by EddyVerbruggen** [comment]
I just tried this without problems on my Nexus 6P running Android 7.1.2:

```js
            var msg = "My message";
            var subject = "My subject";
            var imageLink = "http://cdn.abclocal.go.com/content/creativecontent/images/cms/1119377_1280x720.jpg";
            var url = "https://www.google.com";

            window.plugins.socialsharing.shareWithOptions({
                      subject: subject,
                      message: msg,
                      url: url,
                      files: [imageLink]
                    },
                    function() {console.log('share ok')},
                    function(errormsg){ console.log("Error: " + errormsg)}
            );
```

I picked Gmail to share to and the image came along nicely.

By the way, there [_is_ a `FileProvider` in the repo that's being used](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/FileProvider.java).

Not much I can do besides that test..

**Comment by Ragzzy-R** [comment]
@EddyVerbruggen  actually this problem exists when sharing  an attachment from local filesystem as the Nougat file system access has been changed. Your example shared it from http:// but the plugin right now accesses local files via file:// which is no longer supported since nougat. This issue still exists. I posted this issue after the app getting crash on 7.1.2 on Nexus 6P while trying to access a local file.

**Comment by EddyVerbruggen** [comment]
@Ragzzy-R I've also tested sharing a file from the www folder. Works fine as well. Which steps do I need to take to share a file from a location that causes the issue? And if you have an idea what to change please consider contributing.

**Comment by Ragzzy-R** [comment]
I think I did that from an external folder outside the package. im not sure. its been months. keep this issue open. i'll test it tomorrow and let you know? I haven't been working on ionic lately. need to set up the environment and stuff.

**Comment by Ragzzy-R** [comment]
Hello,
sorry for the wait. I tried checking now. This is what I got

```
08-16 17:54:16.684: D/SystemWebChromeClient(725): file:///android_asset/www/plugins/cordova-plugin-x-socialsharing/www/SocialSharing.js: Line 126 : The injected error callback of 'share' received: "URL_NOT_SUPPORTED"
08-16 17:54:16.684: I/chromium(725): [INFO:CONSOLE(126)] "The injected error callback of 'share' received: "URL_NOT_SUPPORTED"", source: file:///android_asset/www/plugins/cordova-plugin-x-socialsharing/www/SocialSharing.js (126)

```

it seems like the exception is handled now as previously my app just crashed But still the issue exist and the images are not getting shared via the plugin. In whatsapp I got a toast saying "sharing failed"( I hope thats a toast from whatsapp and not the plugin) and in FB and Email i just got post/email without any image/attachments.


this is the code i used 

```
.controller("HomeController",function($scope) {
  
      $scope.shareIt =  function() {
        window.plugins.socialsharing.share('Message and image', null, 'img/Wiki-background.jpg', function(error) {console.log("ERROR IN SHARE",error)});
        // window.plugins.socialsharing.shareViaFacebook('Message via Facebook', 'img/Wiki-background.jpg', null /* url */, function() {console.log('share ok')}, function(errormsg){console.log("error in sharing",errormsg)});
      };
  
    });
```
Verified on my Nexus 6P running 8.0.0 Developer preview as well as Samsung S6 running 7.1.2.

**Note: the image is placed in www folder.**

just add that this issue exist in docs for now. I'll work on this issue during weekend and give you a PR.

**Comment by whodeee** [comment]
I'm having this same issue with Android 7.0 with an image at location `/storage/....`
I had to manually add `file://` to the front of the returned URL.

**Comment by Ragzzy-R** [comment]
@whodeee  did you tried the solutions i posted?

**Comment by whodeee** [comment]
@Ragzzy-R I did not try your solution, but I don't think it will work for what I was doing.  I was needing to access the phone storage, not files in the www folder.

**Comment by Ragzzy-R** [comment]
@whodeee  ohh then the android N file:// scheme access is the issue. There was a lot of permission changes past Nougat. Its been a while since I used Ionic and this plugin. So  I'm not sure if there is an update written for N's file access change.
