### ISSUE TITLE
whatsapp share not working when using 'share' instance method 

### ISSUE THREAD

**Issue by oliviya** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#817]
on sharing using social share plugin using share method, share via whatsapp is showing failed message, but share via all others are working. 
My code is as give below,

   this.platform.ready().then(() => {
  SocialSharing.share("title", "test_subject", "test_subject", "link");
  });

**Comment by ragunathans** [comment]
try this
SocialSharing.share("title", null, null, "link");
instead of
SocialSharing.share("title", "test_subject", "test_subject", "link");
