### ISSUE TITLE
[Error] TypeError: 'undefined' is not an object (evaluating 'window.plugins.socialsharing') 

### ISSUE THREAD

**Issue by agenceKanvas** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#82]
Hi ! 

I've installed the plugin using the add plugin command and it work fine.
Except that when I try to use the share function, I get the error : 
[Error] TypeError: 'undefined' is not an object (evaluating 'window.plugins.socialsharing')
    (anonymous function) (urbanquizz.js, line 231)

I've not modified my HTML, so I don't call the SocialSharing.js file.

Any idea ?

Thanks !

**Comment by rhenter** [comment]
Hi, I'm having the same problem. I check if condova.js are include in index.html and its OK. May you please help me ?
