### ISSUE TITLE
shareWithOptions is not sending  url image

### ISSUE THREAD

**Issue by julianCast** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#834]
- iOS:

Don't attach a valid image sharing to Whatsapp

- Android:

Don't attach valid image sharing to any app.

**Important note**: FILE FORMAT NOT SUPPORTED.Image passed as string url.

_Ionic 3.2.0_

**Comment by lesrpo** [comment]
Did you find a solutions for this problem? I am facing the same issue :(

**Comment by julianCast** [comment]
It's now working on version 5.4.1
