### ISSUE TITLE
Resize intent

### ISSUE THREAD

**Issue by wuilmerj24** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#837]
Is it possible to change the size of the map that is displayed?
I'm using ionic 3

**Comment by EddyVerbruggen** [comment]
What map?

**Comment by wuilmerj24** [comment]
@EddyVerbruggen  sorry I'm wrong. It is resizing the intent. To be displayed in a popup

**Comment by EddyVerbruggen** [comment]
Perhaps a screenshot of another app that has this feature is needed to shed some light on what you mean exactly..

**Comment by wuilmerj24** [comment]
@EddyVerbruggen 
![screenshot_20170603_170812](https://cloud.githubusercontent.com/assets/7539995/26757086/5cc94dea-487f-11e7-9a36-6d66e82f874e.png)
The facebook window To be able to give that size to the attempt of the social network

**Comment by EddyVerbruggen** [comment]
That's just what the OS does for you. Nothing I can change there..

**Comment by wuilmerj24** [comment]
But for it to work on android is it possible?
