### ISSUE TITLE
Class not found sharing message

### ISSUE THREAD

**Issue by josefbernadi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#857]
i have issue on sharing message.
i use telerik platform to build an apps. i try both automatic and manual installation but not working.
the error message show "class not found".
i use SocialShare version 5.1.1

i just try this sample code

`<script>
        
var options = {
  message: 'share this', 
  subject: 'the subject', 
  files: ['', ''], 
  url: 'https://www.website.com/foo/#bar?a=b',
  chooserTitle: 'Pick an app' 
}

var onSuccess = function(result) {
  alert("Share completed? " + result.completed); 
  alert("Shared to app: " + result.app); 
}

var onError = function(msg) {
  alert("Sharing failed with message: " + msg);
}

function share()
{
    window.plugins.socialsharing.share("prova","oggetto",null,null,onSuccess,onError);
}
    </script>`

what did i missed?

[socialshare.try1.zip](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/files/1171934/socialshare.try1.zip)

**Comment by EddyVerbruggen** [comment]
No takers, closing.

**Comment by pookdeveloper** [comment]
Any solution @josefbernadi ?

**Comment by josefbernadi** [comment]
Sorry... I can't help you @pookdeveloper

**Comment by pookdeveloper** [comment]
@josefbernadi did you try the plugin of capacitor?
 https://capacitor.ionicframework.com/docs/apis/share/
