### ISSUE TITLE
geo: 0,0 links to open navigator app

### ISSUE THREAD

**Issue by efstathiosntonas** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#858]
Is there an option to share geo:0,0 links so the user who receives/sees the link can tap it and open the phone navigator app?

**Comment by EddyVerbruggen** [comment]
Dunno, but please share if you were successful.

**Comment by HarelM** [comment]
I'm looking into using this on android but this is currently not possible.
I've seen that the code that need to run on android is the following:
```java
Uri gmmIntentUri = Uri.parse("geo:37.7749,-122.4194");
Intent mapIntent = new Intent(Intent.ACTION_VIEW, gmmIntentUri);
mapIntent.setPackage("com.google.android.apps.maps");
if (mapIntent.resolveActivity(getPackageManager()) != null) {
  startActivity(mapIntent);
}
```
Which is not what's currently is done when using a shareWithOptions with `url` as `geo:0,0` parameter.
I'm not sure what needs to be done in iOS though...

Can this issue be re-opened?
