### ISSUE TITLE
Android WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by MarkVaughn** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#86]
Is this permission needed if you only want to share text links?
If so, it might be worth to create a release that **does not** support sharing files. 
The reason being that the permission wording sounds very dodgy on android and the less permissions an app needs, the better. Especially if you are creating a new app and are relatively unknown.

**Comment by cobbdb** [comment]
So it sounds like the permission is only really needed to share images, am I understanding that right?

I am in the same boat as @MarkVaughn and it seems like I can just remove the permission from `plugin.xml` after I've installed it right? Do you know if that will cause any adverse effects by chance @EddyVerbruggen ? My app only supports sharing urls and messages - no images.

This plugin rocks btw! Love how clean the implementation is!

**Comment by cobbdb** [comment]
Just to follow up, been testing with the storage permission removed and it looks like it works perfectly since I'm not sharing images. Thanks again for this great plugin!

**Comment by EddyVerbruggen** [comment]
Thanks Dan, you're right: you only need the permission for image sharing. 

Cheers,
Eddy
