### ISSUE TITLE
Facebook and Twitter on iOS 11

### ISSUE THREAD

**Issue by seanwilson** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#860]
SocialSharing v5.1.8
Cordova v7.0.1
Cordova ios platform v4.4.0

Hi, I’ve had this plugin working for some time on both iOS and Android.

I’ve been testing it on iOS 11 recently and came across an issue with Facebook and Twitter.

With Facebook, it successfully posts the message to Facebook but my app pops up an alert with error message: “not available”. 

I’m logged into the Facebook app on my iOS device. I tap a button to bring up the Facebook sharing dialog using:

 window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint(msg, imageLink, null, 'Try pasting from the clipboard into your Facebook post - we\'ve pre-copied a message for you to use!', function() {console.log('share ok')}, function(errormsg){basicAlert("Error", errormsg,"OK")});

This code successfully posts the message and image to Facebook but it calls the error callback and I get an alert with error message: “not available”.

Twitter posts successfully too but I’m getting: "No Twitter Account. There are no Twitter accounts configured. You can add or create a Twitter account in Settings."

It seems Facebook and Twitter aren’t as deeply integrated into iOS with version 11 as they have been on recent versions which I suspect is causing the issue.

At the moment, it seems I’m stuck with a choice between:

1, The error message firing when it shouldn't, or
2, No error message firing when actually it should!

Has anybody got any ideas of how to get round this?

Thanks!

**Comment by EddyVerbruggen** [comment]
Indded looks like Apple has changed something for the "internal" social apps (the ones that can be configured in the iOS settings app). Those are now deprecated:

<img width="543" alt="screen shot 2017-08-12 at 09 46 02" src="https://user-images.githubusercontent.com/1426370/29239025-32d5fb96-7f43-11e7-9ac5-677e3a34bfd4.png">

Will look for an alternative..

**Comment by EddyVerbruggen** [comment]
From https://dev.twitter.com/twitterkit/ios/migrate-social-framework:

<img width="871" alt="screen shot 2017-08-12 at 10 01 26" src="https://user-images.githubusercontent.com/1426370/29239102-3aa4d0e8-7f45-11e7-9721-46b8356e1cc2.png">

Hmm.. I don't feed like adding a Twitter SDK and Facebook SDK and whatnot SDK.

**Comment by EddyVerbruggen** [comment]
So the internal sharing widget of iOS for Twitter and Facebook can no longer be relied upon; from iOS 11 onwards users need to have the Twitter or Facebook app installed to be able to share.

Facebook has this already implemented properly, but Twitter needs to change their app to make sure that pesky "No Twitter accounts configured" popup not appear when the Twitter app is installed on iOS 11. See [this link](https://twittercommunity.com/t/bug-in-ios-11/91490) for details.

This plugin should also be changed for iOS 11 to never use the internal share option. That's quite some work though.

**Comment by EddyVerbruggen** [comment]
Version 5.2.0 (later today on npm) should work OK with iOS11. Note that with Twitter you'll see the "no accounts configured" dialog but that's a bug in the Twitter app and will be fixed before iOS 11 is released (as noted in the link I previously shared in this thread).
