### ISSUE TITLE
Bug on Nexus 6P, Android 7

### ISSUE THREAD

**Issue by frontexpert** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#863]
SocialSharing v5.1.8
Cordova v7.0.1
Cordova ios platform v4.4.0

Nexus 6P, Android 7. sharing dialog is opening 12-15 times

**Comment by EddyVerbruggen** [comment]
I'm sorry but this must be something in your app. I have the exact same setup.

If you can reproduce this on a fresh cordova CLI app please share the repo and reopen.

**Comment by frontexpert** [comment]
Yea, you are right. it was my problem. Thanks!
