### ISSUE TITLE
Share with link instead of image

### ISSUE THREAD

**Issue by 1nfinite** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#870]
I am using the shareWithOptions with options as follow.
By default, when there is image file and url, facebook share will use image instead of url.
Is there any way to configure to give priority to url instead?

```
var options = {
  message: 'share this', // not supported on some apps (Facebook, Instagram)
  subject: 'the subject', // fi. for email
  files: ['image.jpg'],
  url: 'https://www.website.com/foo/#bar?a=b',
  chooserTitle: 'Pick an app' // Android only, you can override the default share sheet title
}
```

**Comment by muhzi4u** [comment]
@1nfinite Did you get any solution?

**Comment by 1nfinite** [comment]
@muhzi4u No. Do you have any suggestion?

**Comment by muhzi4u** [comment]
Yes.I just changed the implementation .First I will list all the possible options [Facebook, Whatsapp, etc] in a custom modal .
Whenever  we click on any option,

For Ex:
**Facebook** ,then the following code will execute.
```
$cordovaSocialSharing
    .shareViaFacebookWithPasteMessageHint(message, null, webUrl)
    .then(function(success) {
        console.log('shareViaFacebook Success', success);
    }, function(err) {
        console.log('shareViaFacebook failed', err);
});
```
**Whatsapp** ,then the following code will execute.
```

 $cordovaSocialSharing
    .shareViaWhatsApp(message, imagePath, webUrl)
    .then(function(success) {
        console.log('shareViaWhatsApp Success', success);
    }, function(err) {
        console.log('shareViaWhatsApp failed', err);
});
```

So different code will execute based on the option.If you have any doubt.Please let me know.Thanks

**Comment by 1nfinite** [comment]
@muhzi4u Thanks. But i am actually looking for a solution with `shareWithOptions`, something like 

```
var options = {
  priority: 'link'
};
```

**Comment by centogram** [comment]
PR here to resolve this https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/pull/1092
