### ISSUE TITLE
Android, can't share text via facebook, only the image

### ISSUE THREAD

**Issue by LorenzoZaccagnini** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#871]
Hi when I use the share function in iOS everything works correctly, but on Android the plugin on Facebook shares only the image and not the text or the url.

Thank you,
Lorenzo Zaccagnini

**Comment by RafaelLiendo** [comment]
Hi, I'm having the same issue. 
Tested on Android 7.0

>ionic info
cli packages: (C:\Users\_____\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Windows 10

Misc:

    backend : legacy

**Comment by RafaelLiendo** [comment]
Solved by passing null as the image parameter
`this.socialSharing.shareViaFacebook(message, null, url)`
Facebook fetches the image by itself and everything works!

**Comment by Nexeuz** [comment]
Thanks @LorenzoZaccagnini  for your answer but now seems that facebook does not sharing text only URL :(

**Comment by yechenchao** [comment]
I am having the same issue too, the facebook does not share any text, only url.

**Comment by EddyVerbruggen** [comment]
Closing as duplicate (search for it).
