### ISSUE TITLE
Strange problem with WhatsApp sharing.

### ISSUE THREAD

**Issue by ErHarinderSingh** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#874]
Hello Eddy, I have strange problem with WhatsApp sharing. When I am sharing it doesn't share full text. Text is arround 1000 lines but not share all lines!! What is the problem? Is there any limit to text?

Example:: If text = "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"  

It shares only this : "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"

**Comment by gustavosantosneto** [comment]
Same here

**Comment by ErHarinderSingh** [comment]
> Same here

WhatsApp have limited character's sharing option. Not an issue with Plugin.
