### ISSUE TITLE
Bug fix -> ShareStringForWhatsApp 

### ISSUE THREAD

**Issue by pedroayres** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#893]
I did a bug fix on ShareStringForWhatsApp
I changed the line 657 from SocialShare.m

Correct line:
NSString * encodedShareStringForWhatsApp = [NSString stringWithFormat:@"whatsapp://send?%@text=%@&phone=%@", abidString, encodedShareString, abid];

**Comment by EddyVerbruggen** [comment]
Thanks, I just fixed that in 5.3.0
