### ISSUE TITLE
Skype not coming in the common sharesheet

### ISSUE THREAD

**Issue by Gamerakki** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#895]
hi, 

i am trying to share using the sharesheet. I have skype install but its not showing in it. Here is the code snippet i used

 this.socialSharing.share('hi').then(() => {
      // Sharing done successfulllt

      console.log('shared successfully');
    }).catch((error) => {
      this.toastMsg.displayToast('You do not have skype application. Please install it for using',
        2000, 'botton');
      // Sharing  is not possible
      console.log(error);
    });

Please help in this rest other social app are seeing only skype is missing

**Comment by EddyVerbruggen** [comment]
Can you name an app that I can download that does offer sharing text to Skype?

I just tried the default iOS Notes app and didn’t see the Skype app pop up. 

Feel free to reopen with additional info.
