### ISSUE TITLE
If filename contain Chinese character,sharing will fail.

### ISSUE THREAD

**Issue by liweisi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#896]
The image's url contain Chinese character and has already been encoded by 'encodeURI'.
If filename contain Chinese character,sharing will fail.
If filename not contain Chinese character,sharing will success.

**Comment by EddyVerbruggen** [comment]
OK. I’ll probably can’t fix that issue any time soon so either try to fix it yourself or use a URL shortener.
