### ISSUE TITLE
iPhone-X view bouncing and cutting off tab bar

### ISSUE THREAD

**Issue by wilsolutions** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#900]
I'm using cordova-plugin-x-socialsharing 5.2.1 and in iPhone-X after the Popover comes and a simply cancel it, the screen bounces and the bottom 
of my screen seems to move down resulting a my tab bar getting cutted off.

**Comment by EddyVerbruggen** [comment]
I'm not sure that's caused by this plugin. But happy to learn anyones insights.

**Comment by wilsolutions** [comment]
Hi Eddy, pls let me take this back, after a mode deep checking I saw that it is not related to the plugin, in fact there was a legacy code in  the App calling `ionic.Platform.fullScreen( true, true );` that in my case resulted in the screen bouncing.

Please feel free to close this issue.

thank you!

**Comment by EddyVerbruggen** [comment]
👍
