### ISSUE TITLE
shareViaTwitter callback?

### ISSUE THREAD

**Issue by globules-io** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#901]
Hello,
All of your exemples using the old methods have callbacks but Twitter. Does that mean twitter alone doesn't have a callback?
I've tried
window.plugins.socialsharing.shareViaTwitter('MY TEXT', null, null, onPostSuccess, onPostError);   
none of my functions are triggered. Am I missing something? Thank you.

**Comment by zachonahill** [comment]
@globules-io Did you find out if there is a callback method?

**Comment by globules-io** [comment]
@zachonahill We ended up opting for a back end approach.
