### ISSUE TITLE
Sharing an HTML file to WhatsApp

### ISSUE THREAD

**Issue by borisreitman** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#907]
Hi,

I sent you $50 by PayPal, and I hope you can answer this question. Can you tell me if I will be able to share an HTML file to WhatsApp ? When using WhatsApp desktop or web, I am able to drag-and-drop into it an HTML file.  I would like to do the same from my cordova mobile app. 

Thanks,
Boris

**Comment by john-doherty** [comment]
Did you get an answer to this @borisreitman?

**Comment by EddyVerbruggen** [comment]
I looked into it, but I don't think you can share a file like that through programmatically.. I'd love to be wrong here so let me know if you find any code for Android and iOS to make that possible.

**Comment by borisreitman** [comment]
I found one way to do this. You can see a demo of this by downloading the Documents app by Readdle. When you are in WhatsApp you can attach any file from the apps sharing documents.  Readdle is able to share its documents so that WhatsApp sees them.

**Comment by john-doherty** [comment]
That sounds like the other way around, WhatsApp is querying the device looking for content?

**Comment by borisreitman** [comment]
I don't know the details, but it works.
