### ISSUE TITLE
Plugin is slow to load on app boot

### ISSUE THREAD

**Issue by canadaka** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#921]
We've been doing some investigation into speeding up our app's boot time and the `cordova-plugin-x-socialsharing` is by far the slowest loading plugin of the 20+ plugins we use. Most plugins are only a few ms, but socialsharing is consistently over 600ms.

Here is a snippet from the Xcode native iOS logs during app boot.
![image](https://user-images.githubusercontent.com/108178/36457969-74475a2e-1661-11e8-844c-1ef367c58f36.png)

Not sure if this is a known problem, do others experience this? Any idea why its so slow?

**Comment by EddyVerbruggen** [comment]
Interesting. Can you comment out [this bit](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/d5cc5b3dfe83c3eb11ddbb844f9195d834dc5a4d/src/ios/SocialSharing.m#L21-L23) and measure it again?

If that helps we can move that logic to a background thread.

**Comment by canadaka** [comment]
Yup that seems to do it, the plugin now took "0.339".

What does the cycleTheGlobalMailComposer do?

**Comment by EddyVerbruggen** [comment]
Thanks for confirming that! I guess app startup of many Cordova apps will be a bit quicker once this fix is implemented.

As for the reason, from an old comment in the code: https://stackoverflow.com/questions/25604552/i-have-real-misunderstanding-with-mfmailcomposeviewcontroller-in-swift-ios8-in/25604976#25604976
