### ISSUE TITLE
Hello, I can not share social apps including twitter and facebook, instagram, for ios 11.

### ISSUE THREAD

**Issue by jinqifeng** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#925]
This is a free plugin for which I'm no longer able to offer free support.

If you want me to look at your issue with priority (or at all) you may want to consider giving my PayPal account a bit of love. Details are in the readme.
Okay, I am ready to pay for your answer.
Thank you,
Eddy

**Comment by EddyVerbruggen** [comment]
Your question is really clear, and there's no code/project to look at. Did you add the `LSApplicationQueriesSchemes` as mentioned in the readme?

**Comment by jinqifeng** [comment]
this is config.xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.chaoyu.LOGO" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>ImageLogo</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <preference name="loadUrlTimeoutValue" value="700000" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
            <string>need camera access to take pictures</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
            <string>need photo library access to get pictures from there</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
            <string>need location access to find things nearby</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryAddUsageDescription">
            <string>need photo library access to save pictures there</string>
        </edit-config>
        <preference name="deployment-target" value="7.0" />
    </platform>
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    <plugin name="cordova-plugin-nativegeocoder" spec="^3.0.0">
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Use geocoder service" />
    </plugin>
    <plugin name="com.synconset.imagepicker" spec="~2.1.8">
        <variable name="PHOTO_LIBRARY_USAGE_DESCRIPTION" value="your usage message" />
    </plugin>
    <plugin name="cordova-plugin-facebook4" spec="^1.9.1">
        <variable name="APP_ID" value="538474589851127" />
        <variable name="APP_NAME" value="BLUFF" />
    </plugin>
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-camera" spec="^4.0.2" />
    <plugin name="cordova-plugin-device" spec="^2.0.1" />
    <engine name="android" spec="6.4.0" />
    <engine name="ios" spec="4.5.4" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.3.1" />
</widget>

this is package.json
{
  "name": "ImageLogo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/camera": "^4.5.3",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/crop": "^4.5.3",
    "@ionic-native/device": "^4.5.3",
    "@ionic-native/facebook": "^4.5.3",
    "@ionic-native/file": "^4.5.3",
    "@ionic-native/file-transfer": "^4.5.3",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/image-picker": "^4.5.3",
    "@ionic-native/native-geocoder": "^4.5.3",
    "@ionic-native/push": "^4.5.3",
    "@ionic-native/social-sharing": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "com.synconset.imagepicker": "~2.1.8",
    "cordova-android": "6.4.0",
    "cordova-instagram-plugin": "^0.5.2",
    "cordova-ios": "4.5.4",
    "cordova-plugin-add-swift-support": "^1.7.1",
    "cordova-plugin-camera": "^4.0.2",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-nativegeocoder": "^3.0.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-telerik-imagepicker": "^2.1.8",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.3.1",
    "es6-promise-plugin": "^4.1.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "konva": "^1.7.6",
    "ng2-dragula": "^1.5.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "@types/googlemaps": "^3.30.7",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-nativegeocoder": {
        "LOCATION_WHEN_IN_USE_DESCRIPTION": "Use geocoder service"
      },
      "com.synconset.imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "your usage message"
      },
      "cordova-plugin-facebook4": {
        "APP_ID": "538474589851127",
        "APP_NAME": "BLUFF"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-x-socialsharing": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}

this is code for instagram 

  if(this.platform.is('ios')){
          alert("ios-inst");
      //    this.socialSharing.canShareVia('com.apple.social.instagram', null,null,null).then(function(result) {  
      //      console.log(result); console.log("good");
            this.socialSharing.shareViaInstagram(null,this.photo)//
            .then((data) =>
            {
               console.log('Shared via shareViaInstagram');
              
               this.catSerivce.sharedResult(this.photoid,this.sharedata.userId,"InstagramShared").subscribe(snaps => {alert("Sharing Success!!!");});
                })
                .catch((err) =>
                {
                alert(JSON.stringify(err));
                  console.log('Was not shared via Instagram');
            });
     //     }, function(err) {
     //       console.log(err); console.log("no good");
     //       alert(JSON.stringify(err));
     //   });
        }

this show sheet ,but when click the instagram, popu up instagram and appear such text "something wrong... . " and does not post the image .

this is code for facebook.
facebookShare(){
    this.platform.ready()
     .then(() =>
     {
      this.socialSharing.canShareVia('com.apple.social.facebook', this.forminformation.logotext, this.photo, null)
        .then((data) =>
        { 
          alert(data);
          this.socialSharing.shareViaFacebook(this.forminformation.logotext, this.photo)
           .then((data) =>
           {
              console.log('Shared via Facebook');
              this.catSerivce.sharedResult(this.photoid,this.sharedata.userId,"fbShared").subscribe(snaps => {alert("Sharing Success!!!");});
           })
           .catch((err) =>
           {
            
             alert(err);
              console.log('Was not shared via Facebook');
           });
  
        })
        .catch((err) =>
        {
         
          alert(err);
           console.log('Not able to be shared via Facebook');
        });
  
     });
  }

this is code for twitter
twitterShare(){
    if (this.platform.is('ios')){
     
    /*     this.socialSharing.canShareVia('com.apple.social.twitter',this.forminformation.logotext,"bluff", null,null).then(function(result) {  
            console.log(result); console.log("good");
         */ 
            this.socialSharing.shareViaTwitter(this.forminformation.logotext,this.photo,null)
          .then((data)=>{
             alert(data);
             alert(JSON.stringify(data));
            //  alert(this.catSerivce.baseUrl);
            console.log("ok");
              this.catSerivce.sharedResult(this.photoid,this.sharedata.userId,'twitterShared').subscribe(snaps => {alert("Sharing Success!!!");});
            },
            (error)=>{
              alert(JSON.stringify(error));
          })

    /*    }, function(err) {
            console.log(err); console.log("no good");
            alert(JSON.stringify(err));
        })*/;
    }else{
///
   }
}

twitter and facebook both does not popu up share window. 

In the xcode debug , I found such error.

_SCExtensionLazyMatcher for com.app.share.Twitter.post continuous discovery block got extension ("<NSExtension:0x106857390>{id=com.appe.share.Twitter.post}") error (null).

this is same for facebook.

I hope you to help me. and let me know how much pay.
thank you

**Comment by jinqifeng** [comment]
I am going to denote. how can I do, and how can you know about me?
plz tell me

**Comment by jinqifeng** [comment]
![screenshot 1](https://user-images.githubusercontent.com/29983820/36962118-3a291b52-2089-11e8-94b9-68c2cd3f77b5.png)
I have donate for your socialsharing plugin and thank you for your effort.
I hope you to give me correct answer asap

**Comment by EddyVerbruggen** [comment]
Thanks. Can you strip your code down to the actual thing you're trying to share, with all the params replaced by their exact values? So for instance `.share("the actual text")` instead of `.share(myParam)`.

And are you using a real device, with Twitter and Facebook installed and configured? If so, which exact device?

**Comment by jinqifeng** [comment]
thank you for your reply.
this is code.
 this.socialSharing.shareViaFacebook("test", "http://www.ab7.it/apps/bluff/images/1520049717659.jpg")
           .then((data) =>
           {
              console.log('Shared via Facebook');
             
           })
           .catch((err) =>
           {
            
             alert(err);
              console.log('Was not shared via Facebook');
           });
  
this is device information
version: 11.2.2
model:MG472CH/A
serial number: DNPPH03(number 03)WG5MN.

and I am using real device with installed twitter and facebook and instagram.

**Comment by EddyVerbruggen** [comment]
What does `this.socialSharing` refer to? Is it Ionic Native?

**Comment by jinqifeng** [comment]
yes. this is code
import { SocialSharing } from '@ionic-native/social-sharing';
constructor(private socialSharing: SocialSharing) {
  ///
}

**Comment by jinqifeng** [comment]
sorry, i have missed 
import { SocialSharing } from '@ionic-native/social-sharing';

**Comment by jinqifeng** [comment]
why does not show " from '@ionic-native/social-sharing'"

**Comment by EddyVerbruggen** [comment]
Do you allow your app to fetch that non-https external image? https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

**Comment by jinqifeng** [comment]
I will try it. wait for a moment .

**Comment by jinqifeng** [comment]
hello,
now i am testing, but i have one question.
is this non-http problem cause only on ios 11

**Comment by jinqifeng** [comment]
hello.
I have tested with
 <key>NSAppTransportSecurity</key>
<dict>
     <key>NSAllowsArbitraryLoads</key><true/>
</dict>
but the result is same. app is crashed

**Comment by EddyVerbruggen** [comment]
App crashed? Hmm, can you try starting a new Cordova CLI app and add the share call to the index.html? If that crashes as well, please share the repo with me.

**Comment by jinqifeng** [comment]
sorry, I am new for ionic and github.
I did not understand your ask.
I am using cordova version 8.0.0, and npm --version 5.6.0.
Do you want me to give the full code to you?

**Comment by EddyVerbruggen** [comment]
I'm asking you to do `cordova create newapp`, add this plugin, and reproduce the error. That way all mumbo jumbo of Ionic, and other frameworks, is removed from the equation. If the error still occurs there, please share that code.

**Comment by jinqifeng** [comment]
do you mean? sudo ionic start "project name"?

**Comment by EddyVerbruggen** [comment]
No I mean plain old Cordova, so `cordova create newapp`, using the Cordova CLI. I don't want Ionic in the mix.

**Comment by jinqifeng** [comment]
dear, sir, sorry, I don,t know about cordova. I am only going to use your plugin in ionic.
could you review my code?
and this is error when app is crash.

 Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <MainViewController: 0x131d5d2a0>.'
>>*** First throw call stack:
>>(0x18639a364 0x1855e0528 0x18fcca148 0x18fccc800 0x18fcccd34 0x18fccc750 0x18fa2e388 0x100a100f0 0x100a0e9dc 0x100a3bcb0 0x1009e42b4 0x1009e4118 0x1009e5cf4 0x195802efc 0x1957974b0 0x1957995d8 0x19557ee64 0x195760880 0x19553e694 0x1955410a4 0x18d6eb984 0x18d6ebc44 0x18634297c 0x1863428fc 0x186342184 0x18633fd5c 0x18625fe58 0x18810cf84 0x18f9b467c 0x100994108 0x185d7c56c)
>>libc++abi.dylib: terminating with uncaught exception of type NSException
>>warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by jinqifeng** [comment]
I re-send more detail error.
 
SLExtensionLazyMatcher for com.apple.share.Twitter.post continuous discovery block got extensions (
    "<NSExtension: 0x107f71b00> {id = com.apple.share.Twitter.post}"
) error (null)
2018-03-05 17:27:18.447293+0800 ImageLogo[8021:2979151] [core] SLComposeViewController initWithServiceType got extension <NSExtension: 0x107f71b00> {id = com.apple.share.Twitter.post} for identifier com.apple.share.Twitter.post
2018-03-05 17:27:18.447393+0800 ImageLogo[8021:2979151] [core] SLComposeViewController initWithExtension: <NSExtension: 0x107f71b00> {id = com.apple.share.Twitter.post} requestedServiceType: com.apple.social.twitter
2018-03-05 17:27:18.472811+0800 ImageLogo[8021:2979151] [core] SLComposeViewController dealloc <SLComposeViewController: 0x109e5e3e0>
2018-03-05 17:27:40.599542+0800 ImageLogo[8021:2979151] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <MainViewController: 0x1017654d0>.'

**Comment by EddyVerbruggen** [comment]
Can you remove all the alerts (those popup dialogs) from your code? Looks like those are interfering with the share modal.

**Comment by jinqifeng** [comment]
this is made automatically from xcode.
I did not insert any alert for your plugin

**Comment by EddyVerbruggen** [comment]
Except for the fact that the code you shared has a lot of `alert('bla')` statements..

**Comment by jinqifeng** [comment]
I am building project withoiut alert now.
and in a hand, I have created cordova project and add your plugin. and now how can i test it?

**Comment by jinqifeng** [comment]
the result without alert is the same

**Comment by jinqifeng** [comment]
hello. this is also same. this plugin does not work.
this is code using only 

cordova

**Comment by jinqifeng** [comment]
this size is 10.5M so can not share it here.
i will send you email.

**Comment by jinqifeng** [comment]
Ok, this is source code without node-model and platform

**Comment by jinqifeng** [comment]
[Archive.zip](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/files/1780689/Archive.zip)

**Comment by jinqifeng** [comment]
hello, when can you give me answer?

**Comment by jinqifeng** [comment]
How are you?
I have tested with only cordova, But the result is bad, your twitter button does not work. Does it mean this plugin has bug?
Plz tell me how can share social

**Comment by jinqifeng** [comment]
hello,
why did not support for it to me?
Do you want to donate more?

**Comment by jinqifeng** [comment]
you did not give me any resolution. Plz help me

**Comment by jinqifeng** [comment]
Hello, I don,t want to leave here bad review. If you want to get more money, Plz let me kwno about solution, or your opinion. I am mot patient

**Comment by EddyVerbruggen** [comment]
Are you for real? You ask me a question yesterday and I was investigating it. Then during my night, you send many more (non-helpful) messages. I'll invest my energy in other issues.

**Comment by Amin0096** [comment]
Hello EddyVerbruggen, 
Is it possible restrict few app in pop-up using social sharing with share option.
