### ISSUE TITLE
es6 promise ?

### ISSUE THREAD

**Issue by matrixreal** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#932]
Hello,
i did install the lastest social sharing plugin but i cant see the es6 promise plugin in te plugin list
did you remove it or something ?
thanks for reply

**Comment by matrixreal** [comment]
hello guys
is the es6 promise a necessary plugin ?
thank you

**Comment by EddyVerbruggen** [comment]
The version was changed - see #927.

**Comment by matrixreal** [comment]
because when i install the new plugin i can't see the es6 promise plugin in the cordova plugin list
can you confirm that ?
