### ISSUE TITLE
shareViaFacebook callback return "not available"

### ISSUE THREAD

**Issue by peterpeterparker** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#944]
Hi Eddy,

Unfortunately I can't tell after which of the last updates of the plugin this error began to pop up but on my iPhone 6s/iOS 11 when I call `shareViaFacebook` and successfully having share the content on Facebook, I get as a result an error callback containing "not available"

    this.socialSharing.shareViaFacebook('something'' 'https://something.com/img.jpg').then((result) => {
        console.log('Cool beans');
     }, (errorMsg: string) => {
         console.log('Not cool: ', errorMsg); // -> gonna print "Not cool: not available"
     });

I thought I would report it in case it would be a bug

Best regards

**Comment by shawns582** [comment]
@peterpeterparker @EddyVerbruggen any progress on this? I am getting a Facebook is not available and Twitter is not available error on iOS. Would appreciate any help. Thanks!

**Comment by peterpeterparker** [comment]
Forgot about that, I don't use the feature therefore I close my issue because I won't be able to reproduce or track it anymore
