### ISSUE TITLE
Share via WhatsApp

### ISSUE THREAD

**Issue by natalinacinovicmrf** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#949]
Hi,

I am having an issue while trying to share content via Whatsapp.
The code crashes here in SocialSharing.m
```
NSArray *filenames = [command.arguments objectAtIndex:2];
NSString *urlString = [command.arguments objectAtIndex:3];
NSString *abid = [command.arguments objectAtIndex:4];
NSString *phone = [command.arguments objectAtIndex:5];
```

specifically on the last line, when it tries to access the argument with the index 5.

```
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 5 beyond bounds [0 .. 4]'
...
terminating with uncaught exception of type NSException
```

Any ideas what I could be doing wrong?
I haven't made any modifications to the plugin.

**Comment by EddyVerbruggen** [comment]
You're not manually including SocialSharing.js in your code, right?

Please share a project reproducing this issue.

**Comment by natalinacinovicmrf** [comment]
I figured out my issue, the native files weren't updated so shareViaWhatsApp function had only 5 arguments, instead of 6.
