### ISSUE TITLE
Vera scan flaw "CWE-73: External Control of File Name or Path" on SocialSharing.java file

### ISSUE THREAD

**Issue by vchandran1** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#956]
Hi 

We are using this open plugin and we are getting below flaw on the vera scan report.

nl/.../plugins/SocialSharing.java line no 761  ( Method name saveFile)

External Control of File Name or Path (CWE ID 73)(1 flaw)
Description
This call contains a path manipulation flaw. The argument to the function is a filename constructed using untrusted
input. If an attacker is allowed to specify all or part of the filename, it may be possible to gain unauthorized access to
files on the server, including those outside the webroot, that would be normally be inaccessible to end users. The level
of exposure depends on the effectiveness of input validation routines, if any.
Effort to Fix: 2 - Implementation error. Fix is approx. 6-50 lines of code. 1 day to 

Please let us know if this can be fixed.

**Comment by EddyVerbruggen** [comment]
What? You mean this?

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/b231f855d25330031458f8fc703a405b80d63d97/src/android/nl/xservices/plugins/SocialSharing.java#L761-L766

**Comment by EddyVerbruggen** [comment]
I have no questions. If you need something changed, please send a PR. I have zero incentive to change anything related to those methods.
