### ISSUE TITLE
facebook and twitter sharing issue in ios

### ISSUE THREAD

**Issue by amulyadande** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#960]
hi Eddy,

am using social sharing native plugin, but everything is shareable in android(especially facebook and twitter).
but in ios pre-populated message is not displaying in facebook and in twitter icon is missing and these things are fine in android...here is my code, help me plz
for facebook,,,,,,,,,,,,,,,,,,,,,,,,,
this.socialSharing.shareViaFacebook("Shared via Facebook :"+this.permalink, null /*Image*/,  "")
      .then(()=>{         
        alert("success");
        })
        .catch(()=>{
           alert("Facebook app not installed in your mobile")
        }) 
for twitter,,,,,,,,,,,,,,,,,,,
this.socialSharing.shareViaTwitter("Shared via Twitter :"+this.permalink, null /*Image*/,  "")
      .then(()=>{
         alert("success");
        })
        .catch(()=>{
           alert("Twitter app not installed in your mobile")
        })
thankyou,
amulya.

**Comment by holospeed** [comment]
I think this issue is related with the new Facebook policy https://developers.facebook.com/policy/#control
