### ISSUE TITLE
Facebook link sharing issue

### ISSUE THREAD

**Issue by shkar62** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#963]
I am working on Facebook link sharing in iOS.

`let content = FBSDKShareLinkContent()
let contentUrl = "https://developers.facebook.com"
content.contentURL =  URL(string: contentUrl)
let dialog = FBSDKShareDialog()
        dialog.mode = FBSDKShareDialogMode.automatic
        dialog.shareContent = content
        dialog.delegate = self as FBSDKSharingDelegate
        dialog.fromViewController = self
        dialog.show()`

This is my code. When I click on Post button in the share dialog, I always get error : There was some problem in sharing the link.

Can somebody assist?

**Comment by EddyVerbruggen** [comment]
That code doesn't relate to this project. Wrong repo?
