### ISSUE TITLE
Outlook mail App on iOS

### ISSUE THREAD

**Issue by jb280** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#968]
This plugin works great for sharing things via email with standard iOS mail. I have a customer using OutLook app as their mailer,  and Outlook is not started when I call  shareviaemail().  Any suggestions on how to help them?

Jeff

**Comment by EddyVerbruggen** [comment]
Dunno, never used that app. If anyone has a suggestion, please reopen.
