### ISSUE TITLE
iOS > window.plugins undefined

### ISSUE THREAD

**Issue by michaelpeterlee** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#985]
This Cordova plugin works on Android but not iOS; window.plugins is undefined.

I'm investigating now and will update this issue as I progress.

**Comment by michaelpeterlee** [comment]
ionic cordova plugin rm  cordova-plugin-inappbrowser
ionic cordova plugin add cordova-plugin-inappbrowser

We had to delete android/app/src/main/res/xml/sharing_paths.xml

**Comment by mesqueeb** [comment]
Do I need `cordova-plugin-inappbrowser` for this to work?
