### ISSUE TITLE
Compilation failure for Android in v5.4.2

### ISSUE THREAD

**Issue by leMaik** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#995]
First of all, thank you for this great plugin! :tada:
Everything worked nice until 3 hours ago. It looks like in 5.4.2, the plugin doesn't compile anymore for Android?

It fails with the following message:

```
Error: .../platforms/android/gradlew: Command failed with exit code 1 Error output:

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:191: error: diamond operator is not supported in -source 1.6

        List<LabeledIntent> labeledIntentList = new ArrayList<>();

                                                              ^

  (use -source 7 or higher to enable diamond operator)

1 error
```

I'd appreciate any suggestion on how to fix this. I couldn't find a solution yet, other than downgrading.

**Comment by ph-eh** [comment]
Also getting the same error, but Im on v5.4.0

**Comment by leMaik** [comment]
@EddyVerbruggen Thank you for the prompt response and fix. :+1:

**Comment by subranil** [comment]
i was using the latest version of cordova. so, it didn't get that. @EddyVerbruggen for solving that
