### ISSUE TITLE
Phonegap build fail plugin

### ISSUE THREAD

**Issue by AldeirJampier** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#996]
Hello, today the phonegap is crashing when trying to compile the application with the plugin. I have already removed and added new, but, to no avail. Do you have a solution?

**Comment by tipaulohenriquefernandes** [comment]
I've got the same problem

**Comment by AldeirJampier** [comment]
@tipaulohenriquefernandes I solved my problem using version 5.1.8. Add in your config.xml and try to build. Come back here and tell us, to see if it worked.

<plugin name="es6-promise-plugin" spec="4.2.2"/>
<plugin name="cordova-plugin-x-socialsharing" spec="5.1.8"/>

**Comment by AldeirJampier** [comment]
@tipaulohenriquefernandes  I solved my problem using version 5.1.8. Add in your config.xml and try to build. Come back here and tell us, to see if it worked.

plugin name="es6-promise-plugin" spec="4.2.2"
plugin name="cordova-plugin-x-socialsharing" spec="5.1.8"

**Comment by tipaulohenriquefernandes** [comment]
I added 

<plugin name="cordova-plugin-x-socialsharing" spec="5.1.8" 

and now it worked.

Thank you AldeirJampier

**Comment by ruvenss** [comment]
> I added
> 
> <plugin name="cordova-plugin-x-socialsharing" spec="5.1.8"
> 
> and now it worked.
> 
> Thank you AldeirJampier

Thank you it works on mine also

**Comment by AustP** [comment]
I just ran into this as well. The error said something about ANDROID_SUPPORT_V4_VERSION but I just set my spec to 5.4.1 and it worked.

**Comment by chrismillican** [comment]
I am still running into this issue even when adding the plugin name and spec to my config.xml which is as follows:

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.divemeet.calculator" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MeetCalculator</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-android-support-gradle-release" spec="~2.0.1" />
    <plugin name="cordova-plugin-x-socialsharing" spec="~5.4.4">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.1+" />
    </plugin>
</widget>

When I run "cordova build android" I run into the following error message:
* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not get unknown property 'ANDROID_SUPPORT_V4_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Does anyone have any suggestions on why I might be still running into this issue?

**Comment by AldeirJampier** [comment]
@chrismillican change "~5.4.4" to "5.1.8" report the same way.

**Comment by noveweb** [comment]
+1
